import {EXAMPLE_CASE,DOCUMENT_EXAMPLES,EXAMPLE_REFERENCES} from './document-examples.mjs';
import {schedule,workdayDate} from './visual-model.mjs';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:2});
let kind=new URLSearchParams(location.search).get('doc')||'charter',comparison=false;
if(!Object.hasOwn(DOCUMENT_EXAMPLES,kind))kind='charter';
const safeHref=url=>/^https?:\/\//.test(url)?url:'#';
function table(columns,rows){return `<div class="doc-table-wrap" tabindex="0" role="region" aria-label="문서 근거 표"><table><thead><tr>${columns.map(c=>`<th scope="col">${esc(c.label||c)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map((c,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${esc(Array.isArray(row)?row[i]:row[c.key])}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const paragraphs=items=>(Array.isArray(items)?items:[items]).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('');
function section(s,i){return `<section class="doc-section" id="document-${esc(s.id)}"><h3><span class="doc-section-num">${String(i+1).padStart(2,'0')}</span>${esc(s.title.replace(/^\d+\.\s*/,''))}</h3>${paragraphs(s.paragraphs)}${s.bullets?`<ul>${s.bullets.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}${s.table?table(s.table.columns,s.table.rows):''}</section>`;}
function control(c){const labels={documentId:'문서 번호',version:'문서 버전',asOf:'기준일',preparedBy:'작성',reviewedBy:'검토',decisionAuthority:'결정 권한',classification:'자료 구분'};return `<dl class="doc-control">${Object.entries(labels).filter(([key])=>c[key]!=null).map(([key,label])=>`<div><dt>${label}</dt><dd>${esc(Array.isArray(c[key])?c[key].join(' / '):c[key])}</dd></div>`).join('')}</dl>`;}
function charterFigure(v){
 const rows=v.trace||[],h=76+rows.length*99;
 const cols=[{x:15,w:218,label:'업무 요구'},{x:265,w:218,label:'인도물'},{x:515,w:263,label:'인수·검증 증거'},{x:810,w:175,label:'확인 책임'}];
 const lines=(text,n=18)=>{const words=String(text??'').split(' '),out=[];let line='';for(const word of words){if((line+' '+word).trim().length>n&&line){out.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)out.push(line);return out;};
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 ${h}" role="img" aria-label="업무 요구에서 인도물, 인수 증거, 책임자로 이어지는 추적 관계"><defs><marker id="doc-trace-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="#92a6c8"/></marker></defs>${cols.map(c=>`<text x="${c.x+8}" y="25" fill="#52647f" font-size="13">${c.label}</text>`).join('')}${rows.map((r,i)=>cols.map((c,j)=>{const y=47+i*99,text=[r.requirement,r.deliverable,r.evidence,r.owner][j];return `${j<3?`<path d="M${c.x+c.w},${y+35} H${cols[j+1].x-7}" stroke="#92a6c8" marker-end="url(#doc-trace-arrow)"/>`:''}<rect x="${c.x}" y="${y}" width="${c.w}" height="74" rx="4" fill="${j===0?'#edf2fc':'#fff'}" stroke="#b8c8df"/><text x="${c.x+11}" y="${y+24}" fill="#243b61" font-size="13">${lines(text,j===3?13:j===2?24:19).map((l,k)=>`<tspan x="${c.x+11}" dy="${k?18:0}">${esc(l)}</tspan>`).join('')}</text>`;}).join('')).join('')}</svg>`;
 return `<figure class="doc-figure"><div tabindex="0" role="region" aria-label="가로로 이동 가능한 문서 그림">${svg}</div><figcaption>화살표는 추적 관계입니다. 문서의 범위·인수 기준표에서 상세 조건과 원천 번호를 함께 확인합니다.</figcaption></figure>`;
}
function gantt(v,view='baseline'){
 const base=schedule(v.activities),chosen=view==='current'?v.currentActivities:view==='proposed'?v.proposedActivities:view==='forecast'?v.proposedCurrentActivities:v.activities;
 const calc=schedule(chosen||v.activities),max=Math.max(base.finish,calc.finish),width=980,left=305,right=24,scale=(width-left-right)/Math.ceil(max/5)/5,row=47,top=65,h=top+calc.activities.length*row+44;
 const labels={baseline:'기준선',current:'현재 범위 완료예측',proposed:'변경 제안 · 원안 대비',forecast:'변경 제안 · 현재 지연 반영'};
 const baseMap=new Map(base.activities.map(a=>[a.id,a]));
 const byId=new Map(calc.activities.map((a,i)=>[a.id,{...a,y:top+i*row}]));
 const ticks=Array.from({length:Math.ceil(max/5)+1},(_,i)=>i*5);
 const grid=ticks.map(d=>`<line x1="${left+d*scale}" x2="${left+d*scale}" y1="42" y2="${h-28}" stroke="#dfe6f1"/><text x="${left+d*scale}" y="32" text-anchor="middle" font-size="12" fill="#52647f">${d}</text>`).join('');
 const deps=calc.activities.flatMap(a=>a.predecessors.map(p=>{const from=byId.get(p),to=byId.get(a.id),x=left+from.ef*scale,end=left+a.es*scale;return `<path d="M${x},${from.y+10}H${x+6}V${to.y+10}H${end}" fill="none" stroke="#93a8cb" stroke-width="1"/>`;})).join('');
 const rows=calc.activities.map(a=>{const y=byId.get(a.id).y,b=baseMap.get(a.id),w=a.duration*scale;return `<text x="10" y="${y+9}" font-size="13" font-weight="600" fill="#1c345a">${esc(a.id+' '+a.name)}</text><text x="10" y="${y+29}" font-size="10" fill="#52647f">${esc(a.wbs||'')} / ${esc(a.owner)} / ${workdayDate(v.startDate,a.es)}–${workdayDate(v.startDate,a.ef-1).slice(5)}</text><rect x="${left+a.es*scale}" y="${y-5}" width="${w}" height="21" rx="2" fill="${a.critical?'#3056c9':'#acbcda'}"/><text x="${left+(a.es+a.duration/2)*scale}" y="${y+10}" text-anchor="middle" fill="${a.critical?'#fff':'#213555'}" font-size="11">${a.duration}일</text>${b?`<rect x="${left+b.es*scale}" y="${y+22}" width="${b.duration*scale}" height="8" fill="none" stroke="#8b9bb8" stroke-dasharray="3 2"/>`:''}`;}).join('');
 const figure=`<figure class="doc-figure"><div tabindex="0" role="region" aria-label="가로로 이동 가능한 문서 그림"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${h}" role="img" aria-label="${labels[view]}, ${calc.finish}영업일, 완료 ${workdayDate(v.startDate,calc.finish-1)}">${grid}${deps}${rows}<text x="${left}" y="${h-7}" font-size="11" fill="#52647f">착수 후 경과 영업일 / 실선: 선택한 안 / 점선: 기준선 / 진한 막대: 총여유 0</text></svg></div><figcaption><strong>${labels[view]}</strong> · ${calc.finish}영업일 · ${workdayDate(v.startDate,calc.finish-1)} 완료. 월~금, FS·Lag 0. 공휴일·자원 평준화 미적용. 책임자 표시는 자원 가용성 승인의 증거가 아닙니다.</figcaption></figure>`;
 return figure+table([{key:'id',label:'활동'},{key:'pred',label:'선행'},{key:'duration',label:'기간'},{key:'es',label:'ES'},{key:'ef',label:'EF'},{key:'float',label:'총여유'},{key:'date',label:'완료일'}],calc.activities.map(a=>({...a,pred:a.predecessors.join(', ')||'없음',date:workdayDate(v.startDate,a.ef-1)})));
}
function performance(v){
 const points=v.periods||[],keys=[{id:'pv',label:'PV 계획가치',color:'#677f9f'},{id:'ev',label:'EV 획득가치',color:'#3056c9'},{id:'ac',label:'AC 실제원가',color:'#93651b'}];
 const w=940,h=310,left=65,right=35,top=35,bottom=56,max=Math.ceil(Math.max(...points.flatMap(r=>keys.map(k=>r[k.id]??0)),1)/25000000)*25000000,x=i=>left+i*(w-left-right)/Math.max(points.length-1,1),y=n=>h-bottom-n*(h-top-bottom)/max;
 const ticks=Array.from({length:Math.round(max/25000000)+1},(_,i)=>i*25000000);
 const grid=ticks.map(n=>`<path d="M${left},${y(n)}H${w-right}" fill="none" stroke="#dfe6f1"/><text x="${left-12}" y="${y(n)+4}" text-anchor="end" fill="#52647f" font-size="12">${money(n/1000000)}</text>`).join('');
 const reportIndex=points.findIndex(p=>p.date===v.asOf),reportX=reportIndex>=0?x(reportIndex):null;
 const boundary=reportX===null?'':`<rect x="${reportX}" y="${top}" width="${w-right-reportX}" height="${h-top-bottom}" fill="#f5f7fb"/><path d="M${reportX},${top}V${h-bottom}" stroke="#8393ae" stroke-dasharray="3 4"/><text x="${reportX+10}" y="18" font-size="12" fill="#52647f">보고 기준일 ${esc(v.asOf)} → 이후는 계획만 표시</text>`;
 const curves=keys.map(k=>`<path d="${points.map((p,i)=>p[k.id]==null?'':(i===0||points[i-1][k.id]==null?'M':'L')+x(i)+','+y(p[k.id])).join(' ')}" fill="none" stroke="${k.color}" stroke-width="3" ${k.id==='pv'?'stroke-dasharray="7 4"':''}/>${points.map((p,i)=>p[k.id]==null?'':`<circle cx="${x(i)}" cy="${y(p[k.id])}" r="4" fill="${k.color}"/>`).join('')}`).join('');
 return `<figure class="doc-figure"><div tabindex="0" role="region" aria-label="가로로 이동 가능한 문서 그림"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="동일 기준선과 보고일의 누적 PV EV AC 추이, 단위 백만원">${boundary}${grid}${curves}<text x="${left}" y="18" font-size="12" fill="#52647f">백만원 · 누적</text>${points.map((p,i)=>`<text x="${x(i)}" y="${h-31}" text-anchor="middle" fill="#52647f" font-size="12">${esc(p.date.slice(5))}</text>`).join('')}${keys.map((k,i)=>`<line x1="${220+i*210}" x2="${245+i*210}" y1="${h-7}" y2="${h-7}" stroke="${k.color}" stroke-width="3"/><text x="${254+i*210}" y="${h-3}" font-size="12" fill="#344965">${k.label}</text>`).join('')}</svg></div><figcaption>세 선은 동일한 보고기간·원가 범위의 누적 값입니다. AC는 발생 원가이고 지급액과 구분합니다. 점선 PV는 승인 기준선이며, 미래 예측을 실적으로 연결하지 않습니다.</figcaption></figure>`+table([{key:'date',label:'기준일'},{key:'pv',label:'PV (원)'},{key:'ev',label:'EV (원)'},{key:'ac',label:'AC (원)'}],points.map(p=>({...p,pv:money(p.pv),ev:p.ev==null?'아직 없는 실적':money(p.ev),ac:p.ac==null?'아직 없는 실적':money(p.ac)})));
}
function visuals(doc){const v=doc.visual||{};if(v.type==='charter')return charterFigure(v);if(v.type==='schedule')return `<div class="doc-visual-tools"><label for="doc-schedule-view">겹쳐 볼 일정</label><select id="doc-schedule-view"><option value="baseline">기준선</option><option value="current">현재 범위 완료예측</option><option value="proposed">변경 제안 · 원안 대비</option><option value="forecast">변경 제안 · 현재 지연 반영</option></select></div><div id="doc-gantt">${gantt(v)}</div>`;if(v.type==='change')return performance(v);return '';}
function render(){
 const doc=DOCUMENT_EXAMPLES[kind],c=doc.control;
 history.replaceState(null,'','documents.html?doc='+kind);
 document.querySelectorAll('[data-document]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.document===kind)));
 const revColumns=[{key:'version',label:'버전'},{key:'date',label:'일자'},{key:'change',label:'변경 내용'},{key:'by',label:'작성'}];
 $('#doc-paper').innerHTML=`<article class="pm-document" data-kind="${kind}"><header class="doc-masthead"><div><p class="doc-id">${esc(c.documentId)} / ${esc(c.version)}</p><h2>${esc(doc.title)}</h2><p class="doc-subtitle">${esc(doc.subtitle)}</p></div><span class="doc-state">${esc(c.status)}</span></header>${control(c)}<div class="doc-decision"><strong>이 문서에서 요청하는 결정</strong>${paragraphs(doc.decisionRequest)}</div><section class="doc-section" id="document-summary"><h3>검토 요약</h3>${paragraphs(doc.summary)}</section><section class="doc-section" id="document-visual"><h3>${{charter:'요구에서 인수 증거까지',schedule:'기준선·현재 예측·변경안',change:'실적 추이와 편차의 근거'}[kind]}</h3>${visuals(doc)}</section>${doc.sections.map(section).join('')}<section class="doc-section" id="document-review"><h3>검토 의견과 처리 상태</h3>${table([{key:'id',label:'의견 ID'},{key:'reviewer',label:'검토자'},{key:'comment',label:'검토 의견'},{key:'response',label:'반영·후속조치'},{key:'status',label:'상태'}],doc.reviewComments)}</section><section class="doc-section" id="document-history"><h3>개정 이력</h3>${table(revColumns,doc.revisionHistory)}</section><section class="doc-section" id="document-sources"><h3>근거와 연결 문서</h3>${Array.isArray(doc.sources)?'<ul>'+doc.sources.map(s=>`<li>${esc(typeof s==='string'?s:Object.values(s).join(' / '))}</li>`).join('')+'</ul>':''}<p class="doc-footnote">PREVIEW-02 교육용 가상 사례. 문서 구조를 보여 주는 검토 초안이며 실제 회사의 서명·승인·프로젝트 실적이 아닙니다. 실제 실습에는 MP-01의 해당 시점 원천자료를 사용하세요.</p></section><footer class="doc-footer"><span>${esc(c.documentId)} / ${esc(c.version)} / ${esc(c.asOf)}</span><span>별도 가상 사례 / 검토용</span></footer></article>`;
 $('#doc-toc').innerHTML='<strong>이 문서에서 확인할 것</strong>'+[{id:'summary',title:'검토 요약'},{id:'visual',title:'그림·계산 근거'},...doc.sections,{id:'review',title:'검토와 처리'},{id:'history',title:'개정 이력'},{id:'sources',title:'근거 문서'}].map(s=>`<a href="#document-${esc(s.id)}">${esc(s.title)}</a>`).join('');
 $('#doc-comparison').innerHTML=`<div class="doc-comparison"><div><h2>${esc(doc.before.title)}</h2>${paragraphs(doc.before.paragraphs)}<p class="doc-footnote">같은 사례를 짧게 요약했을 때 빠지기 쉬운 정보입니다.</p></div><div><h2>검토 문서에서 보완한 것</h2><ul>${doc.before.missing.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p>아래 문서에서 실제로 어디에 들어갔는지 확인하고, 자신의 양식에 필요한 항목을 적용하세요.</p></div></div>`;
 $('#doc-comparison').hidden=!comparison;
 $('#doc-next').innerHTML=`<h2>이 구조를 내 문서에 적용하기</h2><p>예시의 수치를 복사하기보다 자신의 근거·판단·검토 의견이 어디에 들어가야 하는지 대조합니다. 워크북에서는 현재 조건의 그림과 해석을 묶고, 교재에서는 전체 문서 양식을 작성·미리보기로 확인합니다.</p><a href="${esc(doc.workbookLink)}">${doc.unit}단원 시각화 실습</a><a href="learn.html?unit=${doc.unit}&view=practice&step=${{charter:'charter-3',schedule:'6.5',change:'7.4'}[kind]}&phase=practice">교재에서 문서 작성</a>`;
 $('#doc-references').innerHTML='<p>'+esc(EXAMPLE_CASE.policyNotice)+'</p><p>서식은 공개 지침의 관리 항목을 참고해 이 교재에 맞게 새로 구성했습니다. 특정 조직의 공식 표준 양식이나 법규 준수 증명으로 제시하지 않습니다.</p><ul>'+EXAMPLE_REFERENCES.map(r=>`<li><a href="${esc(safeHref(r.url))}" target="_blank" rel="noopener">${esc(r.title)}</a> — ${esc(r.usedFor||r.note||'')}<br>${esc(r.limits||'')} · 확인 ${esc(r.accessed||'')}</li>`).join('')+'</ul>';
 const select=$('#doc-schedule-view');if(select)select.onchange=()=>{$('#doc-gantt').innerHTML=gantt(doc.visual,select.value);$('#doc-message').textContent=select.selectedOptions[0].textContent+'을 표시합니다. 원안과 제안의 문서 번호·검토 상태는 아래 표에서 함께 확인하세요.';};
}
document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>{kind=b.dataset.document;$('#doc-message').textContent='';render();});
function compare(value){comparison=value;$('#doc-comparison').hidden=!value;$('#doc-complete').setAttribute('aria-pressed',String(!value));$('#doc-compare').setAttribute('aria-pressed',String(value));}
$('#doc-complete').onclick=()=>compare(false);$('#doc-compare').onclick=()=>compare(true);
$('#doc-print').onclick=()=>window.print();
$('#doc-export').onclick=async()=>{try{const r=await fetch('pm-document.css');if(!r.ok)throw Error('문서 서식을 불러오지 못했습니다. 새로고침 후 다시 시도하세요.');const css=await r.text(),copy=$('#doc-paper').cloneNode(true);copy.querySelectorAll('.doc-visual-tools').forEach(el=>el.remove());copy.querySelectorAll('a[href]').forEach(a=>a.href=new URL(a.getAttribute('href'),location.href).href);const doc=DOCUMENT_EXAMPLES[kind],html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(doc.title)}</title><style>body{margin:0;background:#edf1f7;padding:28px}main{max-width:1120px;margin:auto}${css}@media print{body{padding:0;background:white}}</style><main>${copy.innerHTML}</main></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`PREVIEW-02_${kind}_검토문서.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#doc-message').textContent='현재 그림과 문서가 포함된 HTML 다운로드를 요청했습니다. 실제 파일을 확인하세요.';}catch(e){$('#doc-message').textContent=e.message;}};
try{render();}catch(e){$('#doc-message').textContent='예시를 표시하지 못했습니다: '+e.message;console.error(e);}
