'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles=['회사에 합류하기','프로젝트 착수','요구사항과 범위','일정과 자원','원가와 예산','품질과 리스크','조달과 협업','계획 통합과 실행','성과와 변경 통제','검수·이관·종료'];
const stages={S0:'착수 전',S0A:'헌장 승인',S1:'분야 계획',S1A:'통합 승인·킥오프',S2:'실행·변경 분석',S3:'변경 승인',S4:'검수·종료'};
const briefs=[
 ['회사 자료를 보고 돈·업무·담당자를 구분합니다.','준비 문서는 없습니다. S01 사업제안을 함께 읽는 첫 단계부터 시작하세요.','필요하면 G00 업무 파악 메모를 남깁니다. 다음에는 사업 필요·경계·권한을 헌장에 연결합니다.'],
 ['프로젝트를 시작하는 이유와 PM의 권한을 근거로 설명합니다.','0단원에서 읽은 S01·S02·S03·S17을 사용합니다. D01은 승인 전 초안으로 시작합니다.','D01 헌장, D30 이해관계자, A01 가정 로그를 만듭니다. 역할별 검토 후 승인 조건을 대조합니다.'],
 ['현업의 요청을 시험할 수 있는 요구와 작업 범위로 바꿉니다.','헌장의 목적·경계와 인터뷰를 가져옵니다. 요구사항을 곧바로 개발 작업으로 바꾸지 말고 인수조건부터 확인하세요.','D08~D11의 요구·추적·범위·WBS를 연결합니다. 다음에는 각 작업의 활동·담당·기간을 정합니다.'],
 ['어떤 일을 누구와 어떤 순서로 끝낼지 설명할 수 있는 일정을 만듭니다.','WBS와 완료조건을 가져옵니다. 자원의 수량과 가용성을 확인한 뒤 기간·날짜를 계산합니다.','D13/D14 일정과 D21 자원을 작성합니다. 위험·계약 조건을 확인한 뒤 계획으로 돌아와 갱신합니다.'],
 ['작업 비용과 현금 지급을 구분하고 예산 초안을 만듭니다.','활동·투입량·단가를 가져옵니다. 회사 현금이나 가맹점 정산금은 프로젝트 예산과 다릅니다.','D15~D17 추정·관리계획·예산을 작성합니다. 위험 분석 후 예비비를 재검토하고 통합 승인에 올립니다.'],
 ['품질의 합격 기준과 위험 발생 전의 대응을 정합니다.','요구의 인수조건, 일정·원가 초안을 가져옵니다. 아직 발생하지 않은 위험과 이미 발생한 이슈를 구분하세요.','D18 품질과 D25/D26 위험을 연결합니다. 대응에 필요한 비용·자원·기간을 앞의 계획에 반영합니다.'],
 ['외주 범위·선정 이유·협업 책임을 근거로 정합니다.','작업 범위와 품질 조건을 가져옵니다. 업체 선정 권고와 계약 체결은 다른 상태입니다.','조달·소통·참여 계획을 작성합니다. 계약 조건이 일정·현금계획과 맞는지 확인하고 7단원으로 넘깁니다.'],
 ['여러 계획을 하나로 맞추고 승인 이후의 작업과 증거를 관리합니다.','2~6단원의 분야 계획 초안을 가져옵니다. 먼저 모순을 수정하고 승인 자료를 엽니다.','통합 계획 → 승인·킥오프 → 실행 중 기록 순서입니다. 성과보고와 검사 기록은 여기서 시작해 후속 단원에서 갱신합니다.'],
 ['현재 성과를 설명하고 변경이 필요한 이유와 영향을 상정합니다.','기준선과 실행 기록을 함께 가져옵니다. 같은 기준일의 실적을 비교하고 승인 전 대안을 먼저 보존하세요.','D05 성과보고와 D06 변경 기록을 만듭니다. 승인 후 영향받는 문서를 함께 갱신하고 이전 기준선은 보존합니다.'],
 ['검수·인수·계약·운영 책임을 확인하고 종료 가능 여부를 설명합니다.','요구 추적, 품질 계획, 변경 이력을 가져옵니다. 시험 통과와 현업 인수, 스폰서의 종료 결정은 구분합니다.','D20 검사 → D12 인수 → D29 계약 대조 → D07 종료 순서입니다. 보증과 편익 측정 책임은 종료 후 담당자에게 넘깁니다.']
];
let selected=Number(new URLSearchParams(location.search).get('unit')||0),lesson,position={},requestId=0;
if(!Number.isInteger(selected)||selected<0||selected>9)selected=0;
try{position=JSON.parse(localStorage.getItem('moapay.pm.reader.positions')||'{}');if(!position||Array.isArray(position)||typeof position!=='object')position={};$('#legacy').hidden=!localStorage.getItem('moapay.pm.learning.v2')}catch(e){position={}}
$('#unit').innerHTML=titles.map((t,i)=>`<option value="${i}">${i}. ${esc(t)}</option>`).join('');$('#unit').value=String(selected);
const api=PMApp.api;
function savePosition(){try{localStorage.setItem('moapay.pm.reader.positions',JSON.stringify(position))}catch(e){$('#notice').textContent='읽던 위치를 저장하지 못했습니다. 설명과 조회는 계속 이용할 수 있습니다.'}}
function go(index){position[selected]=Math.max(0,Math.min(index,lesson.guideSteps.length-1));savePosition();render();$('#step-title').focus();$('#step-title').scrollIntoView({block:'start'})}
function render(){
 const all=lesson.guideSteps,index=Number.isInteger(position[selected])?Math.max(0,Math.min(all.length-1,position[selected])):0,s=all[index];
 const brief=briefs[selected];
 const lab={0:'workflow',1:'charter',3:'schedule',8:'change'}[selected];
 const visualLink=PMApp.isStatic&&lab?`<p><a class="downloadlink" href="visual.html?lab=${lab}" target="_blank" rel="noopener">이 단원을 시각화 워크북으로 실습하기 ↗</a></p>`:'';
 $('#unit-intro').innerHTML=`<strong>${selected}단원에서 배우는 일</strong><p>${esc(brief[0])}</p>${visualLink}<details><summary>시작할 때와 끝낼 때 확인할 것</summary><p>${esc(brief[1])}</p><p>${esc(brief[2])}</p><p class="hint">예제를 읽은 뒤 직접 해석하고, 근거·판단·시점을 검토합니다. 웹에 답을 적거나 완료 표시를 할 필요는 없습니다. 목차에서 원하는 단계로 이동하세요.</p></details>`;
 $('#lesson').innerHTML=`<div class="layout"><aside class="card outline"><h2>${selected}. ${esc(lesson.title)}</h2><p class="hint">설명을 읽고 필요한 자료를 확인하세요. 어느 단계든 다시 볼 수 있습니다.</p><nav aria-label="단원 학습 단계">${all.map((x,i)=>`<button data-step="${i}" aria-current="${i===index?'step':'false'}">${i+1}. ${esc(x.title)}${x.locked?' · '+esc(x.stage)+' 자료 필요':''}</button>`).join('')}</nav></aside><article class="card"><span class="pill">${index+1} / ${all.length}단계 · ${esc(s.stage)}</span><h2 id="step-title" tabindex="-1">${esc(s.title)}</h2><p class="meta">${s.processes.length?'관련 프로세스 '+esc(s.processes.join(', ')):'회사와 자료 이해'} · 현재 조회 자료 ${esc(lesson.currentStage)}</p>${s.locked?`<p>이 단계의 예제와 원천자료는 ${esc(s.stage)}(${esc(stages[s.stage])})에서 확인합니다. 앞 단계의 문서 검토를 마친 뒤 상단의 자료 선택에서 해당 팩을 여세요. 목차와 다음 단계는 자유롭게 살펴볼 수 있습니다.</p>`:`<div class="bar">${s.sources.map(id=>`<button class="source-button" data-source="${esc(id)}">${esc(id)} ${esc(lesson.sourceTitles?.[id]||'원천 문서')} 읽기</button>`).join('')}</div>${(s.links||[]).length?'<div>'+s.links.map(([label,url])=>`<a class="downloadlink" href="${esc(PMApp.href(url))}" target="_blank" rel="noopener">${esc(label)} ↗</a>`).join('')+'</div>':''}<section id="source-panel" hidden></section><div id="step-body">${s.html}</div><details id="templates"><summary>이 단계의 작성 양식</summary><p>실제 문서는 내려받은 양식에서 작성합니다. 같은 문서가 있으면 새 파일을 만들기보다 해당 버전을 이어서 보완하세요.</p>${s.downloads.map(n=>`<a class="downloadlink" download href="${esc(PMApp.href('/download?name='+encodeURIComponent(n)))}">${esc(n)} 내려받기</a>`).join('')}</details>`}<nav class="paging" aria-label="이전 다음 단계">${index?`<button data-step="${index-1}">← 이전 단계</button>`:'<span></span>'}${index<all.length-1?`<button class="primary" data-step="${index+1}">다음 단계 →</button>`:selected<9?`<a class="downloadlink" href="${esc(PMApp.href('/learn?unit='+(selected+1)))}">다음 단원: ${esc(titles[selected+1])} →</a>`:'<p>전체 과정의 문서와 남은 책임을 확인했습니다. 실제 수행 기록과 강사 검토로 학습 결과를 확인하세요.</p>'}</nav></article></div>`;
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(Number(b.dataset.step)));
 document.querySelectorAll('[data-source]').forEach(b=>b.onclick=async()=>{const stage=lesson.currentStage,step=s.id;try{const d=await api('/api/detail?menu=documents&id='+encodeURIComponent(b.dataset.source));if(!d.document)throw Error('현재 자료에 없습니다. 자료 단계와 검색조건을 확인하세요.');if(lesson.currentStage!==stage||lesson.guideSteps[position[selected]||0].id!==step)return;const panel=$('#source-panel');panel.hidden=false;panel.innerHTML=`<button id="close-source">원천 문서 닫기</button><h3>${esc(d.document.doc_id+' '+d.document.title)}</h3><p class="meta">${esc(d.document.effective_date)} · ${esc(d.document.version)}</p><p>${esc(d.document.body)}</p>`;$('#close-source').onclick=()=>panel.hidden=true;panel.scrollIntoView({block:'start'})}catch(e){$('#notice').textContent=e.message}});
}
async function open(){const id=++requestId;selected=Number($('#unit').value);$('#notice').textContent='';$('#lesson').textContent='설명을 읽고 있습니다…';try{const d=await api('/api/lesson?unit='+selected);if(id!==requestId)return;lesson=d;$('#stage-caption').textContent='현재 자료: '+d.currentStage+' · '+stages[d.currentStage];$('#stage').innerHTML=d.availableStages.map(s=>`<option value="${s}">${s} · ${esc(stages[s])}</option>`).join('');$('#stage').value=d.currentStage;render();history.replaceState(null,'',PMApp.href('/learn?unit='+selected))}catch(e){if(id===requestId){$('#lesson').textContent='';$('#notice').textContent=e.message}}}
$('#open').onclick=open;
$('#change-stage').onclick=async()=>{const b=$('#change-stage');b.disabled=true;try{const d=await api('/api/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage:$('#stage').value})});await open();$('#notice').textContent=d.message}catch(e){$('#notice').textContent=e.message}finally{b.disabled=false}};
$('#legacy-export').onclick=()=>{const raw=localStorage.getItem('moapay.pm.learning.v2');if(!raw)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json;charset=utf-8'}));a.download='이전_PM_학습기록.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
if(PMApp.isStatic){document.querySelector('#stage-help').textContent='공개 웹 교재에서는 자료팩 설치 없이 시점을 선택합니다. 선택은 이 브라우저에만 저장됩니다. 앞 단계의 검토를 마친 뒤 다음 자료를 여세요.';}
open();
