'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles=['회사에 합류하기','프로젝트 착수','요구사항과 범위','일정과 자원','원가와 예산','품질과 리스크','조달과 협업','계획 통합과 실행','성과와 변경 통제','검수·이관·종료'];
const stages={S0:'착수 전',S0A:'헌장 승인',S1:'분야 계획',S1A:'통합 승인·킥오프',S2:'실행·변경 분석',S3:'변경 승인',S4:'검수·종료'};
const params=new URLSearchParams(location.search);
let selected=Number(params.get('unit')||0),lesson,position={},requestId=0,view=params.get('view')==='practice'?'practice':'chapter',phase=['concept','evidence','practice'].includes(params.get('phase'))?params.get('phase'):'concept',entryStep=params.get('step');
if(!Number.isInteger(selected)||selected<0||selected>9)selected=0;
try{position=JSON.parse(localStorage.getItem('moapay.pm.reader.positions')||'{}');if(!position||Array.isArray(position)||typeof position!=='object')position={};$('#legacy').hidden=!localStorage.getItem('moapay.pm.learning.v2')}catch(e){position={}}
$('#unit').innerHTML=titles.map((t,i)=>`<option value="${i}">${i}. ${esc(t)}</option>`).join('');$('#unit').value=String(selected);
const api=PMApp.api;
function savePosition(){try{localStorage.setItem('moapay.pm.reader.positions',JSON.stringify(position))}catch(e){$('#notice').textContent='읽던 위치를 저장하지 못했습니다. 설명과 조회는 계속 이용할 수 있습니다.'}}
function closeVisual(){const d=$('#study-simulation');if(d){d.open=false;$('#study-frame-slot')?.replaceChildren();}}
function syncLocation(){const step=lesson?.guideSteps[position[selected]||0];history.replaceState(null,'',PMApp.href('/learn?unit='+selected+'&view='+view+(view==='practice'&&step?'&step='+encodeURIComponent(step.id)+'&phase='+phase:'')));}
function setView(next,focus=false){
 view=next;$('#chapter-view').hidden=view!=='chapter';$('#practice-view').hidden=view!=='practice';
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));
 if(view!=='practice')closeVisual();
 syncLocation();
 if(focus){const el=$(view==='chapter'?'#chapter-title':'#step-title');el.focus();el.scrollIntoView({block:'start'});}
}
function setPhase(next,focus=false){
 phase=next;
 document.querySelectorAll('.step-phase-panel').forEach(p=>p.hidden=p.dataset.phasePanel!==phase);
 document.querySelectorAll('[data-phase]').forEach(b=>{const active=b.dataset.phase===phase;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});
 if(phase!=='evidence')closeVisual();
 syncLocation();
 if(focus)$(`[data-phase="${phase}"]`).focus();
}
function go(index){position[selected]=Math.max(0,Math.min(index,lesson.guideSteps.length-1));savePosition();phase='concept';view='practice';render();$('#step-title').focus();$('#step-title').scrollIntoView({block:'start'});}
// Release controls describe company information availability, not a learner's score.
function releaseNotice(stage){return `<div class="release-notice"><p><strong>${esc(stage)} · ${esc(stages[stage])}에서 공개되는 자료입니다.</strong></p><p>현재 ${esc(lesson.currentStage)} 자료에는 이 업무의 근거가 아직 없습니다. 이전 문서의 검토·수정을 마친 뒤 자료 시점을 선택하세요. 읽기나 작성 여부로 잠근 화면이 아니며, 자료를 여는 것이 자신의 문서를 승인하는 일도 아닙니다.</p><button data-release="${esc(stage)}">자료 선택 위치로 이동</button></div>`;}
function render(){
 const all=lesson.guideSteps,index=Number.isInteger(position[selected])?Math.max(0,Math.min(all.length-1,position[selected])):0,s=all[index],guide=lesson.unitGuide;
 $('#unit-intro').innerHTML=`<div class="unit-direction"><span class="eyebrow">LEVEL 1 · UNIT ${String(selected).padStart(2,'0')}</span><nav aria-label="이전 다음 단원"><button id="unit-prev" ${selected===0?'disabled':''}>← 이전 단원</button><button id="unit-next" ${selected===9?'disabled':''}>다음 단원 →</button></nav></div><h2>${selected}. ${esc(lesson.title)}</h2><p>${esc(guide?.mission||'설명을 읽고 원천자료에서 근거를 확인합니다.')}</p><div id="reader-view" class="reader-view" role="group" aria-label="교재 읽기 방식"><button data-view="chapter">단원 본문 읽기</button><button data-view="practice">단계별 실습하기</button></div><p class="hint">처음에는 본문을 읽고, 이어서 단계별 실습을 진행하세요. 필요한 그림은 실습 중 선택해서 엽니다. 진도 입력이나 완료 표시는 필요하지 않습니다.</p>`;
 const chapters=guide?.sections||[];
 const chapter=`<section id="chapter-view" class="card chapter-reader"><h2 id="chapter-title" tabindex="-1">이 단원의 업무를 차례로 이해하기</h2><p>${esc(guide?.mission||'')}</p><div class="chapter-brief"><div><h3>가져올 것</h3><ul>${(guide?.prerequisites||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div><div><h3>마치면 할 수 있는 일</h3><ul>${(guide?.outcomes||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div></div><nav class="chapter-toc" aria-label="단원 본문 차례">${chapters.map((c,i)=>`<a href="#chapter-${esc(c.id)}">${i+1}. ${esc(c.title)}${c.locked?' · 자료 미공개':''}</a>`).join('')}</nav>${chapters.map((c,i)=>`<section class="chapter-section ${c.locked?'chapter-lock':''}" data-section="${esc(c.id)}" id="chapter-${esc(c.id)}"><span class="meta">${i+1} / ${chapters.length} · ${esc(c.stage)}</span><h3>${esc(c.title)}</h3>${c.locked?releaseNotice(c.stage):c.html}</section>`).join('')}<div class="chapter-handoff"><h3>읽은 내용을 문서로 옮기기</h3><p>${esc(guide?.handoff||'현재 자료에서 단계별 실습을 시작하세요.')}</p><button id="chapter-to-practice" class="primary">이 단원의 단계별 실습 시작하기 →</button><p class="hint">실습에서는 필요한 원천 문서를 열고, 양식의 항목을 작성한 뒤 검토 의견으로 수정합니다. 본문은 언제든 다시 읽을 수 있습니다.</p></div></section>`;
 const blocks=s.readingBlocks||{concept:s.html,evidence:'',practice:''};
 const body=s.locked?releaseNotice(s.stage):`<div class="phase-tabs" role="tablist" aria-label="한 업무의 수행 순서">${[['concept','1. 개념 읽기'],['evidence','2. 근거·예제'],['practice','3. 작성·검토']].map(([id,label])=>`<button id="phase-tab-${id}" role="tab" data-phase="${id}" aria-controls="phase-${id}" aria-selected="false">${label}</button>`).join('')}</div><div id="step-body"><section id="phase-concept" class="step-phase-panel" data-phase-panel="concept" role="tabpanel" aria-labelledby="phase-tab-concept"><div>${blocks.concept}</div><button data-continue="evidence" class="primary">근거와 예제 확인하기 →</button></section><section id="phase-evidence" class="step-phase-panel" data-phase-panel="evidence" role="tabpanel" aria-labelledby="phase-tab-evidence"><p class="hint">원천 버튼으로 자료를 읽고 아래 예제와 대조합니다. SQL은 선택 경로입니다.</p><div class="bar">${s.sources.map(id=>`<button class="source-button" data-source="${esc(id)}">${esc(id)} ${esc(lesson.sourceTitles?.[id]||'원천 문서')} 읽기</button>`).join('')}</div>${(s.links||[]).map(([label,url])=>`<a class="downloadlink" href="${esc(PMApp.href(url))}" target="_blank" rel="noopener">${esc(label)} ↗</a>`).join('')}<section id="source-panel" hidden></section><div id="evidence-reading">${blocks.evidence}</div><div id="visual-slot"></div><button data-continue="practice" class="primary">문서 작성과 검토로 이어가기 →</button></section><section id="phase-practice" class="step-phase-panel" data-phase-panel="practice" role="tabpanel" aria-labelledby="phase-tab-practice"><div id="practice-reading">${blocks.practice}</div><div id="quiz-slot"></div><details id="templates"><summary>파일로 작성할 양식 내려받기</summary><p>웹 작성과 파일 편집 중 편한 방법 하나를 사용하세요. 같은 문서는 버전을 이어서 보완합니다.</p>${s.downloads.map(n=>`<a class="downloadlink" download href="${esc(PMApp.href('/download?name='+encodeURIComponent(n)))}">${esc(n)} 내려받기</a>`).join('')}</details></section></div>`;
 const next=index<all.length-1?`<button class="primary" data-step="${index+1}">다음 단계 →</button>`:selected<9?`<button class="primary" data-next-unit>다음 단원: ${esc(titles[selected+1])} →</button>`:'<p>헌장부터 종료까지의 근거·문서 연결을 설명하고 실제 수행 기록으로 검토받으세요.</p>';
 $('#lesson').innerHTML=chapter+`<section id="practice-view"><div class="layout"><aside class="card outline"><h2>${selected}. ${esc(lesson.title)}</h2><p class="hint">각 단계에서 개념 → 근거·예제 → 작성·검토 순서로 진행합니다.</p><nav aria-label="단원 학습 단계">${all.map((x,i)=>`<button data-step="${i}" aria-current="${i===index?'step':'false'}">${i+1}. ${esc(x.title)}${x.locked?' · '+esc(x.stage)+' 자료 필요':''}</button>`).join('')}</nav></aside><article class="card"><span class="pill">${index+1} / ${all.length}단계 · ${esc(s.stage)}</span><h2 id="step-title" tabindex="-1">${esc(s.title)}</h2><p class="meta">${s.processes.length?'관련 프로세스 '+esc(s.processes.join(', ')):'회사와 자료 이해'} · 현재 조회 자료 ${esc(lesson.currentStage)}</p>${body}<nav class="paging" aria-label="이전 다음 단계">${index?`<button data-step="${index-1}">← 이전 단계</button>`:'<span></span>'}${next}</nav></article></div></section>`;
 window.PMStudy?.mount({lesson,step:s,unit:selected});setView(view);if(!s.locked)setPhase(phase);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view,true));
 document.querySelectorAll('[data-phase]').forEach(b=>{b.onclick=()=>setPhase(b.dataset.phase);b.onkeydown=e=>{const ids=['concept','evidence','practice'],i=ids.indexOf(b.dataset.phase);let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();setPhase(ids[next],true);}};});
 document.querySelectorAll('[data-continue]').forEach(b=>b.onclick=()=>{setPhase(b.dataset.continue,true);$('.phase-tabs').scrollIntoView({block:'start'});});
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(Number(b.dataset.step)));
 document.querySelectorAll('[data-release]').forEach(b=>b.onclick=()=>{const panel=$('#stage-caption').parentElement;panel.open=true;$('#stage').value=b.dataset.release;$('#stage').focus();panel.scrollIntoView({block:'start'});});
 $('#chapter-to-practice').onclick=()=>go(0);$('#unit-prev').onclick=()=>open(selected-1);$('#unit-next').onclick=()=>open(selected+1);document.querySelector('[data-next-unit]')?.addEventListener('click',()=>open(selected+1));
 document.querySelectorAll('[data-source]').forEach(b=>b.onclick=async()=>{const stage=lesson.currentStage,step=s.id,unit=selected;try{const d=await api('/api/detail?menu=documents&id='+encodeURIComponent(b.dataset.source));if(!d.document)throw Error('현재 자료에 없습니다. 자료 단계와 검색조건을 확인하세요.');if(selected!==unit||lesson.currentStage!==stage||lesson.guideSteps[position[selected]||0].id!==step)return;const panel=$('#source-panel');panel.hidden=false;panel.innerHTML=`<button id="close-source">원천 문서 닫기</button><h3>${esc(d.document.doc_id+' '+d.document.title)}</h3><p class="meta">${esc(d.document.effective_date)} · ${esc(d.document.version)}</p><p>${esc(d.document.body)}</p>`;$('#close-source').onclick=()=>panel.hidden=true;panel.scrollIntoView({block:'start'})}catch(e){$('#notice').textContent=e.message}});
}
async function open(next){const id=++requestId;const target=Number.isInteger(next)?next:Number($('#unit').value);if(target<0||target>9)return;if(selected!==target){view='chapter';phase='concept';}selected=target;$('#unit').value=String(selected);$('#notice').textContent='';$('#lesson').textContent='설명을 읽고 있습니다…';try{const d=await api('/api/lesson?unit='+selected);if(id!==requestId)return;lesson=d;let jump=false;if(entryStep){const i=d.guideSteps.findIndex(s=>s.id===entryStep);if(i>=0){position[selected]=i;view='practice';jump=true;}entryStep=null;}$('#stage-caption').textContent='현재 자료: '+d.currentStage+' · '+stages[d.currentStage];$('#stage').innerHTML=d.availableStages.map(s=>`<option value="${s}">${s} · ${esc(stages[s])}</option>`).join('');$('#stage').value=d.currentStage;render();if(jump){$('#step-title').focus();$('#step-title').scrollIntoView({block:'start'});}}catch(e){if(id===requestId){$('#lesson').textContent='';$('#notice').textContent=e.message}}}
$('#open').onclick=()=>open();
$('#change-stage').onclick=async()=>{const b=$('#change-stage');b.disabled=true;try{const d=await api('/api/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage:$('#stage').value})});await open();$('#notice').textContent=d.message}catch(e){$('#notice').textContent=e.message}finally{b.disabled=false}};
$('#legacy-export').onclick=()=>{const raw=localStorage.getItem('moapay.pm.learning.v2');if(!raw)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json;charset=utf-8'}));a.download='이전_PM_학습기록.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
if(PMApp.isStatic)$('#stage-help').textContent='자료 선택은 이 브라우저에만 저장됩니다. 앞 단계의 검토를 마친 뒤 다음 시점을 여세요. 시점을 선택해도 학습자 문서가 승인되지는 않습니다.';
open();
