PRAGMA foreign_keys=ON;
CREATE TABLE meta(stage TEXT PRIMARY KEY, as_of TEXT, label TEXT);
CREATE TABLE company(bukrs TEXT PRIMARY KEY, name TEXT, currency TEXT);
CREATE TABLE cost_center(kostl TEXT PRIMARY KEY, bukrs TEXT REFERENCES company, name TEXT);
CREATE TABLE person(person_id TEXT PRIMARY KEY, name TEXT, role TEXT, department TEXT, authority TEXT, interest TEXT);
CREATE TABLE business_partner(partner_id TEXT PRIMARY KEY, name TEXT, category TEXT);
CREATE TABLE project(pspid TEXT PRIMARY KEY, bukrs TEXT REFERENCES company, name TEXT, pm_id TEXT REFERENCES person);
CREATE TABLE wbs(posid TEXT PRIMARY KEY, pspid TEXT REFERENCES project, name TEXT, owner_id TEXT REFERENCES person);
CREATE TABLE source_document(doc_id TEXT PRIMARY KEY,title TEXT,release_stage TEXT,author_id TEXT REFERENCES person,reviewer_id TEXT REFERENCES person,approver_id TEXT REFERENCES person,version TEXT,effective_date TEXT,body TEXT);
CREATE TABLE document_link(doc_id TEXT REFERENCES source_document, object_type TEXT, object_id TEXT, PRIMARY KEY(doc_id,object_type,object_id));
CREATE TABLE requirement(req_id TEXT PRIMARY KEY, title TEXT, owner_id TEXT REFERENCES person, acceptance TEXT, source_id TEXT REFERENCES source_document);
CREATE TABLE requirement_wbs(req_id TEXT REFERENCES requirement,posid TEXT REFERENCES wbs,PRIMARY KEY(req_id,posid));
CREATE TABLE approval(approval_id TEXT PRIMARY KEY,kind TEXT,approved_by TEXT REFERENCES person,approved_date TEXT,source_id TEXT REFERENCES source_document);
CREATE TABLE baseline(version TEXT PRIMARY KEY, pspid TEXT REFERENCES project, bac INTEGER, management_reserve INTEGER,end_date TEXT, approval_id TEXT REFERENCES approval,status TEXT);
CREATE TABLE budget_line(version TEXT REFERENCES baseline,period TEXT,amount INTEGER,PRIMARY KEY(version,period));
CREATE TABLE allocation(person_group TEXT, posid TEXT REFERENCES wbs,headcount INTEGER,person_days INTEGER,rate INTEGER,PRIMARY KEY(person_group,posid));
CREATE TABLE account(saknr TEXT PRIMARY KEY,name TEXT,statement TEXT);
CREATE TABLE bkpf(bukrs TEXT REFERENCES company,belnr TEXT,gjahr INTEGER,budat TEXT,description TEXT,source_id TEXT REFERENCES source_document,PRIMARY KEY(bukrs,belnr,gjahr));
CREATE TABLE acdoca(bukrs TEXT,belnr TEXT,gjahr INTEGER,docln INTEGER,rldnr TEXT DEFAULT '0L',saknr TEXT REFERENCES account,hsl INTEGER,pspid TEXT REFERENCES project,posid TEXT REFERENCES wbs,partner_id TEXT REFERENCES business_partner,PRIMARY KEY(bukrs,belnr,gjahr,docln,rldnr),FOREIGN KEY(bukrs,belnr,gjahr) REFERENCES bkpf);
CREATE TABLE contract(contract_id TEXT PRIMARY KEY,partner_id TEXT REFERENCES business_partner,pspid TEXT REFERENCES project,amount INTEGER,scope TEXT,source_id TEXT REFERENCES source_document);
CREATE TABLE purchase_request(request_id TEXT PRIMARY KEY,posid TEXT REFERENCES wbs,amount INTEGER,status TEXT,source_id TEXT REFERENCES source_document);
CREATE TABLE purchase_order(ebeln TEXT PRIMARY KEY,request_id TEXT REFERENCES purchase_request,contract_id TEXT REFERENCES contract,amount INTEGER,status TEXT);
CREATE TABLE service_acceptance(acceptance_id TEXT PRIMARY KEY,ebeln TEXT REFERENCES purchase_order,accepted_date TEXT,amount INTEGER,kind TEXT,source_id TEXT REFERENCES source_document);
CREATE TABLE invoice(invoice_id TEXT PRIMARY KEY,acceptance_id TEXT REFERENCES service_acceptance,amount INTEGER,belnr TEXT,gjahr INTEGER,bukrs TEXT,FOREIGN KEY(bukrs,belnr,gjahr) REFERENCES bkpf);
CREATE TABLE payment(payment_id TEXT PRIMARY KEY,invoice_id TEXT REFERENCES invoice,amount INTEGER,paid_date TEXT,belnr TEXT,gjahr INTEGER,bukrs TEXT,FOREIGN KEY(bukrs,belnr,gjahr) REFERENCES bkpf);
CREATE TABLE performance(posid TEXT REFERENCES wbs,status_date TEXT,pv INTEGER,ev INTEGER,ac INTEGER,source_id TEXT REFERENCES source_document,PRIMARY KEY(posid,status_date));
CREATE TABLE test_result(test_id TEXT PRIMARY KEY,req_id TEXT REFERENCES requirement,tested INTEGER,passed INTEGER,critical_open INTEGER,source_id TEXT REFERENCES source_document);
CREATE TABLE merchant(merchant_id TEXT PRIMARY KEY,partner_id TEXT REFERENCES business_partner,name TEXT,fee_bps INTEGER);
CREATE TABLE settlement_batch(batch_id TEXT PRIMARY KEY,merchant_id TEXT REFERENCES merchant,settlement_date TEXT,adjustment INTEGER,status TEXT);
CREATE TABLE payment_transaction(tx_id TEXT PRIMARY KEY,batch_id TEXT REFERENCES settlement_batch,trade_date TEXT,gross INTEGER,cancel INTEGER,fee INTEGER,expected_net INTEGER,received_net INTEGER);
CREATE TABLE exception_case(exception_id TEXT PRIMARY KEY,tx_id TEXT REFERENCES payment_transaction,owner_id TEXT REFERENCES person,due_date TEXT,status TEXT,reason TEXT);
CREATE VIEW v_전표조회 AS SELECT b.budat AS 전기일,a.belnr AS 전표번호,a.docln AS 항목,a.saknr AS 계정번호,c.name AS 계정명,a.hsl AS 차변양수_대변음수,a.pspid AS 프로젝트,a.posid AS WBS,a.partner_id AS 거래처,b.source_id AS 근거문서 FROM acdoca a JOIN bkpf b USING(bukrs,belnr,gjahr) JOIN account c USING(saknr);
CREATE VIEW v_프로젝트원가 AS SELECT a.pspid AS 프로젝트,a.posid AS WBS,w.name AS 작업패키지,sum(a.hsl) AS 누적비용 FROM acdoca a JOIN wbs w USING(posid) WHERE a.saknr='610000' GROUP BY a.pspid,a.posid;
CREATE VIEW v_정산조회 AS SELECT b.batch_id AS 정산번호,m.name AS 가맹점,b.settlement_date AS 정산일,sum(t.gross) AS 거래금액,sum(t.cancel) AS 취소금액,sum(t.fee) AS 수수료,b.adjustment AS 조정금액,sum(t.expected_net)+b.adjustment AS 지급예정액,b.status AS 상태 FROM settlement_batch b JOIN merchant m USING(merchant_id) JOIN payment_transaction t USING(batch_id) GROUP BY b.batch_id;
CREATE VIEW v_대사조회 AS SELECT t.tx_id AS 거래번호,t.batch_id AS 정산번호,t.expected_net AS 계산액,t.received_net AS 수신액,t.received_net-t.expected_net AS 차이,CASE WHEN t.expected_net=t.received_net THEN '일치' ELSE '불일치' END AS 판정,e.owner_id AS 담당자,e.status AS 처리상태 FROM payment_transaction t LEFT JOIN exception_case e USING(tx_id);
CREATE VIEW v_조달조회 AS SELECT p.ebeln AS 발주번호,c.contract_id AS 계약번호,b.name AS 공급사,p.amount AS 발주액,coalesce((SELECT sum(s.amount) FROM service_acceptance s WHERE s.ebeln=p.ebeln),0) AS 누적검수액,coalesce((SELECT sum(i.amount) FROM invoice i JOIN service_acceptance s USING(acceptance_id) WHERE s.ebeln=p.ebeln),0) AS 누적청구액,coalesce((SELECT sum(y.amount) FROM payment y JOIN invoice i USING(invoice_id) JOIN service_acceptance s USING(acceptance_id) WHERE s.ebeln=p.ebeln),0) AS 누적지급액 FROM purchase_order p JOIN contract c USING(contract_id) JOIN business_partner b USING(partner_id);
CREATE VIEW v_요구추적 AS SELECT r.req_id AS 요구번호,r.title AS 요구사항,l.posid AS WBS,r.acceptance AS 인수기준,r.source_id AS 원천문서 FROM requirement r LEFT JOIN requirement_wbs l USING(req_id);
CREATE VIEW v_예산조회 AS SELECT b.version AS 버전,b.status AS 상태,b.bac AS 원가기준선,b.management_reserve AS 관리예비비,b.bac+b.management_reserve AS 총자금,b.end_date AS 종료일,b.approval_id AS 승인번호 FROM baseline b;
-- Educational provenance of the fee sample within the aggregated revenue journal.
CREATE TABLE settlement_revenue_bridge(batch_id TEXT PRIMARY KEY REFERENCES settlement_batch,bukrs TEXT,belnr TEXT,gjahr INTEGER,sample_fee INTEGER,FOREIGN KEY(bukrs,belnr,gjahr) REFERENCES bkpf);
CREATE TABLE physical_resource(resource_id TEXT PRIMARY KEY,name TEXT,planned_qty INTEGER,allocated_qty INTEGER,status TEXT,owner_id TEXT REFERENCES person,source_id TEXT REFERENCES source_document);
