/* All simulations are local, reversible readings of the current ERP snapshot. */
export const EXTRA_MODULES = {
 scope:{unit:2,title:'요구에서 WBS·시험까지 끊김 없이 연결하기',stage:'S1'},
 cost:{unit:4,title:'같은 프로젝트의 비용 곡선과 지급 곡선',stage:'S1'},
 risk:{unit:5,title:'위험 확률이 예비비 판단으로 이어지는 과정',stage:'S1'},
 procurement:{unit:6,title:'외주 평가에서 검수·지급까지 책임 연결하기',stage:'S1'},
 integration:{unit:7,title:'회의 결정을 증거가 있는 실행 보드로',stage:'S2'},
 closure:{unit:9,title:'시험·인수·종료와 남아 있는 책임 구분하기',stage:'S4'}
};
const colors={blue:'#355d9e',navy:'#1d3152',ochre:'#8c5a24',muted:'#626d7f',soft:'#ebf0f8',line:'#aab7ca',paper:'#fffefb',red:'#a92335'};
const million=1000000;
const percent=n=>(n*100).toLocaleString('ko-KR',{maximumFractionDigits:1})+'%';
function requireValue(value,message){if(value==null||!Number.isFinite(Number(value)))throw Error(message);return Number(value);}
export function riskOutcomes(p1,p2,c1,c2,reserve){
 if(![p1,p2].every(v=>Number.isFinite(v)&&v>=0&&v<=1)||![c1,c2,reserve].every(v=>Number.isFinite(v)&&v>=0))throw Error('확률과 금액 범위를 확인하세요.');
 const rows=[{name:'둘 다 미발생',p:(1-p1)*(1-p2),loss:0},{name:'K01만 발생',p:p1*(1-p2),loss:c1},{name:'K02만 발생',p:(1-p1)*p2,loss:c2},{name:'동시 발생',p:p1*p2,loss:c1+c2}];
 return {rows,emv:rows.reduce((s,r)=>s+r.p*r.loss,0),covered:rows.filter(r=>r.loss<=reserve).reduce((s,r)=>s+r.p,0),excess:rows.reduce((s,r)=>s+r.p*Math.max(0,r.loss-reserve),0)};
}
export function readRiskFacts(body){
 const find=id=>{const m=body.match(new RegExp(id+' ([^\\n.]+?) 확률(0\\.\\d+) 비용영향(\\d+)백만원 일정(\\d+)일, 책임([^ .\\n]+)'));if(!m)throw Error('S07의 위험 확률·영향·책임 자료를 확인해 주세요.');return {id,name:m[1],p:Number(m[2]),cost:Number(m[3])*million,days:Number(m[4]),owner:m[5],rank:id==='K01'?2:3};};
 if(!body.includes('독립 발생'))throw Error('S07의 독립 발생 가정을 확인해 주세요.');
 return [find('K01'),find('K02')];
}
export function readCostFacts(s06,s19){
 const m=s06.match(/10월(\d+)백만원, 11월(\d+)백만원, 12월(\d+)백만원, 1월(\d+)백만원/);
 if(!m)throw Error('S06 월별 비용 후보를 확인해 주세요.');
 const costs=m.slice(1).map(Number),reserve=requireValue(s06.match(/우발예비비(\d+)백만원/)?.[1],'우발예비비가 없습니다.'),management=requireValue(s06.match(/관리예비비(\d+)백만원/)?.[1],'관리예비비가 없습니다.');
 const partial=requireValue(s19.match(/부분검수 (\d+)백만원/)?.[1],'외주 부분검수 계획이 없습니다.'),paid=requireValue(s19.match(/중 (\d+)백만원을 11월 지급/)?.[1],'외주 지급 계획이 없습니다.'),last=requireValue(s19.match(/최종(\d+)백만원/)?.[1],'외주 최종 지급 계획이 없습니다.');
 const cash=[costs[0],costs[1]-partial+paid,costs[2]-last-reserve,costs[3]+partial-paid+last];
 if(cash.some(x=>x<0))throw Error('월별 지급 조건을 다시 확인하세요.');
 return {months:['2026-10','2026-11','2026-12','2027-01'],costs:costs.map(x=>x*million),cash:cash.map(x=>x*million),reserve:reserve*million,management:management*million,deferred:(partial-paid+last)*million};
}
export function proposalScores(proposals,weights){
 if(weights.length!==3||weights.some(w=>w<0)||Math.abs(weights.reduce((a,b)=>a+b,0)-1)>1e-8)throw Error('평가 가중치의 합은 100%입니다.');
 return proposals.map(p=>({...p,total:p.scores.reduce((s,x,i)=>s+x*weights[i],0)}));
}
function table(h,heads,rows){return '<div class="reading-table"><table><thead><tr>'+heads.map(s=>'<th scope="col">'+h.esc(s)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map((v,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${h.esc(v)}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</tbody></table></div>';}
function section(title,text){return `<section class="card extra-teaching"><h3>${title}</h3>${text}</section>`;}
function figure(id,label){return `<div class="wb-figure extra-figure"><svg id="${id}" role="img" aria-label="${label}"></svg></div>`;}
function duration(){return window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:420;}
function tween(selection,attrs){selection.interrupt();const target=duration()?selection.transition().duration(duration()):selection;for(const [k,v]of Object.entries(attrs))target.attr(k,v);return target;}
function svgBase(id,width,height,label){const s=window.d3.select('#'+id).attr('viewBox',`0 0 ${width} ${height}`).attr('xmlns','http://www.w3.org/2000/svg');s.selectAll('title').data([label]).join('title').text(d=>d);return s;}
function cleanup(){window.d3.select('#wb-content').selectAll('*').interrupt();}
function buttonStates(attr,current){document.querySelectorAll(`[${attr}]`).forEach(b=>b.setAttribute('aria-pressed',b.getAttribute(attr)===String(current)));}
function stepsControls(id,labels){return `<div class="extra-player" role="group" aria-label="근거를 단계별로 재생"><button id="${id}-play">순서대로 보기</button><button id="${id}-next">다음 단계</button><button id="${id}-reset">처음으로</button><span id="${id}-status" aria-live="polite"></span></div><div class="wb-selectors">${labels.map((l,i)=>`<button data-${id}-step="${i}">${i+1}. ${l}</button>`).join('')}</div>`;}
function player(h,id,labels,draw){
 let index=0,timer=null;const stop=()=>{clearInterval(timer);timer=null;h.$('#'+id+'-play').textContent='순서대로 보기';};
 const show=i=>{index=i;draw(i);buttonStates('data-'+id+'-step',i);h.$('#'+id+'-status').textContent=`${i+1}/${labels.length} · ${labels[i]}`;h.$('#'+id+'-next').disabled=i===labels.length-1;};
 h.$('#'+id+'-play').onclick=()=>{if(timer){stop();return;}if(index===labels.length-1)show(0);h.$('#'+id+'-play').textContent='일시 정지';timer=setInterval(()=>{if(index>=labels.length-1){stop();return;}show(index+1);if(index===labels.length-1)stop();},3600);};
 h.$('#'+id+'-next').onclick=()=>{stop();show(Math.min(labels.length-1,index+1));};h.$('#'+id+'-reset').onclick=()=>{stop();show(0);};
 document.querySelectorAll(`[data-${id}-step]`).forEach(b=>b.onclick=()=>{stop();show(Number(b.getAttribute('data-'+id+'-step')));});show(0);return ()=>{stop();cleanup();};
}
function teachCycle(h,items,file){return h.prompt('그림에서 문서로: 조회 → 작성 → 검토 → 수정 → 인계',items,file);}

async function scope(h){
 const [s03,s18,requirements,links,wbs]=await Promise.all([h.doc('S03'),h.doc('S18'),h.query("SELECT r.*,p.name AS owner FROM requirement r LEFT JOIN person p ON r.owner_id=p.person_id WHERE r.req_id <= 'R05' ORDER BY r.req_id"),h.query("SELECT * FROM requirement_wbs WHERE req_id <= 'R05' ORDER BY req_id,posid"),h.query("SELECT w.*,p.name AS owner FROM wbs w LEFT JOIN person p ON w.owner_id=p.person_id WHERE posid <= '1.6' ORDER BY posid")]);
 if(requirements.length!==5||wbs.length!==6)throw Error('S1의 요구사항과 WBS 자료가 필요합니다.');
 const tests={R01:'T01 정산금액',R02:'T02 대사 분류',R03:'T03 예외 필수정보',R04:'T04 접근권한·로그',R05:'T05 운영 인수'};
 h.$('#wb-content').innerHTML=h.intro('scope','“만들었다”의 뜻을 요구·인도물·시험 기준으로 풀어 봅니다. 먼저 R04를 선택해 구현과 검증 두 패키지가 함께 필요한 이유를 설명하세요. 이 화면은 최초 범위 R01~R05의 계획 연습입니다.')+h.sources([s03,s18])+section('1. 요구사항, WBS, 활동은 질문이 다릅니다','<p>요구사항은 누가 무엇을 필요로 하는지, WBS는 무엇을 인도해야 하는지, 활동은 그것을 만들기 위해 어떤 일을 해야 하는지 답합니다. 예를 들어 R04는 권한과 기록이라는 필요이고, 조회 구현과 보안 검증은 서로 다른 완료 증거를 갖는 패키지입니다. 화살표는 업무 순서가 아니라 <strong>추적 관계</strong>입니다.</p><p>S18의 1.1 요구·설계는 전체 요구를 지원합니다. 아래 ERP 연결선에 직접 나타나지 않는 공통 지원도 D11 WBS 사전에서 설명해야 합니다. 요구 번호마다 패키지를 하나씩 복제하면 같은 작업을 중복 계산하기 쉽습니다.</p>')+`<section class="card"><h3>2. 하나의 요구를 끝까지 추적하세요</h3><div class="wb-selectors">${requirements.map(r=>`<button data-scope-req="${r.req_id}">${r.req_id} ${h.esc(r.title)}</button>`).join('')}</div><label class="extra-check"><input id="scope-gap" type="checkbox"> 연습 가정: R04의 1.4 검증 연결을 누락시켜 보기</label><p class="wb-note">체크는 화면의 가상안만 바꿉니다. ERP의 원래 추적 관계와 승인 상태는 유지됩니다.</p>${figure('scope-chart','요구사항, WBS 패키지, 시험 설계의 추적 관계')}<div id="scope-detail" class="wb-detail" aria-live="polite"></div></section>`+section('3. 표와 원천을 나란히 대조하세요',table(h,['요구','필요한 결과','확인 담당','원천 인수기준','원래 연결 WBS'],requirements.map(r=>[r.req_id,r.title,r.owner,r.acceptance,links.filter(l=>l.req_id===r.req_id).map(l=>l.posid).join(' · ')])))+teachCycle(h,['ERP 요구추적에서 R04를 찾고, D09에 요구 책임자·원천 ID·인수기준·WBS·T04를 적습니다. 그림은 계획 관계이며 시험 통과의 증거는 아직 없습니다.','D11에서 1.2의 구현 완료 조건과 1.4의 검증 완료 조건을 각각 작성하세요. 공통 설계·통합검증·전환·안정화의 인도물도 빠뜨리지 않습니다.','QA의 검토 의견 “권한 요구는 있지만 차단 시나리오의 증거 위치가 없다”에 답해 D09·D11을 함께 수정합니다. S18의 8개 기대결과를 확인하고 시험 설계에 연결합니다.','개발·QA·요구 책임자의 검토를 마친 계획을 D02 통합 검토에 넘깁니다. 분야별 합의만으로 범위 기준선 승인이라고 적지 않습니다.'],'D09 요구사항_추적표.md');
 const d3=window.d3,svg=svgBase('scope-chart',970,430,'요구사항 → 인도물 패키지 → 시험 설계. 선택한 요구의 관계를 강조합니다.');
 const reqNodes=requirements.map((r,i)=>({id:r.req_id,label:r.req_id+' '+r.title,x:8,y:54+i*71}));const wbsNodes=wbs.map((w,i)=>({id:w.posid,label:w.posid+' '+w.name,x:337,y:40+i*61}));const testNodes=requirements.map((r,i)=>({id:tests[r.req_id],req:r.req_id,label:tests[r.req_id],x:665,y:54+i*71}));
 svg.selectAll('.extra-heading').data([{x:8,t:'요구 · 필요한 것'},{x:337,t:'WBS · 인도할 것'},{x:665,t:'시험 설계 · 확인할 것'}]).join('text').attr('class','extra-heading').attr('x',d=>d.x).attr('y',20).text(d=>d.t);
 const edgeLayer=svg.append('g'),nodes=[...reqNodes,...wbsNodes,...testNodes];const node=svg.append('g').selectAll('g').data(nodes,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);node.append('rect').attr('width',287).attr('height',44).attr('rx',8).attr('stroke',colors.line).attr('fill',colors.paper);node.append('text').attr('x',12).attr('y',27).attr('font-size',14).text(d=>d.label);
 let selected='R04';const draw=()=>{const gap=h.$('#scope-gap').checked,shown=links.filter(l=>!(gap&&l.req_id==='R04'&&l.posid==='1.4'));const activeWbs=shown.filter(l=>l.req_id===selected).map(l=>l.posid);const edges=shown.flatMap(l=>{const r=reqNodes.find(r=>r.id===l.req_id),w=wbsNodes.find(w=>w.id===l.posid),t=testNodes.find(t=>t.req===l.req_id);return [{id:l.req_id+'>'+l.posid,r:l.req_id,a:r,b:w},{id:l.posid+'>'+l.req_id+'T',r:l.req_id,a:w,b:t}];});
 edgeLayer.selectAll('path').data(edges,d=>d.id).join(enter=>enter.append('path').attr('fill','none').attr('opacity',0),update=>update,exit=>exit.remove()).attr('d',d=>`M${d.a.x+287},${d.a.y+22}C${d.a.x+310},${d.a.y+22} ${d.b.x-22},${d.b.y+22} ${d.b.x},${d.b.y+22}`).call(s=>tween(s,{stroke:d=>d.r===selected?colors.blue:colors.line,'stroke-width':d=>d.r===selected?3:1,opacity:d=>d.r===selected?1:.23}));
 tween(node.select('rect'),{fill:d=>d.id===selected||d.req===selected||activeWbs.includes(d.id)?colors.soft:colors.paper,stroke:d=>d.id===selected||d.req===selected||activeWbs.includes(d.id)?colors.blue:colors.line,'stroke-width':d=>d.id===selected||d.req===selected||activeWbs.includes(d.id)?2:1});buttonStates('data-scope-req',selected);
 const r=requirements.find(r=>r.req_id===selected);h.$('#scope-detail').innerHTML=`<h3>${r.req_id} ${h.esc(r.title)} · ${h.esc(r.owner)} 확인</h3><p><strong>인수기준:</strong> ${h.esc(r.acceptance)}. <strong>연결:</strong> ${activeWbs.join(' · ')} → ${tests[selected]}.</p><p>${gap&&selected==='R04'?'<strong>가상 누락:</strong> 검증 패키지 연결이 사라졌습니다. 구현 담당만 정해 두면 시험 책임과 증거 보관 위치를 놓칠 수 있습니다. D09의 연결과 D11의 완료 조건을 함께 고쳐야 합니다.':selected==='R04'?'1.2는 권한·로그를 구현하고 1.4는 그 결과를 시험합니다. “로그 기능 구현”이라는 설명만으로 타사 조회 차단과 이력삭제 차단을 확인했다고 할 수 없습니다.':selected==='R05'?'교육 참석과 독립 수행은 다릅니다. 3명 각각의 5개 업무 수행, 매뉴얼·복구 절차 승인까지 설계해야 운영 인수 여부를 판단할 수 있습니다.':'시험 방법과 기대결과를 먼저 정하고 나중에 실제 결과를 대조합니다. 지금 D09에 미래의 통과 수나 현업 인수 서명을 채우지 않습니다.'}</p><p><strong>다음 확인:</strong> 개발·QA가 구현·시험 가능성을 검토하고 요구 담당자가 해석을 확인합니다. 통합 기준선 승인은 별도입니다.</p>`;};
 document.querySelectorAll('[data-scope-req]').forEach(b=>b.onclick=()=>{selected=b.dataset.scopeReq;draw();});h.$('#scope-gap').onchange=draw;draw();return cleanup;
}

async function cost(h){
 const [s06,s19,baselines]=await Promise.all([h.doc('S06'),h.doc('S19'),h.query("SELECT * FROM baseline WHERE version='BL01'")]);const model=readCostFacts(s06.body,s19.body),sum=a=>a.reduce((s,x)=>s+x,0);
 h.$('#wb-content').innerHTML=h.intro('cost','작업을 소비한 달과 돈을 지급한 달을 같은 표로 합치면 PM은 예산과 자금 부족을 잘못 판단할 수 있습니다. S06 비용 배분과 S19 지급 조건을 읽고, 월별로 두 곡선이 갈라지는 이유를 확인합니다.')+h.sources([s06,s19])+section('1. 금액에는 이름과 시점이 필요합니다',`<p>작업원가 ${h.money(sum(model.cash))}에 식별 위험의 우발예비비 ${h.money(model.reserve)}를 더하면 원가기준선 후보 ${h.money(sum(model.costs))}입니다. 관리예비비 ${h.money(model.management)}는 그 밖에서 별도로 확보합니다. 우발예비비가 비용계획에 들어 있어도 지금 지출 전표가 발생한 것은 아닙니다.</p><p><strong>이 화면의 기준:</strong> ${baselines.length?'S09/AP01로 승인된 최초 BL01 계획을 재구성합니다. 이후 변경 버전과 섞지 않습니다.':'S1에서 만든 계획 후보입니다. ERP의 기준선이 0건인 것은 예산이 0원이라는 뜻이 아닙니다. 통합 승인 후 BL01이 생깁니다.'} 실제 비용과 실제 지급은 실행 단원의 증빙으로 따로 확인합니다.</p>`)+`<section class="card"><h3>2. 월별 누적을 한 단계씩 쌓아 보세요</h3>${stepsControls('cost',model.months)}<div class="wb-slider"><label for="cost-shift">가상 협의안: 1월 외주 지급 중 12월에 앞당길 금액</label><input id="cost-shift" type="range" min="0" max="${model.deferred/million}" step="1" value="0"><output id="cost-shift-value">0백만원</output><p>청구·검수 조건이 충족된다고 가정한 지급시기 민감도 연습입니다. 실제 계약 수정이나 지급 승인이 아닙니다. 비용계획은 유지됩니다.</p></div>${figure('cost-chart','월별 누적 원가기준선 후보와 계획 지급액 비교')}<div id="cost-detail" class="wb-detail" aria-live="polite"></div><div id="cost-table"></div></section>`+section('3. 곡선 차이가 곧 절감은 아닙니다','<p>11월 외주 비용계획은 20백만원이지만 그달 지급 조건은 12백만원입니다. 차액은 공짜가 된 작업이 아니라 나중에 지급할 금액입니다. 12월 우발예비비는 사용 가능하게 준비할 돈이고, 사건 발생 전부터 확정 현금 지출로 적지 않습니다.</p><p>같은 총지급액이어도 지급을 앞당기면 재무가 미리 확보해야 할 현금이 커집니다. PM은 지급 달력과 비용 기준선을 별도로 관리하고, 변경이 계약·자금·범위에 미치는 영향을 검토 담당자에게 확인합니다.</p>')+teachCycle(h,['D15에서 수량×단가와 고정가 외주의 범위를 검산하고 D17에 작업원가·우발예비비·원가기준선·관리예비비·총자금을 나눠 적습니다.','표의 11월 비용과 지급 차이를 S19 문장으로 설명하세요. 계획 지급액 옆에는 우발예비비 확보와 관리예비비를 별도 열로 둡니다.','재무의 검토 의견 “12월 예비비를 확정 지출에 더했다”에 답해 지급표를 수정합니다. 예비비를 없애는 것이 아니라 자금 확보와 지출을 구분하는 수정입니다.','5단원에서 위험 분석 후 예비비의 타당성을 다시 확인하고, D17을 일정·리스크·조달 조건과 함께 통합 승인에 올립니다.'],'D17 예산_자금계획.md');
 const d3=window.d3,svg=svgBase('cost-chart',930,400,'누적 비용과 지급. 표에 같은 숫자를 제공합니다.'),x=d3.scalePoint().domain(model.months).range([95,865]),y=d3.scaleLinear().domain([0,sum(model.costs)/million*1.1]).range([335,40]);
 svg.append('g').attr('transform','translate(0,335)').call(d3.axisBottom(x));svg.append('g').attr('transform','translate(95,0)').call(d3.axisLeft(y).ticks(6).tickFormat(d=>d+'백만'));svg.append('text').attr('x',95).attr('y',20).attr('font-size',13).text('원안 비용: 실선 파랑 / 지급안: 점선 갈색 · 누적 계획, 실제 실적 아님');const graph=svg.append('g');let step=0;
 const draw=i=>{step=i;const shifted=Number(h.$('#cost-shift').value)*million,cash=model.cash.map((v,j)=>v+(j===2?shifted:j===3?-shifted:0));h.$('#cost-shift-value').textContent=h.money(shifted);let a=0,b=0;const rows=model.months.map((month,j)=>({month,cost:model.costs[j],cash:cash[j],cumCost:a+=model.costs[j],cumCash:b+=cash[j]}));const series=[{id:'cost',color:colors.blue,values:rows.map(r=>({month:r.month,value:r.cumCost})),dash:null},{id:'cash',color:colors.ochre,values:rows.map(r=>({month:r.month,value:r.cumCash})),dash:'7 4'}];const line=d3.line().x(d=>x(d.month)).y(d=>y(d.value/million));
 graph.selectAll('path').data(series,d=>d.id).join('path').attr('fill','none').attr('stroke',d=>d.color).attr('stroke-width',3).attr('stroke-dasharray',d=>d.dash).call(s=>tween(s,{d:d=>line(d.values.slice(0,i+1))}));const points=series.flatMap(s=>s.values.slice(0,i+1).map(v=>({...v,id:s.id+v.month,color:s.color})));graph.selectAll('circle').data(points,d=>d.id).join('circle').attr('r',5).attr('fill',d=>d.color).call(s=>tween(s,{cx:d=>x(d.month),cy:d=>y(d.value/million)}));
 const row=rows[i];h.$('#cost-detail').innerHTML=`<h3>${row.month} · ${shifted?'가상 지급 협의안':'S06/S19 원안'}</h3><div class="wb-grid">${h.metric('누적 비용계획',h.money(row.cumCost),'우발예비비 포함 / 실제원가 아님')}${h.metric('누적 계획 지급액',h.money(row.cumCash),'후보 지급조건 / 실제 지급 아님')}${h.metric('두 계획의 차이',h.money(row.cumCost-row.cumCash),'시기와 예비비 구성 차이')}</div><p>${['10월 요구정의 비용과 지급은 같은 달입니다. 곡선이 겹쳐도 두 개념을 구분해 표의 열을 유지하세요.','11월 외주 부분검수 20백만원 중 12백만원만 지급합니다. 비용에 비해 현금이 적게 나간 이유는 지급시기입니다.','12월에는 외주 비용10과 우발예비비10이 비용계획에 포함됩니다. 예비비는 확보 대상이며 계획 지급이 아닙니다.','원안 총 계획 지급110과 비용기준선120의 차이는 아직 지출되지 않은 우발예비비10입니다. 별도 관리예비비12까지 합친 총자금132는 현금 지출 총액과 다릅니다.'][i]}</p>`;
 h.$('#cost-table').innerHTML=table(h,['월','당월 비용계획','당월 계획 지급','누적 비용','누적 지급'],rows.slice(0,i+1).map(r=>[r.month,h.money(r.cost),h.money(r.cash),h.money(r.cumCost),h.money(r.cumCash)]));};const dispose=player(h,'cost',model.months,draw);h.$('#cost-shift').oninput=()=>draw(step);return dispose;
}

async function risk(h){
 const [s07,s19]=await Promise.all([h.doc('S07'),h.doc('S19')]),facts=readRiskFacts(s07.body),reserve=requireValue(s19.body.match(/우발예비비(\d+)백만원/)?.[1],'S19 예비비 조건이 필요합니다.')*million;
 h.$('#wb-content').innerHTML=h.intro('risk','위험의 순위를 정하는 점수와 돈으로 계산하는 기대손실은 다른 판단 도구입니다. 두 위험을 독립이라고 가정했을 때의 네 가지 경우를 그림으로 펼치고, 예비비가 충분하다는 말의 한계를 확인합니다.')+h.sources([s07,s19])+section('1. 아직 일어나지 않은 사건을 구체적으로 씁니다','<p>“일정 지연”만 쓰면 무엇을 관찰할지 알기 어렵습니다. K01은 외주 인터페이스 불일치, K02는 테스트 환경 지연이라는 사건입니다. 원인과 발생 신호, 비용·일정 영향, 책임자를 함께 D25에 적습니다. 표본검증 실패나 환경 인계 지연이 실제로 발생했다면 이슈로 옮겨 대응해야 합니다.</p><p>정성 순위는 S07의 실제 확률 × 영향등급(중2·고3)을 사용합니다. 두 점수가 같으면 일정 영향이 큰 위험을 먼저 봅니다. 정량분석에서는 등급 대신 금액을 사용합니다. 서로 단위가 다른 두 계산을 더하지 마세요.</p>')+`<section class="card"><h3>2. 확률을 바꾸면 위험의 분포가 어떻게 변하나요?</h3><div class="wb-slider-grid">${facts.map(f=>`<div class="wb-slider"><label for="risk-${f.id}">${f.id} · ${h.esc(f.name)}</label><input id="risk-${f.id}" type="range" min="0" max="100" step="5" value="${f.p*100}"><output id="risk-${f.id}-value">${percent(f.p)}</output><p>비용영향 ${h.money(f.cost)} / 일정 ${f.days}일 / ${h.esc(f.owner)}</p></div>`).join('')}<div class="wb-slider"><label for="risk-reserve">검토할 우발예비비</label><input id="risk-reserve" type="range" min="0" max="30" step="1" value="${reserve/million}"><output id="risk-reserve-value">${h.money(reserve)}</output><p>원안 10백만원 / 변경은 승인 전 가정</p></div></div><div class="wb-selectors"><button id="risk-reset">S07 원안으로 초기화</button><button id="risk-reveal" class="button primary">먼저 예상한 뒤 네 경우 계산하기</button></div><p id="risk-mode" class="wb-note"></p>${figure('risk-matrix','확률과 비용영향 등급의 위험 매트릭스')}<div id="risk-result" hidden><h3>3. 네 경우의 확률과 손실을 함께 읽으세요</h3>${figure('risk-outcomes','네 가지 독립 위험 발생 경우와 확률')}<div id="risk-detail" class="wb-detail" aria-live="polite"></div><div id="risk-table"></div></div></section>`+section('4. 예비비와 품질 기준을 연결해 검토합니다','<p>기대손실은 같은 조건이 반복될 때의 평균입니다. 예비비와 기대손실을 비교한 것만으로 한 번의 프로젝트에서 손실을 모두 감당한다고 보장할 수 없습니다. 동시 발생도 따져 보고 감당 못 하는 금액과 책임자의 대응을 설명해야 합니다.</p><p>독립 가정이 깨지면 네 경우의 확률도 바뀝니다. 이 실습에서는 S07의 독립 가정을 사용하고, 실제 프로젝트에서는 환경 문제와 외주 결함이 서로 영향을 주는지 확인합니다. 예방조치는 S19의 기존 설계·QA 업무에 포함되므로 별도 고정가를 다시 더하지 않습니다.</p><p>품질 측면에서는 R01~R05 인수조건과 요구–설계–시험 연결을 매주 확인합니다. 위험 예방 점검이 통과해도 최종 권한시험 8/8이나 현업 인수까지 자동으로 통과한 것은 아닙니다.</p>')+teachCycle(h,['D25에 K01/K02의 사건·확률·영향·책임·발생 신호를 적고 정성 점수를 계산합니다. 동점 처리 규칙을 문장으로 남깁니다.','D26에서 네 경우의 확률 합이 100%인지 검산하고, 각 확률×손실을 더해 기대금액을 구합니다. 예비비 이내인 경우의 확률도 따로 적습니다.','재무의 검토 의견 “기대손실보다 예비비가 크니 안전하다고 단정했다”에 답해, 동시 발생 손실과 잔여 대응을 설명하도록 수정합니다.','D17 예비비 검토에 이 분석을 연결하고, D18 품질 점검과 D25의 재평가 시점을 정합니다. 아직 실행 점검 결과나 잔여 확률을 앞당겨 기입하지 않습니다.'],'D26 정량리스크 분석.md');
 const d3=window.d3,matrix=svgBase('risk-matrix',930,280,'정성 매트릭스. 가로 확률, 세로 영향등급, 실제 위험 두 개를 표시합니다.'),x=d3.scaleLinear().domain([0,1]).range([125,875]),y=d3.scalePoint().domain([1,2,3]).range([215,55]);matrix.append('g').attr('transform','translate(0,245)').call(d3.axisBottom(x).ticks(5).tickFormat(percent));matrix.append('g').attr('transform','translate(125,0)').call(d3.axisLeft(y).tickFormat(d=>({1:'저 1',2:'중 2',3:'고 3'})[d]));matrix.selectAll('line.extra-risk-grid').data([1,2,3]).join('line').attr('x1',125).attr('x2',875).attr('y1',d=>y(d)).attr('y2',d=>y(d)).attr('stroke',colors.line).attr('stroke-dasharray','3 4');matrix.append('text').attr('x',125).attr('y',22).text('정성 위치: 확률 × 비용영향 등급 / 원의 크기는 금액이 아닙니다');const dots=matrix.selectAll('g.extra-risk-dot').data(facts).join('g').attr('class','extra-risk-dot');dots.append('circle').attr('r',11).attr('fill',d=>d.id==='K01'?colors.blue:colors.ochre);dots.append('text').attr('x',16).attr('y',5).text(d=>d.id);
 const bars=svgBase('risk-outcomes',930,265,'각 경우의 발생 확률. 손실 금액과 초과 여부는 아래 표에서 확인합니다.'),bx=d3.scaleLinear().domain([0,1]).range([200,840]);bars.append('g').attr('transform','translate(0,228)').call(d3.axisBottom(bx).ticks(5).tickFormat(percent));let revealed=false;
 const draw=()=>{const probs=facts.map(f=>Number(h.$('#risk-'+f.id).value)/100),r=Number(h.$('#risk-reserve').value)*million;facts.forEach((f,i)=>h.$('#risk-'+f.id+'-value').textContent=percent(probs[i]));h.$('#risk-reserve-value').textContent=h.money(r);const changed=probs.some((p,i)=>p!==facts[i].p)||r!==reserve;h.$('#risk-mode').textContent=changed?'가상 민감도 연습 · 원천·예산을 수정하지 않습니다. 확률 저하는 수행·검증 증거 없이 확정할 수 없습니다.':'S07 원안 · 독립 발생 가정. 예비비는 S19의 계획 후보입니다.';tween(dots,{transform:(f,i)=>`translate(${x(probs[i])},${y(f.rank)})`});if(!revealed)return;
 const result=riskOutcomes(probs[0],probs[1],facts[0].cost,facts[1].cost,r),rows=bars.selectAll('g.extra-outcome').data(result.rows,d=>d.name).join(enter=>{const g=enter.append('g').attr('class','extra-outcome');g.append('text').attr('class','extra-outcome-name').attr('x',8);g.append('rect').attr('x',200).attr('height',24).attr('rx',3);g.append('text').attr('class','extra-outcome-value').attr('font-size',13);return g;}).attr('transform',(d,i)=>`translate(0,${30+i*47})`);rows.select('.extra-outcome-name').attr('y',17).text(d=>d.name);tween(rows.select('rect'),{width:d=>bx(d.p)-200,fill:d=>d.loss>r?colors.ochre:colors.blue});rows.select('.extra-outcome-value').attr('y',17).attr('x',d=>Math.min(845,bx(d.p)+8)).text(d=>percent(d.p));
 const scores=facts.map((f,i)=>probs[i]*f.rank),tie=Math.abs(scores[0]-scores[1])<1e-8;h.$('#risk-detail').innerHTML=`<div class="wb-grid">${h.metric('기대손실',h.money(result.emv),'확률 × 금액의 합 / 최대손실 아님')}${h.metric('예비비 이내일 확률',percent(result.covered),'네 경우 중 손실 ≤ 예비비인 확률의 합')}${h.metric('최대 시나리오 손실',h.money(facts[0].cost+facts[1].cost),'두 위험 동시 발생 조건')}</div><p><strong>정성 점수:</strong> K01 ${scores[0].toFixed(2)}, K02 ${scores[1].toFixed(2)}. ${tie?'동점이므로 일정영향이 큰 K02를 먼저 점검합니다.':'현재 가정에서는 '+(scores[0]>scores[1]?'K01':'K02')+'의 정성 점수가 큽니다.'} 이 점수는 금액이 아닙니다.</p><p><strong>정량 판단:</strong> 예비비를 초과할 확률은 ${percent(1-result.covered)}입니다. ${h.money(result.emv)}라는 평균만 보고 “${h.money(r)}이면 모든 경우를 감당한다”고 결론 내릴 수 없습니다. 초과분의 기대금액은 ${h.money(result.excess)}이며 실제 발생 손실을 예언하는 값은 아닙니다.</p>`;h.$('#risk-table').innerHTML=table(h,['경우','확률','손실','확률×손실','예비비 이내'],result.rows.map(v=>[v.name,percent(v.p),h.money(v.loss),h.money(v.p*v.loss),v.loss<=r?'이내':'초과']));};
 facts.forEach(f=>h.$('#risk-'+f.id).oninput=draw);h.$('#risk-reserve').oninput=draw;h.$('#risk-reveal').onclick=()=>{revealed=true;h.$('#risk-result').hidden=false;h.$('#risk-reveal').hidden=true;draw();};h.$('#risk-reset').onclick=()=>{facts.forEach(f=>h.$('#risk-'+f.id).value=f.p*100);h.$('#risk-reserve').value=reserve/million;draw();};draw();return cleanup;
}

async function procurement(h){
 const [s08,s19,s02,actual]=await Promise.all([h.doc('S08'),h.doc('S19'),h.doc('S02'),h.query('SELECT * FROM v_조달조회')]);const proposals=[...s08.body.matchAll(/(가온시스템|누리소프트) 제안(\d+)백만원, 기술(\d+)\/납기(\d+)\/가격(\d+)/g)].map(m=>({name:m[1],cost:Number(m[2])*million,scores:m.slice(3).map(Number)}));if(proposals.length!==2)throw Error('S08의 두 제안서를 확인해 주세요.');const weights=[.5,.3,.2],labels=['같은 범위','사전 평가','계약 서명','발주','검수','청구·지급'];
 const checkpoints=[['PM·개발·운영','R02/R03의 소스·시험 증거·설치설명서를 SOW에 적습니다. 납기만 정하면 나중에 무엇을 검수할지 합의하기 어렵습니다.','D27 SOW / S08·S19'],['구매·평가 참여자','기술50%·납기30%·가격20%로 두 제안을 비교합니다. 낮은 가격 하나만으로 결정하지 않고 같은 인도물과 보증 조건인지 확인합니다.','D28 평가표 / S08'],['강태훈 작성 → 최민석 검토 → 윤서진 서명','PM의 추천은 계약 서명이 아닙니다. 납품 목표·검수·무상 결함 보완·지급 조건을 검토하고 승인권자의 서명 기록을 받습니다.','계약 원본 / S02·S19'],['구매 담당','승인 계약과 구매요청을 발주번호로 연결합니다. 발주액은 앞으로 구입할 약정이며 지금 발생한 비용이나 현금 지급액이 아닙니다.','PR → CT → PO 연결'],['QA 증거·운영 인수와 구매 기록','부분 용역 검수와 최종 인수를 나눕니다. 납품만으로 합격이라고 쓰지 않고 계약 범위·시험 증거·결함 보완을 대조합니다.','SA 검수 / D29 계약이행'],['재무 담당','검수 증거에 청구를 연결하고 실제 지급일·금액을 따로 남깁니다. 하나의 거래를 발주·검수·청구·지급 열에서 네 번 비용으로 더하지 않습니다.','IV 청구 → PY 지급 / 전표 대조']];
 h.$('#wb-content').innerHTML=h.intro('procurement','업체를 고르는 판단과 계약을 체결하는 권한, 일을 확인하는 검수와 돈을 내는 지급을 한 흐름에서 구분합니다. 현재 자료에 존재하는 증거만 실제 상태로 읽고, 아직 없는 단계는 예정 절차로 남깁니다.')+h.sources([s08,s19,s02])+`<section class="card"><h3>1. 가격이 가장 낮으면 언제나 최선일까요?</h3><p>먼저 S08의 점수와 사전 가중치로 예상해 보세요. 가격점수는 구매부서가 이미 정규화한 값입니다. 제안 금액을 임의의 새 산식으로 다시 점수화하지 않습니다.</p><button id="proc-score-show" class="button primary">가중 점수 계산 펼치기</button><div id="proc-score-result" hidden>${figure('proc-score-chart','사전 가중치에 따른 기술·납기·가격 점수의 합')}<div id="proc-score-table"></div><p class="wb-note">가온은 30백만원, 누리는 28백만원 제안입니다. 비교 점수가 추천 근거가 되지만 계약 체결 사실은 S09의 별도 승인으로 확인합니다.</p></div></section><section class="card"><h3>2. 각 단계를 통과시키는 증거와 책임을 확인하세요</h3>${stepsControls('proc',labels)}${figure('proc-flow','외주 범위, 평가, 계약, 발주, 검수, 청구 지급의 연결')}<div id="proc-detail" class="wb-detail" aria-live="polite"></div></section>`+section('3. 현재 ERP의 기록은 어디까지 있나요?',actual.length?table(h,['발주','계약','공급사','약정액','누적 검수','누적 청구','누적 지급'],actual.map(v=>[v.발주번호,v.계약번호,v.공급사,h.money(v.발주액),h.money(v.누적검수액),h.money(v.누적청구액),h.money(v.누적지급액)]))+'<p>네 금액은 하나의 거래를 서로 다른 관점에서 읽은 값입니다. 합계를 내서 프로젝트 비용이라고 보고하지 않습니다. 부분검수와 잔금은 S19 지급 조건을 함께 읽으세요.</p>':'<p>현재 스냅샷에는 발주·계약 기록이 없습니다. S1은 평가와 계약 초안을 준비하는 시점입니다. 가온을 추천할 수는 있지만 CT01·PO01이 이미 체결되었다고 D28에 쓰지 않습니다. 통합 승인 뒤 해당 원천과 ERP 기록으로 확인합니다.</p>')+section('4. 협업 방식도 계약처럼 인계 조건을 적습니다','<p>S08의 화요일 작업회의, 금요일 스폰서 보고, 가맹점 격주 요약은 같은 문서를 모두에게 보내라는 뜻이 아닙니다. 작업회의에는 장애물·담당·기한, 스폰서에게는 편차·의사결정 요청, 가맹점에는 업무 영향과 필요한 안내를 전달합니다. 내부 인건비는 외부 요약에 넣지 않습니다.</p><p>수신 확인이 없다면 정보가 전달되었다고 단정하지 말고 D23에 후속 담당과 확인 시점을 적습니다. D31에서는 운영·가맹점의 현재 중립 상태에서 어떤 시연과 확인 활동을 통해 지원을 얻을지 구체적으로 정합니다.</p>')+teachCycle(h,['D27에 외주 범위·인도물·검수·보증·지급·변경 절차를 적습니다. 내부 4명의 개발 배정에 외주 전문 역량이 포함되는지 S19로 확인합니다.','D28에 두 업체의 원점수·가중치·산식을 남기고 추천 이유를 씁니다. 가중치는 제안서를 본 뒤 유리한 업체에 맞춰 바꾸지 않습니다.','구매의 검토 의견 “잔여 대금 지급과 보증 종료를 같은 날로 적었다”에 답해 지급 채무와 30일 무상 보완 책임을 다른 항목으로 수정합니다.','D23·D31의 소통·참여 계획을 정리하고 계약 조건을 통합 계획 검토에 넘깁니다. 이후 검수·청구·지급 증거는 D29에 같은 계약번호로 누적합니다.'],'D28 제안평가_계약검토.md');
 const d3=window.d3,scoreSvg=svgBase('proc-score-chart',930,210,'가중 점수. 기술, 납기, 가격의 합계.'),scored=proposalScores(proposals,weights),sx=d3.scaleLinear().domain([0,100]).range([180,850]);scoreSvg.append('g').attr('transform','translate(0,165)').call(d3.axisBottom(sx).ticks(5));h.$('#proc-score-show').onclick=()=>{h.$('#proc-score-show').hidden=true;h.$('#proc-score-result').hidden=false;const series=scored.flatMap((p,i)=>{let start=0;return p.scores.map((s,j)=>{const v=s*weights[j],row={id:p.name+j,name:p.name,i,j,start,value:v};start+=v;return row;});});scoreSvg.selectAll('rect').data(series,d=>d.id).join('rect').attr('x',d=>sx(d.start)).attr('y',d=>35+d.i*65).attr('height',30).attr('width',0).attr('fill',d=>[colors.blue,colors.ochre,colors.muted][d.j]).call(s=>tween(s,{width:d=>sx(d.value)-180}));scoreSvg.selectAll('text.extra-prop').data(scored).join('text').attr('class','extra-prop').attr('x',5).attr('y',(d,i)=>55+i*65).text(d=>d.name+' '+d.total+'점');h.$('#proc-score-table').innerHTML=table(h,['업체','제안금액','기술 ×50%','납기 ×30%','가격 ×20%','합계'],scored.map(p=>[p.name,h.money(p.cost),p.scores[0]+' × .5 = '+p.scores[0]*.5,p.scores[1]+' × .3 = '+p.scores[1]*.3,p.scores[2]+' × .2 = '+p.scores[2]*.2,p.total]));};
 const svg=svgBase('proc-flow',930,155,'외주 업무의 단계. 선택한 단계의 책임과 증거를 아래에 표시합니다.');svg.selectAll('path').data(labels.slice(0,-1)).join('path').attr('d',(d,i)=>`M${i*154+141},75H${(i+1)*154+2}`).attr('stroke',colors.line).attr('stroke-width',2);const nodes=svg.selectAll('g').data(labels).join('g').attr('transform',(d,i)=>`translate(${i*154+3},28)`);nodes.append('rect').attr('width',138).attr('height',90).attr('rx',8).attr('fill',colors.paper).attr('stroke',colors.line);nodes.append('text').attr('x',13).attr('y',35).text((d,i)=>(i+1)+'. '+d);nodes.append('text').attr('x',13).attr('y',63).attr('font-size',12).text((d,i)=>['범위 합의','추천 근거','권한 확인','약정 기록','이행 확인','채무·현금'][i]);return player(h,'proc',labels,i=>{tween(nodes.select('rect'),{fill:(d,j)=>j===i?colors.soft:colors.paper,stroke:(d,j)=>j===i?colors.blue:colors.line,'stroke-width':(d,j)=>j===i?3:1});h.$('#proc-detail').innerHTML=`<h3>${labels[i]} · ${checkpoints[i][0]}</h3><p>${checkpoints[i][1]}</p><p><strong>다음 단계로 넘길 근거:</strong> ${checkpoints[i][2]}</p><p class="wb-note">현재 버튼은 절차를 설명합니다. 클릭이 실제 계약·검수·지급을 실행하거나 승인하지 않습니다.</p>`;});
}

async function integration(h){
 const [s09,s10,s20,resources]=await Promise.all([h.doc('S09'),h.doc('S10'),h.doc('S20'),h.query('SELECT r.*,p.name AS owner FROM physical_resource r LEFT JOIN person p ON r.owner_id=p.person_id')]);const labels=['10/19 배정·착수','10/23 준비 확인','11/27 교육 증거','11/30 점검·후속'];
 const cards=[{id:'WO01-A',name:'인터페이스 표본 확인',owner:'이현우',due:'10/23',show:0,done:1,evidence:'S20: 필드명·금액단위·날짜형식 일치 확인. 최종 제품 인수와 다릅니다.'},{id:'WO01-B',name:'QA 환경 접근·복구 점검',owner:'정유나',due:'10/23',show:0,done:1,evidence:'S20: QA환경1식 접근·복구 점검 통과. S10에서 사용가능 상태를 확인합니다.'},{id:'교육 증거',name:'DEV01·DEV02 로그 실습',owner:'정유나 확인',due:'11/27',show:2,done:2,evidence:'S20: 두 참여자가 각각 로그 작성·조회 실습 통과. 출석만으로 합격 처리하지 않습니다.'},{id:'DF01',name:'마스킹 표시 오류 두 건',owner:'이현우',due:'12/04',show:3,done:99,evidence:'S10/S20: 조회 시험20개 중18통과. 보완 예정이며 아직 재시험 결과는 없습니다.'},{id:'면담 후속',name:'집중시간·질문 미해결 확인',owner:'이현우·정유나',due:'12/07',show:3,done:99,evidence:'S20: 오전 집중시간 보호와16:30 질문 취합 합의. 효과 측정은12/07 예정입니다.'},{id:'소통 후속',name:'가맹점 요약 미확인 사유',owner:'박다은',due:'회신기한 합의 필요',show:3,done:99,evidence:'S20: 11/27 요약 미확인. 김소연에게 이유를 묻고 설명을 요청합니다. 반대자로 단정하지 않습니다.'}];
 h.$('#wb-content').innerHTML=h.intro('integration','실행 중 PM은 회의록을 업무로 바꾸고, 담당자의 “완료”라는 말에 어떤 증거가 연결되는지 확인합니다. S2에서 공개된 날짜별 원장을 되짚는 재생 화면입니다. 미래의 종료 결과를 끌어오지 않습니다.')+h.sources([s09,s10,s20])+section('1. 통합계획은 분야별 문서의 합본에서 한 단계 더 갑니다','<p>범위에 넣은 요구를 일정이 수행할 수 있는지, 그 일정에 필요한 인원과 비용이 있는지, 조달 인도일이 시험 착수 조건을 만족하는지 맞춥니다. S09의 AP01 이후에는 승인본을 공지하고 팀이 같은 버전으로 일하도록 합니다.</p><p>작업 보드는 그중 실행과 후속 확인을 돕는 도구입니다. D03에는 사실·결정·담당·기한·완료 증거를 남깁니다. 아래 보드는 원장의 일부 항목을 학습용 카드로 재구성한 것이며 전체 일정이나 공식 완료율을 대신하지 않습니다.</p>')+`<section class="card"><h3>2. 시간이 지나면 카드는 어떤 근거로 이동하나요?</h3>${stepsControls('board',labels)}${figure('execution-board','근거 확인 대기와 확인된 결과를 분리한 실행 보드')}<div id="board-detail" class="wb-detail" aria-live="polite"></div><div id="board-table"></div></section>`+section('3. 자원과 참여는 숫자만 세지 않습니다',table(h,['자원','계획 수량','확보 수량','현재 상태','책임자'],resources.map(r=>[r.name,r.planned_qty,r.allocated_qty,r.status,r.owner]))+'<p>S20의 C 36/50인일 사용을 보고 진척72%라고 쓰지 마세요. 검증된 산출물 가치와 소비한 공수는 서로 다릅니다. 잔여14인일이 충분한지는 미완료 항목을 다시 추정해야 판단할 수 있습니다.</p><p>운영 회의3/4 참석이나 가맹점 요약1/2 확인은 후속 질문의 출발점입니다. 미확인 사유와 필요한 설명을 확인하고, 팀 갈등에는 관찰 사실·업무 영향·구체적 요청으로 접근합니다.</p>')+teachCycle(h,['D03에 WO01-A/B의 담당·기한·출처를 쓰고 S20의 확인 증거가 공개되는 시점에 완료 상태를 갱신합니다. 이 완료는 준비 점검 완료이며 프로젝트 인수 완료가 아닙니다.','DF01은 D20 결함대장, 불확실한 K01/K02는 D25 리스크등록부로 구분합니다. 위험 예방 결과가 확인되면 S10 근거로 잔여 확률을 갱신합니다.','검토 의견 “면담에서 합의했으니 문제 해결 완료로 표시했다”에 답해,12/07 후속 확인 담당·지표를 남기는 상태로 수정합니다.','D05에는 사실·해석·요청을 분리해 보고합니다. 기준선 변경이 필요한 업무는 작업 보드에서 임의 완료하지 말고 D06 통합변경 절차로 넘깁니다.'],'D03 작업_이슈 기록.md');
 const d3=window.d3,svg=svgBase('execution-board',970,660,'원천 증거에 따라 카드가 확인 대기에서 확인 완료로 이동합니다.');const columns=[{x:5,name:'배정·수행 / 증거 대기'},{x:335,name:'후속 확인 예정'},{x:665,name:'근거 확인 완료'}];svg.selectAll('rect.extra-lane').data(columns).join('rect').attr('class','extra-lane').attr('x',d=>d.x).attr('y',12).attr('width',310).attr('height',625).attr('rx',10).attr('fill',colors.soft);svg.selectAll('text.extra-lane-title').data(columns).join('text').attr('class','extra-lane-title').attr('x',d=>d.x+15).attr('y',43).text(d=>d.name);const layer=svg.append('g');
 return player(h,'board',labels,step=>{const visible=cards.filter(c=>c.show<=step).map(c=>({...c,col:step>=c.done?2:c.show===3?1:0})),counts=[0,0,0];visible.forEach(c=>{c.x=columns[c.col].x+12;c.y=70+(counts[c.col]++)*177;});const joined=layer.selectAll('g').data(visible,d=>d.id).join(enter=>{const g=enter.append('g');g.append('rect').attr('width',286).attr('height',158).attr('rx',8).attr('fill',colors.paper).attr('stroke',colors.line);g.append('text').attr('class','extra-card-id').attr('x',14).attr('y',26).attr('font-weight',700);g.append('text').attr('class','extra-card-name').attr('x',14).attr('y',53).attr('font-size',14);g.append('text').attr('class','extra-card-owner').attr('x',14).attr('y',84).attr('font-size',13);g.append('text').attr('class','extra-card-due').attr('x',14).attr('y',107).attr('font-size',13);g.append('text').attr('class','extra-card-state').attr('x',14).attr('y',136).attr('font-size',13);return g;},update=>update,exit=>exit.remove());tween(joined,{transform:d=>`translate(${d.x},${d.y})`});joined.select('.extra-card-id').text(d=>d.id);joined.select('.extra-card-name').text(d=>d.name);joined.select('.extra-card-owner').text(d=>'담당: '+d.owner);joined.select('.extra-card-due').text(d=>'기한: '+d.due);joined.select('.extra-card-state').text(d=>d.col===2?'✓ 원천 확인 증거 있음':'○ 후속 증거 필요');
 h.$('#board-detail').innerHTML=`<h3>${labels[step]} · 그 날짜까지 확인 가능한 상태</h3><p>${['S09의 킥오프 결정과 S20의 배정 확인을 작업으로 전환합니다. 담당과 기한은 정했지만 결과 증거는 아직 확인 전입니다.','WO01-A/B 결과가 확인되어 준비 작업을 완료로 옮깁니다. 최종 인수시험과 구분하는 완료 조건이 중요합니다.','로그 교육의 참석과 실습 통과를 구분합니다. 검증된 두 명의 실습 증거가 있기에 교육 결과를 기록할 수 있습니다.','DF01과 면담·소통 후속은 열린 업무입니다. “하기로 했다”는 합의를 결과로 오인하지 않고 다음 확인까지 관리합니다.'][step]}</p><p><strong>후속 질문:</strong> ${step===3?'무엇이 확인되면 각 카드를 닫을 수 있나요? 재시험 결과,12/07 지표 점검, 가맹점 회신을 각각 적으세요.':'작업 완료를 다른 사람이 확인하려면 어떤 원천 문장과 담당자의 확인 기록이 필요한가요?'}</p>`;h.$('#board-table').innerHTML=table(h,['기록','상태','담당 / 기한','증거 또는 다음 확인'],visible.map(c=>[c.id,c.col===2?'근거 확인 완료':'확인 대기',c.owner+' / '+c.due,c.col===2||step===3?c.evidence:'해당 기한에 결과 확인. 미래 결과를 먼저 기록하지 않습니다.']));});
}

async function closure(h){
 const [s13,s14,s15,s21,rows,baseline,costs,approvals,proc]=await Promise.all([h.doc('S13'),h.doc('S14'),h.doc('S15'),h.doc('S21'),h.query('SELECT r.req_id,r.title,r.acceptance,t.test_id,t.tested,t.passed,t.critical_open FROM requirement r JOIN test_result t USING(req_id) ORDER BY r.req_id'),h.query("SELECT * FROM baseline WHERE status='현행'"),h.query('SELECT SUM(누적비용) AS total FROM v_프로젝트원가'),h.query("SELECT a.*,p.name AS name FROM approval a JOIN person p ON a.approved_by=p.person_id WHERE approval_id='AP03'"),h.query('SELECT * FROM v_조달조회')]);if(rows.length!==6||!baseline.length||!approvals.length)throw Error('S4의 시험·기준선·종료승인 자료가 필요합니다.');const labels=['시험 증거','현업·보안 확인','운영·계약·자원 인계','종료 승인·편익 추적'],b=baseline[0],total=costs[0].total;
 h.$('#wb-content').innerHTML=h.intro('closure','테스트가 통과하면 QA가 검증하고, 현업이 받아들인 뒤, 스폰서가 잔여 책임 인계까지 확인해 종료합니다. 이번에는 S4에 실제로 존재하는 시험·인수·종료 기록을 연결하고, 종료 이후에도 남는 책임을 찾아봅니다.')+h.sources([s13,s14,s15,s21])+section('1. 통과율은 증거의 일부입니다','<p>480개 거래 중 불일치12건이 있더라도 이를 정확히 분류했다면 대사 기능의 시험은 성공할 수 있습니다. R02의 기준은 모든 거래 금액이 같아지는 것이 아니라 일치·불일치의 정확한 분류입니다. R05는 교육에 참석한 인원수보다 각 운영자의 독립 수행과 문서 승인이 중요합니다.</p><p>아래 ERP 시험 집계는 요약입니다. T04의 차단·허용 기대결과와 로그 누락0, T05의 15개 행동, T06의 다운로드 권한·로그3/3 같은 세부 근거는 S15/S13을 함께 읽어야 합니다.</p>')+`<section class="card"><h3>2. 증거에서 승인까지의 연결을 재생하세요</h3>${stepsControls('close',labels)}<label class="extra-check"><input id="close-missing" type="checkbox"> 가상 검토 연습: R04 상세 시험 증거를 받지 못한 경우</label><p class="wb-note">실제 S4의 시험 결과와 승인 이력은 그대로입니다. 이 가정에서는 무엇을 추가 확인해야 하는지 판단해 보세요.</p>${figure('closure-flow','시험, 현업 보안 확인, 운영 계약 자원 인계, 종료 승인의 증거 연결')}<div id="close-detail" class="wb-detail" aria-live="polite"></div></section>`+section('3. 요구별 집계와 세부 증거를 대조하세요',table(h,['요구','인수기준','시험','시도 / 통과','열린 치명결함'],rows.map(r=>[r.req_id+' '+r.title,r.acceptance,r.test_id,r.tested+' / '+r.passed,r.critical_open])))+section('4. 비용을 닫아도 편익 측정은 남습니다',`<div class="wb-grid">${h.metric('최종 실제원가',h.money(total),'프로젝트 비용 전표 합계')}${h.metric(b.version+' 대비 미사용',h.money(b.bac-total),'미사용액은 매출·사업편익이 아님')}${h.metric('관리예비비 포함 미사용',h.money(b.bac+b.management_reserve-total),'자금 해제와 편익 실현을 구분')}</div>${table(h,['계약','누적 검수','누적 청구','누적 지급','잔여 약정'],proc.map(p=>[p.계약번호,h.money(p.누적검수액),h.money(p.누적청구액),h.money(p.누적지급액),h.money(p.발주액-p.누적검수액)]))}<p>S21은 지급채무0과 보증 책임 종료를 구분합니다. CT01의 무상 결함 보완 창구는 1월23일~2월21일 유지됩니다. 잔액이 없다고 운영팀에 넘길 책임도 없는 것은 아닙니다.</p><p>첫 주 평균65분은 목표60분 달성의 증거가 아닙니다. 박다은이 2월1일~2월26일의 20영업일을 측정하고 윤서진에게 보고합니다. 아직 없는 미래 측정 결과는 종료보고에 채우지 않고 담당·기한·방법을 인계합니다.</p>`)+teachCycle(h,['D12에 R01~R06의 인수기준, T01~T06 증거, QA 검증, AT01 현업 인수, SC01 보안 확인을 연결합니다. 같은 “완료” 한 칸으로 합치지 않습니다.','D29에서 CT01의 발주·검수·청구·지급·보증 책임을 대조하고 D22에는 운영으로 넘길 QA-01과 해제할 프로젝트 배정을 구분합니다.','검토 의견 “프로젝트가 종료됐으니60분 목표도 달성”에 답해 초기 관찰값과 종료 후20영업일 평가를 분리합니다. D07에 편익 책임자·측정 기간·보고처를 수정합니다.','S21/AP03의 종료 조건과 자신의 종료보고를 대조하고 문서 버전을 보존합니다. 이후 사실은 운영 기록으로 남기며 종료 승인본을 임의로 덮어쓰지 않습니다.'],'D07 종료보고.md');
 const d3=window.d3,svg=svgBase('closure-flow',960,190,'각 단계의 책임과 근거. 실제 승인과 가상 증거 누락을 구분합니다.');svg.selectAll('path').data(labels.slice(0,-1)).join('path').attr('d',(d,i)=>`M${i*239+222},92H${(i+1)*239+7}`).attr('stroke',colors.line).attr('stroke-width',3);const nodes=svg.selectAll('g').data(labels).join('g').attr('transform',(d,i)=>`translate(${i*239+6},30)`);nodes.append('rect').attr('width',218).attr('height',120).attr('rx',10).attr('stroke',colors.line).attr('fill',colors.paper);nodes.append('text').attr('x',13).attr('y',29).attr('font-size',14).text((d,i)=>['QA 정유나','현업 박다은 · 보안 오수빈','운영·구매·재무·자원 담당','스폰서 윤서진'][i]);nodes.append('text').attr('x',13).attr('y',59).attr('font-size',14).text((d,i)=>['시험 검증','AT01 · SC01','OM01 · RB01 · CT01','AP03 / 편익 추적 인계'][i]);nodes.append('text').attr('class','extra-close-state').attr('x',13).attr('y',93).attr('font-size',12);let step=0;
 const draw=i=>{step=i;const missing=h.$('#close-missing').checked;tween(nodes.select('rect'),{fill:(d,j)=>j===i?colors.soft:colors.paper,stroke:(d,j)=>missing&&j===0?colors.red:j===i?colors.blue:colors.line,'stroke-width':(d,j)=>j===i||missing&&j===0?3:1});nodes.select('.extra-close-state').text((d,j)=>missing?'가상안: 증거 보완 전 판단 유보':j<=i?'S4 원천 기록 확인':'다음 근거를 확인하세요');
 const narratives=[['시험과 요구의 대조','S15의 시험 방법·기대결과와 S13 집계를 대조합니다. QA가 확인한 검증 산출물은 현업 인수 판단의 입력입니다. 통과 수만 보고 권한 차단·로그·운영 독립 수행 조건을 생략하지 않습니다.'],['인수와 보안은 역할별 결정','박다은의 AT01은 정산 업무의 인수이며, 오수빈의 SC01은 보안 확인입니다. QA의 검증 증거와 서로 연결되지만 동일한 서명으로 대체하지 않습니다.'],['받을 사람과 남을 책임','OM01/RB01과 QA-01은 운영에 인계합니다. 임시계정 해제·프로젝트 인력 배정 해제·기술지원 창구를 확인합니다. 지급 잔액0과 계속되는 보증 책임을 별도로 적습니다.'],['종료 이후에 측정할 것',`S21의 ${approvals[0].name} 승인 ${approvals[0].approval_id}는 잔여 책임과 편익 추적 인계를 조건으로 합니다. 첫 주65분을 목표 달성으로 바꾸지 않고20영업일 측정과2월26일 보고를 운영에 넘깁니다.`]];
 h.$('#close-detail').innerHTML=`<h3>${narratives[i][0]}</h3><p>${narratives[i][1]}</p>${missing?'<p class="extra-warning"><strong>가상 누락의 영향:</strong> R04 집계8/8만 있고 상세 기대결과·로그 증거를 받지 못했다면, PM은 QA·보안 담당자에게 보완을 요청해야 합니다. 그 가상 상태를 근거로 “모든 종료 조건 확인 완료”라고 새로 판단할 수 없습니다. 실제 S4에는 S15/SC01/AP03이 존재하며 이 연습이 승인 이력을 취소하지 않습니다.</p>':'<p><strong>현재 사실:</strong> S4 원천에는 QA 검증, AT01, SC01, AP03이 있습니다. 학습자는 실제 승인 조건과 자기 문서의 항목을 대조해 누락을 찾아야 합니다.</p>'}`;};const dispose=player(h,'close',labels,draw);h.$('#close-missing').onchange=()=>draw(step);return dispose;
}

export async function renderExtra(key,helpers){
 if(!window.d3)throw Error('시각화 구성요소를 불러오지 못했습니다. 새로고침 후 다시 확인해 주세요.');
 const renderers={scope,cost,risk,procurement,integration,closure};if(!renderers[key])throw Error('시각화 단원을 찾을 수 없습니다.');
 return renderers[key](helpers);
}
