/* A report is an explicit snapshot plus the learner's own interpretation. */
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const drafts=new Map();
window.addEventListener('beforeunload',e=>{if([...drafts.values()].some(d=>d.dirty)){e.preventDefault();e.returnValue='';}});
const fields=[['summary','결과 요약','이번 검토에서 확인한 사실을 두세 문장으로 적으세요.'],['analysis','차트·표의 해석','무엇을 바꾸었고 왜 결과가 달라졌는지 근거와 함께 적으세요.'],['recommendation','권고와 결정 요청','누가 무엇을 검토하거나 결정해야 하는지 적으세요.'],['open','미결 사항과 후속 확인','확인할 담당자·질문·기한을 적으세요. 없으면 그 판단의 근거를 적으세요.']];
const prose=value=>value?.trim()?value.trim().split(/\n\s*\n/).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join(''):'<p class="doc-missing">아직 작성하지 않은 항목입니다. 그림과 원천을 확인한 뒤 자신의 판단을 적으세요.</p>';
function visible(el){return !el.closest('[hidden]')&&el.getClientRects().length>0;}
function capture(root){
 const conditions=[...root.querySelectorAll('input[type=range],input[type=checkbox],select')].filter(visible).map(el=>({name:root.querySelector(`label[for="${CSS.escape(el.id)}"]`)?.textContent.trim()||el.closest('label')?.textContent.trim()||el.id,value:el.type==='checkbox'?(el.checked?'적용':'미적용'):el.value}));
 const selections=[...root.querySelectorAll('button[aria-pressed=true]')].filter(visible).map(b=>b.textContent.trim());
 const sources=[...root.querySelectorAll('.wb-source>summary')].map(el=>el.textContent.trim());
 const targets=[...root.querySelectorAll('.wb-figure,.wb-bars,.wb-grid,.reading-table,.wb-detail,.wb-approval,.wb-caption,.wb-legend,.wb-note')].filter(el=>visible(el)&&!el.closest('.wb-source,.wb-prompt,.wb-playback'));
 const outer=targets.filter(el=>!targets.some(other=>other!==el&&other.contains(el)));
 const host=document.createElement('div');
 for(const el of outer){const clone=el.cloneNode(true);clone.querySelectorAll('button,input,select,textarea,script,.wb-selectors,.wb-playback,.extra-player,.wb-traveller').forEach(n=>n.remove());clone.querySelectorAll('a[href]').forEach(a=>a.href=new URL(a.getAttribute('href'),location.href).href);host.append(clone);}
 // SVG marker IDs must stay local to the snapshot, even when both copies are visible.
 const ids=new Map([...host.querySelectorAll('[id]')].map(el=>[el.id,'report-'+el.id]));
 host.querySelectorAll('*').forEach(el=>{if(el.id)el.id=ids.get(el.id);for(const attr of [...el.attributes]){if(attr.name.startsWith('on'))el.removeAttribute(attr.name);else if(attr.value.includes('url(#'))el.setAttribute(attr.name,attr.value.replace(/url\(#([^)]*)\)/g,(all,id)=>ids.has(id)?`url(#${ids.get(id)})`:all));}});
 return {conditions,selections,sources,html:host.innerHTML};
}
function documentHTML(d,m,meta){
 const s=d.snapshot;const conditionRows=s.conditions.map(c=>`<tr><th>${esc(c.name)}</th><td>${esc(c.value)}</td></tr>`).join('');
 return `<article class="pm-document doc-captured-report"><header class="doc-masthead"><div><p class="doc-id">MP-01 / ${esc(d.module)} / ${esc(d.version||'v0.1')}</p><h2>${esc(m.title)} · 검토 메모</h2><p class="doc-subtitle">현재 실습의 그림·계산·근거와 작성자의 해석</p></div><span class="doc-state">학습자 초안 · 미승인</span></header><dl class="doc-control"><div><dt>자료 시점</dt><dd>${esc(meta.stage)} / ${esc(meta.as_of)}</dd></div><div><dt>작성자</dt><dd>${esc(d.author?.trim()||'미기입')}</dd></div><div><dt>문서 버전</dt><dd>${esc(d.version?.trim()||'v0.1')}</dd></div><div><dt>공유 대상</dt><dd>교재의 해당 업무 검토자 · 직접 확인 필요</dd></div></dl><section class="doc-section"><h3><span class="doc-section-num">01</span>검토 요약</h3>${prose(d.summary)}</section><section class="doc-section"><h3><span class="doc-section-num">02</span>조건과 원천</h3><p>원천의 승인 상태와 현재 계산의 조건을 구분합니다. 이 파일은 조회 자료를 복사한 검토 메모이며 회사 기록을 갱신하지 않습니다.</p>${conditionRows?`<div class="doc-table-wrap"><table><thead><tr><th>실습 조건</th><th>캡처한 값</th></tr></thead><tbody>${conditionRows}</tbody></table></div>`:''}${s.selections.length?`<p><strong>선택한 항목:</strong> ${s.selections.map(esc).join(' / ')}</p>`:''}<ul>${s.sources.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section class="doc-section"><h3><span class="doc-section-num">03</span>그림·계산 결과</h3><div class="doc-captured">${s.html}</div></section><section class="doc-section"><h3><span class="doc-section-num">04</span>결과의 해석</h3>${prose(d.analysis)}</section><section class="doc-section"><h3><span class="doc-section-num">05</span>권고와 결정 요청</h3>${prose(d.recommendation)}</section><section class="doc-section"><h3><span class="doc-section-num">06</span>미결 사항과 후속 확인</h3>${prose(d.open)}</section><footer class="doc-footer"><span>모아페이 Level 1 / ${esc(meta.stage)} / ${esc(d.version||'v0.1')}</span><span>학습자가 작성한 검토 메모 · 승인·제출 기록 없음</span></footer></article>`;
}
export function mountWorkbookReport(host,{module,m,meta,pause}){
 const key=meta.stage+':'+module;let d=drafts.get(key);if(!d){d={module,version:'v0.1',author:'',summary:'',analysis:'',recommendation:'',open:'',dirty:false,snapshot:null};drafts.set(key,d);}
 host.hidden=false;host.className='report-builder';
 host.innerHTML=`<h2>내 실습 결과를 문서로 묶기</h2><p>그림 아래에 근거와 해석을 더합니다. 현재 조건을 복사한 뒤 자신의 문장을 작성하고, 검토할 수 있는 한 문서로 내려받으세요. 전체 양식 본문은 교재의 작성 영역에서 이어 쓸 수 있습니다.</p><p><a href="documents.html?doc=${['charter','schedule','change'].includes(module)?module:'charter'}">실무 문서 형식의 완성 예시 비교</a> · <a href="learn.html?unit=${m.unit}&view=practice&phase=practice">${m.unit}단원 작성·검토로 이동</a></p><div class="report-fields"><label>작성자<input id="wr-author" value="${esc(d.author)}" placeholder="이름 또는 학습용 역할명"></label><label>문서 버전<input id="wr-version" value="${esc(d.version)}" placeholder="v0.1"></label>${fields.map(([id,label,help])=>`<label for="wr-${id}">${label}<small>${help}</small><textarea id="wr-${id}" rows="4">${esc(d[id])}</textarea></label>`).join('')}</div><div class="report-controls"><button id="wr-capture" class="primary">현재 조건으로 문서 만들기 / 갱신</button><button id="wr-export" disabled>검토 문서 HTML 내려받기</button><button id="wr-print" disabled>문서만 인쇄</button></div><p id="wr-status" class="report-status" role="status">자동 저장되지 않습니다. 이동 전에 파일을 보관하세요.</p><div id="wr-result" class="report-result"></div>`;
 const $=sel=>host.querySelector(sel),root=document.querySelector('#wb-content');let disposed=false,stale=!!d.snapshot,capturing=false,observer;
 const status=text=>$('#wr-status').textContent=text;
 const draw=()=>{if(d.snapshot)$('#wr-result').innerHTML=documentHTML(d,m,meta);};
 const invalidate=()=>{if(!d.snapshot||capturing)return;stale=true;$('#wr-export').disabled=true;$('#wr-print').disabled=true;status('실습 조건이나 선택이 바뀌었습니다. 해석을 확인한 뒤 「현재 조건으로 문서 만들기 / 갱신」을 누르세요. 아래 문서는 이전 조건입니다.');};
 for(const id of ['author','version',...fields.map(f=>f[0])])$('#wr-'+id).addEventListener('input',e=>{d[id]=e.target.value;d.dirty=true;draw();if(!stale)status('작성 내용이 미리보기에 반영되었습니다. 파일을 내려받아 보관하세요.');});
 root.addEventListener('input',invalidate);root.addEventListener('change',invalidate);root.addEventListener('click',invalidate);
 observer=new MutationObserver(invalidate);observer.observe(root,{childList:true,subtree:true,characterData:true});
 $('#wr-capture').onclick=async()=>{capturing=true;$('#wr-capture').disabled=true;try{pause();await new Promise(r=>setTimeout(r,500));if(disposed)return;observer.takeRecords();d.snapshot=capture(root);d.dirty=true;stale=false;draw();$('#wr-export').disabled=false;$('#wr-print').disabled=false;status('현재 조건·원천·그림을 복사했습니다. 미작성 항목을 채우고 해석을 검토한 뒤 보관하세요.');}finally{if(!disposed)$('#wr-capture').disabled=false;capturing=false;}};
 $('#wr-export').onclick=async()=>{if(!d.snapshot||stale)return;try{const r=await fetch('pm-document.css');if(!r.ok)throw Error('문서 서식을 불러오지 못했습니다. 다시 시도하세요.');const css=await r.text();if(disposed||stale)return;const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(m.title)} 검토 메모</title><style>body{margin:0;background:#edf1f7;padding:24px}main{max-width:1120px;margin:auto}${css}@media print{body{padding:0;background:white}}</style><main>${documentHTML(d,m,meta)}</main></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`MP-01_${module}_${meta.stage}_검토메모.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);d.dirty=false;status('문서 다운로드를 요청했습니다. HTML에는 현재 그림·계산·작성 문장이 함께 있습니다. 실제 파일 생성을 확인하세요.');}catch(e){status(e.message);}};
 $('#wr-print').onclick=()=>{if(stale)return;document.body.classList.add('report-print');window.print();document.body.classList.remove('report-print');};
 if(d.snapshot){draw();status('이 페이지에서 작성하던 초안입니다. 현재 실습 조건으로 갱신한 뒤 내보내세요.');}
 return ()=>{disposed=true;observer.disconnect();root.removeEventListener('input',invalidate);root.removeEventListener('change',invalidate);root.removeEventListener('click',invalidate);host.hidden=true;host.replaceChildren();};
}
