/* Capture genuine learner UI states in a fresh, headless context.
 * NODE_PATH=/path/to/node_modules PM_CHROME=/path/to/Chrome node tools/capture_home_tour.cjs
 * Optional --base-url URL --output DIR --frames DIR. Screenshots carry tutorial-only
 * click highlights; lesson text, ERP records and controls are never replaced.
 */
'use strict';
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),site=path.join(root,'_site');
const args=process.argv.slice(2),arg=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:args[i+1];};
const output=path.resolve(arg('--output',path.join(root,'ERP/tour-media')));
const frameRoot=path.resolve(arg('--frames',path.join(root,'tmp/home-tour-frames')));
const viewport={width:1040,height:640};
const clips=[];let server,browser,base=arg('--base-url','');
function serve(){return new Promise(resolve=>{server=http.createServer((req,res)=>{let p;try{p=decodeURIComponent(new URL(req.url,'http://local').pathname);}catch(_){res.writeHead(400).end();return;}const file=path.resolve(site,p.replace(/^\//,'')||'index.html');if(!file.startsWith(site+path.sep)){res.writeHead(403).end();return;}try{const type={'.html':'text/html;charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.md':'text/markdown;charset=utf-8'}[path.extname(file)]||'application/octet-stream';const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':type}).end(data);}catch(_){res.writeHead(404).end();}});server.listen(0,'127.0.0.1',()=>resolve('http://127.0.0.1:'+server.address().port+'/'));});}
async function overlay(page,label,selector,clip){await page.evaluate(({label,selector,clip})=>{document.querySelector('#tour-capture-overlay')?.remove();const host=document.createElement('div');host.id='tour-capture-overlay';host.style.cssText='position:fixed;inset:0;z-index:2147483647;pointer-events:none;font-family:system-ui,-apple-system,sans-serif;';const bar=document.createElement('div');bar.style.cssText='position:absolute;bottom:0;left:0;right:0;background:#172b4df2;color:#fff;padding:13px 20px;font-size:17px;line-height:1.5;box-shadow:0 -2px 14px #172b4d26;';const prefix=document.createElement('strong');prefix.textContent=clip+' · ';prefix.style.color='#f1cf9f';bar.append(prefix,document.createTextNode(label));host.append(bar);if(selector){const el=document.querySelector(selector);if(!el)throw Error('Overlay target missing: '+selector);const r=el.getBoundingClientRect();const ring=document.createElement('div');ring.style.cssText=`position:absolute;left:${r.left-5}px;top:${r.top-5}px;width:${r.width+10}px;height:${r.height+10}px;border:3px solid #c66b22;border-radius:8px;box-shadow:0 0 0 4px #fff9;`;host.append(ring);const cursor=document.createElement('div');cursor.style.cssText=`position:absolute;left:${Math.min(innerWidth-48,r.left+r.width*.73)}px;top:${Math.min(innerHeight-108,r.top+Math.min(r.height*.6,40))}px;width:42px;height:48px;filter:drop-shadow(0 2px 3px #0008);`;cursor.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 48"><path d="M4 3 L5 37 L14 29 L22 44 L28 41 L20 26 L32 25 Z" fill="#fff" stroke="#172b4d" stroke-width="2.8"/><circle cx="6" cy="5" r="4" fill="#c66b22" stroke="#fff" stroke-width="1.5"/></svg>';host.append(cursor);}(document.querySelector('dialog[open]')||document.body).append(host);},{label,selector,clip});}
async function clean(page){await page.evaluate(()=>document.querySelector('#tour-capture-overlay')?.remove());}
async function focus(page,selector,offset=84){await page.locator(selector).first().scrollIntoViewIfNeeded();await page.evaluate(({selector,offset})=>{const el=document.querySelector(selector),r=el.getBoundingClientRect();window.scrollTo({top:scrollY+r.top-offset,behavior:'instant'});},{selector,offset});await page.waitForTimeout(100);}
async function snap(clip,page,label,selector=null,durationMs=2000){await page.evaluate(()=>document.fonts.ready);await overlay(page,label,selector,clip.title);const filename=String(clip.frames.length+1).padStart(2,'0')+'.png',dest=path.join(frameRoot,clip.id,filename);fs.mkdirSync(path.dirname(dest),{recursive:true});await page.screenshot({path:dest,animations:'disabled'});const focus=await page.evaluate(selector=>{const rect=selector?document.querySelector(selector).getBoundingClientRect():null;return {x:Math.round(Math.max(0,Math.min(innerWidth,rect?rect.left+rect.width/2:innerWidth/2))),y:Math.round(Math.max(0,Math.min(innerHeight,rect?rect.top+rect.height/2:innerHeight/2)))};},selector);clip.frames.push({file:dest,label,durationMs,focus});await clean(page);}
async function learn(page,step=0,phase='concept'){await page.goto(base+'learn.html?unit=0&view=practice');await page.locator('#step-title').waitFor();await page.locator('.outline [data-step="'+step+'"]').click();if(phase!=='concept')await page.locator('[data-phase="'+phase+'"]').click();await focus(page,'#step-title',34);}
async function run(){fs.mkdirSync(output,{recursive:true});if(!base)base=await serve();if(!base.endsWith('/'))base+='/';browser=await chromium.launch({headless:true,executablePath:process.env.PM_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({viewport,deviceScaleFactor:1,acceptDownloads:true,reducedMotion:'reduce'});const page=await context.newPage();page.on('dialog',d=>d.dismiss());const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let c={id:'read',title:'1. 교재 읽기',frames:[]};clips.push(c);
 await page.goto(base+'learn.html?unit=0');await page.locator('#chapter-title').waitFor();await focus(page,'#unit-intro',12);await snap(c,page,'0단원에서 본문을 먼저 읽습니다.','[data-view="chapter"]',2300);
 await focus(page,'.chapter-toc',50);await snap(c,page,'차례에서 필요한 설명으로 바로 이동할 수 있습니다.','.chapter-toc a[href="#chapter-u0-reading"]',1900);
 await page.locator('.chapter-toc a[href="#chapter-u0-reading"]').click();await focus(page,'#chapter-u0-reading',24);await snap(c,page,'ERP에서 무엇을 확인할지 질문을 먼저 정합니다.',null,2900);
 await focus(page,'.chapter-handoff',46);await snap(c,page,'본문을 읽은 뒤 단계별 실습을 시작합니다.','#chapter-to-practice',1900);
 await page.locator('#chapter-to-practice').click();await focus(page,'#step-title',40);await snap(c,page,'개념 → 근거·예제 → 작성·검토 순서로 진행합니다.','.phase-tabs',2700);
 c={id:'source',title:'2. 원천자료 읽기',frames:[]};clips.push(c);
 await learn(page,0);await snap(c,page,'첫 실습에서 「근거·예제」를 누릅니다.','[data-phase="evidence"]',2100);
 await page.locator('[data-phase="evidence"]').click();await snap(c,page,'S01 원천 문서 읽기를 누릅니다.','[data-source="S01"]',2200);
 await page.locator('[data-source="S01"]').click();await page.locator('#source-panel:not([hidden])').waitFor();await focus(page,'#source-panel',35);await snap(c,page,'문서 ID·제목·기준일을 확인하고 사업 필요를 읽습니다.','#source-panel h3',3100);
 c={id:'erp',title:'3. ERP 조회',frames:[]};clips.push(c);
 await learn(page,3,'evidence');await snap(c,page,'「ST001 함께 조회」로 해당 업무의 ERP를 엽니다.','a[href*="menu=settlements"][href*="ST001"]',2200);
 const [erp]=await Promise.all([context.waitForEvent('page'),page.locator('a[href*="menu=settlements"][href*="ST001"]').click()]);await erp.locator('#results table').waitFor();await snap(c,erp,'실습 링크에는 조회 조건이 미리 채워져 있습니다.','#filters',2600);
 await erp.locator('#clear').click();await erp.waitForFunction(()=>document.querySelector('#value').value==='');await erp.selectOption('#field','정산번호');await erp.locator('#value').fill('ST001');await snap(c,erp,'직접 조회할 때는 정산번호와 ST001을 입력합니다.','#value',2100);
 await snap(c,erp,'「조회」를 눌러 현재 조건의 결과를 확인합니다.','#filters button.primary',1500);await erp.locator('#filters button.primary').click();await erp.waitForFunction(()=>document.querySelector('#count').textContent.includes('검색 결과 1건'));await snap(c,erp,'한 건의 지급예정액 222,440원을 확인합니다.','#count',2900);
 await erp.locator('#results [data-row]').first().click();await erp.locator('#detail[open]').waitFor();await snap(c,erp,'정산번호를 누르면 상세와 연관 기록을 함께 봅니다.','#detailbody h2',2700);await erp.close();
 c={id:'write',title:'4. 초안 작성',frames:[]};clips.push(c);
 await learn(page,6,'practice');await focus(page,'#study-writing',115);await snap(c,page,'파일 또는 웹 양식 중 편한 방법을 선택합니다.','#study-writing > summary',2200);
 await page.locator('#study-writing > summary').click();await focus(page,'#study-writing',35);await snap(c,page,'G00을 선택하고 양식 열기를 누릅니다.','#study-load',2100);await page.locator('#study-load').click();await page.locator('#study-preview textarea').first().waitFor();
 const fact=page.locator('#study-preview textarea[aria-label="S0 / [ ] · 확인한 사실"]').first();await fact.fill('박다은(P03)\n정산 운영책임자\n근거: S02');await fact.evaluate(el=>{const box=el.closest('.reading-table');box.scrollLeft=box.scrollWidth-box.clientWidth;});await focus(page,'#study-preview table',24);await snap(c,page,'근거 대장에 확인한 사실 한 가지를 적습니다.','#study-preview textarea[aria-label="S0 / [ ] · 확인한 사실"]',3100);
 await focus(page,'.study-tools',125);await snap(c,page,'이동하기 전에 작성본을 파일로 보관합니다.','#study-export',2200);const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#study-export').click()]);await download.saveAs(path.join(frameRoot,'sample-download.md'));await snap(c,page,'다운로드 요청 메시지와 내려받은 파일을 확인합니다.','#study-writing-status',2500);
 c={id:'review',title:'5. 검토하고 다음 단원으로',frames:[]};clips.push(c);
 await learn(page,7,'evidence');await focus(page,'#evidence-reading',22);await snap(c,page,'박다은·최민석의 검토 질문을 초안에 적용합니다.',null,3100);
 await focus(page,'#evidence-reading h4:nth-of-type(3)',30);await snap(c,page,'예시를 참고해 수정 전·후와 근거를 남깁니다.',null,3300);
 await page.locator('[data-phase=practice]').click();await focus(page,'#practice-reading',22);await snap(c,page,'검토 결과와 다음 단원에서 사용할 자료를 확인합니다.',null,2500);
 await focus(page,'[data-next-unit]',285);await snap(c,page,'G00 검토를 마치면 헌장 작성 단원으로 이어갑니다.','[data-next-unit]',2200);
 await page.locator('[data-next-unit]').click();await page.waitForFunction(()=>document.querySelector('#unit').value==='1'&&document.querySelector('#chapter-view')&&!document.querySelector('#chapter-view').hidden);await focus(page,'#unit-intro',14);await snap(c,page,'1단원에서 사업 필요·범위·권한을 헌장으로 연결합니다.','[data-view="chapter"]',2900);
 if(errors.length)throw Error(errors.join('\n'));const captured={capturedFrom:'local generated Pages',stage:'S0',viewport,clips};fs.writeFileSync(path.join(frameRoot,'capture.json'),JSON.stringify(captured,null,2));console.log(JSON.stringify({capture:path.join(frameRoot,'capture.json'),output,clips:clips.map(c=>({id:c.id,frames:c.frames.length,durationMs:c.frames.reduce((n,f)=>n+f.durationMs,0)}))},null,2));
}
run().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
