"""Source-checked, in-context textbook diagrams for Level 1 units 0–4.

Data only: the web and PDF renderers consume the same nodes and relationships.
Rows describe desktop placement; edges retain their meaning in a stacked view.
All examples use facts already available at the receiving section's stage.
"""


FIGURES = {
    0: [
        {
            'id': 'u0-money',
            'section': 'u0-concepts',
            'after': '회사의 현금 잔액이 얼마인지와 이번 프로젝트에 얼마를 사용할 수 있는지도 별개의 질문입니다.',
            'stage': 'S0',
            'title': '같은 원화라도 답하는 질문이 다릅니다',
            'lead': '금액을 보기 전에 누구의 돈이며 어떤 결정을 위한 값인지 나눕니다. 아래 화살표는 돈의 이동이 아니라 읽을 질문의 분류입니다.',
            'caption': '가맹점 지급예정액은 운영의 정산 대상, 회사 현금은 특정 시점의 회사 잔액, 프로젝트 자금 한도는 계획을 검토할 경계입니다. 세 숫자를 합치거나 회사 현금 전체를 프로젝트에 배정하면 금액의 의미와 사용 권한이 달라집니다.',
            'question': 'G00에 조회한 금액 하나를 골라 주인·기준일·관리 목적을 적어 보세요. 어느 갈래의 질문에 답하는 값인가요?',
            'sources': ['S01', 'S04', 'S05', 'S17'],
            'kind': 'compare',
            'nodes': [
                {'id': 'question', 'title': '어떤 돈을 읽는가', 'lines': ['같은 원 단위여도 의미는 다름', '주인·시점·목적부터 확인'], 'role': 'decision'},
                {'id': 'merchant', 'title': '가맹점 지급예정액', 'lines': ['가맹점에 지급할 예정액', '운영의 정산 업무에서 확인', '회사 매출과 구분'], 'role': 'evidence'},
                {'id': 'company', 'title': '회사 현금', 'lines': ['특정 시점의 회사 전체 잔액', '재무 자료에서 확인', '프로젝트 배정액과 구분'], 'role': 'evidence'},
                {'id': 'project', 'title': '프로젝트 자금 한도', 'lines': ['이번 사업의 투자 경계', '스폰서의 조건으로 확인', '상세 기준선은 별도 승인'], 'role': 'decision'},
            ],
            'edges': [
                {'from': 'question', 'to': 'merchant', 'label': '얼마를 지급할까'},
                {'from': 'question', 'to': 'company', 'label': '얼마를 보유했나'},
                {'from': 'question', 'to': 'project', 'label': '어디까지 계획할까'},
            ],
            'rows': [['question'], ['merchant', 'company', 'project']],
        },
        {
            'id': 'u0-settlement-flow',
            'section': 'u0-reading',
            'after': 'S05를 읽을 때는 시간 옆의 동사를 따라갑니다.',
            'stage': 'S0',
            'title': '정산 자료는 계산을 거쳐 비교와 후속 처리로 갑니다',
            'lead': 'S05의 하루 업무를 읽는 순서입니다. 각 화살표에서 다음 단계가 받아야 할 자료를 생각해 보세요.',
            'caption': '지급예정액을 계산하는 일과 다른 자료에 대조하는 일은 이어지지만 다른 업무입니다. 대사에서 발견한 불일치는 사유와 담당자를 확인할 대상이며 그 자체가 프로그램 결함이라는 뜻은 아닙니다. 09:00~11:00은 팀 경과시간으로 읽습니다.',
            'question': 'G00 업무흐름에서 한 화살표를 골라 넘길 정보와 확인할 담당자를 붙이세요. 취소 확인을 빠뜨리면 어느 뒤 단계의 판단이 달라질까요?',
            'sources': ['S05'],
            'kind': 'flow',
            'nodes': [
                {'id': 'receive', 'title': '거래파일 수신', 'lines': ['09:00', '정산할 거래 자료를 받음'], 'role': 'evidence'},
                {'id': 'cancel', 'title': '취소 확인', 'lines': ['09:20', '계산에 반영할 취소 확인'], 'role': 'work'},
                {'id': 'fee', 'title': '수수료 계산', 'lines': ['09:40', '지급예정액 계산에 반영'], 'role': 'work'},
                {'id': 'match', 'title': '지급예정 대조', 'lines': ['10:20', '은행 자료와 금액을 비교'], 'role': 'decision'},
                {'id': 'exception', 'title': '예외 전달', 'lines': ['11:00', '차이의 사유·담당을 연결'], 'role': 'result'},
            ],
            'edges': [
                {'from': 'receive', 'to': 'cancel', 'label': '거래 자료'},
                {'from': 'cancel', 'to': 'fee', 'label': '취소 반영'},
                {'from': 'fee', 'to': 'match', 'label': '계산 결과'},
                {'from': 'match', 'to': 'exception', 'label': '확인할 차이'},
            ],
            'rows': [['receive', 'cancel', 'fee'], ['match', 'exception']],
        },
    ],
    1: [
        {
            'id': 'u1-evidence-map',
            'section': 'u1-reading',
            'after': '중요한 사람이라는 이유로 모든 문서의 승인자로 적지 않습니다.',
            'stage': 'S0',
            'title': '원천의 사실을 헌장의 판단 항목으로 옮깁니다',
            'lead': '헌장의 세 항목을 읽는 경로만 골랐습니다. 자료를 한꺼번에 요약하기보다 지금 작성할 항목의 질문을 먼저 정합니다.',
            'caption': '같은 자료를 읽더라도 사업 필요, 목표의 측정, PM 권한은 다른 판단을 돕습니다. 특히 S17의 측정 회신은 목표를 구체화하는 입력이며 헌장 승인 자체가 아닙니다. 화살표마다 근거의 어떤 뜻을 문장에 반영했는지 설명해야 합니다.',
            'question': 'D01의 목표 한 문장에 측정 대상·기간·책임이 모두 있는지 확인하세요. 빠진 요소는 어떤 원천에서 보완할 수 있나요?',
            'sources': ['S01', 'S02', 'S05', 'S17'],
            'kind': 'lanes',
            'nodes': [
                {'id': 'need-source', 'title': 'S01·S05', 'lines': ['사업 요청과 현재 업무', '문제와 개선 이유를 읽음'], 'role': 'evidence'},
                {'id': 'measure-source', 'title': 'S01·S17', 'lines': ['현재값·목표값·측정 조건', '대상·기간·책임을 읽음'], 'role': 'evidence'},
                {'id': 'authority-source', 'title': 'S02', 'lines': ['회사 권한·문서 규정', '수행과 승인 역할을 읽음'], 'role': 'evidence'},
                {'id': 'need-field', 'title': 'D01 사업 필요', 'lines': ['현재 문제 → 업무 영향', '왜 시작하는지 설명'], 'role': 'work'},
                {'id': 'target-field', 'title': 'D01 목표와 측정', 'lines': ['성공을 판단할 조건', '미래 달성 결과와 구분'], 'role': 'work'},
                {'id': 'authority-field', 'title': 'D01 PM 권한', 'lines': ['배정·정보 요청·변경 상정', '기준선 단독 변경 불가'], 'role': 'work'},
            ],
            'edges': [
                {'from': 'need-source', 'to': 'need-field', 'label': '업무 문제를 연결'},
                {'from': 'measure-source', 'to': 'target-field', 'label': '측정 조건을 연결'},
                {'from': 'authority-source', 'to': 'authority-field', 'label': '권한 경로를 연결'},
            ],
            'rows': [['need-source', 'measure-source', 'authority-source'], ['need-field', 'target-field', 'authority-field']],
        },
        {
            'id': 'u1-charter-review',
            'section': 'u1-review',
            'after': '검토 의견을 모두 처리한 것과 스폰서가 착수를 승인한 것은 다릅니다.',
            'stage': 'S0',
            'title': '검토는 내용을, 승인은 착수 권한을 확인합니다',
            'lead': '현재 수행할 교육용 검토 절차를 그렸습니다. 마지막 칸은 앞으로 확인할 결정의 종류이며, 지금 승인이 발생했다는 기록은 아닙니다.',
            'caption': '운영·재무·보안·QA는 각자의 관점으로 조건을 검토하고 PM은 근거에 맞게 수정합니다. 의견을 모두 처리해도 자동으로 승인되지 않습니다. 스폰서의 헌장 결정은 승인 자료를 받은 뒤 별도로 대조하며 상세 기준선 승인은 이후 계획에서 다룹니다.',
            'question': 'D01의 수정 한 건을 골라 어느 검토 관점에서 무엇이 보완됐는지 설명하세요. 수정본의 상태를 아직 승인 대기로 두어야 하는 이유는 무엇인가요?',
            'sources': ['S02', 'S03', 'S17'],
            'kind': 'flow',
            'nodes': [
                {'id': 'draft', 'title': 'PM의 초안', 'lines': ['D01 v0.1', '근거·판단·미확정을 구분'], 'role': 'work'},
                {'id': 'review', 'title': '역할별 검토', 'lines': ['운영·재무·보안·QA', '목표·자금·경계·시험 확인'], 'role': 'decision'},
                {'id': 'revise', 'title': 'PM의 수정본', 'lines': ['D01 v0.2', '의견·수정 이유·근거 보존'], 'role': 'work'},
                {'id': 'waiting', 'title': '승인 상정', 'lines': ['검토 충족 여부를 대조', '현재 상태: 승인 대기'], 'role': 'work'},
                {'id': 'sponsor', 'title': '윤서진의 결정', 'lines': ['착수와 PM 권한의 승인', '결과는 이후 자료로 확인'], 'role': 'decision'},
            ],
            'edges': [
                {'from': 'draft', 'to': 'review', 'label': '검토 요청'},
                {'from': 'review', 'to': 'revise', 'label': '의견 반영'},
                {'from': 'revise', 'to': 'waiting', 'label': '조건 충족 확인'},
                {'from': 'waiting', 'to': 'sponsor', 'label': '권한 있는 결정 요청'},
            ],
            'rows': [['draft', 'review', 'revise'], ['waiting', 'sponsor']],
        },
    ],
    2: [
        {
            'id': 'u2-wbs-scope',
            'section': 'u2-concepts',
            'after': 'WBS를 나눌 때는 모든 포함 범위가 어딘가에 들어가고 같은 작업이 두 곳에 중복되지 않는지 확인합니다.',
            'stage': 'S1',
            'title': 'WBS는 결과를 나누고, 활동은 그 결과를 만듭니다',
            'lead': 'S06·S18의 상위 패키지를 결과 중심으로 펼쳤습니다. 날짜와 비용을 넣기 전에 각 가지가 무엇을 인도하는지 읽습니다.',
            'caption': '이 가지들은 수행 순서가 아니라 포함 범위의 분해입니다. 1.1에 A 요구정의와 B 설계가 함께 들어갈 수 있으므로 패키지와 활동을 일대일로 보지 않습니다. 검증 패키지에서 각 모듈의 개발비를 다시 세면 같은 작업이 중복됩니다.',
            'question': 'D11 사전에서 패키지 하나를 골라 완료를 확인할 인도물·담당·증거를 보완하세요. 운영 매뉴얼은 어느 패키지에서 인계해야 할까요?',
            'sources': ['S06', 'S18'],
            'kind': 'tree',
            'nodes': [
                {'id': 'scope', 'title': 'MP-01 개선 결과', 'lines': ['이번에 인도할 범위를 분해', '다음 가지는 계획의 구조'], 'role': 'result'},
                {'id': 'wbs11', 'title': '1.1 요구·설계', 'lines': ['명세·규격·권한 설계', '계획 담당: 이현우'], 'role': 'work'},
                {'id': 'wbs12', 'title': '1.2 조회', 'lines': ['R01 조회·R04 권한·로그', '계획 담당: 이현우'], 'role': 'work'},
                {'id': 'wbs13', 'title': '1.3 대사·예외', 'lines': ['R02/R03·소스·시험 증거', '계획 담당: 공급사 역할'], 'role': 'work'},
                {'id': 'wbs14', 'title': '1.4 검증', 'lines': ['통합·보안 회귀시험 증거', '계획 담당: 정유나'], 'role': 'work'},
                {'id': 'wbs15', 'title': '1.5 전환·교육', 'lines': ['매뉴얼·복구 절차·교육', '계획 담당: 박다은'], 'role': 'work'},
                {'id': 'wbs16', 'title': '1.6 안정화', 'lines': ['운영 관찰·미결 사항 인계', '계획 담당: 이현우'], 'role': 'work'},
            ],
            'edges': [
                {'from': 'scope', 'to': 'wbs11', 'label': '결과를 분해'},
                {'from': 'scope', 'to': 'wbs12', 'label': '결과를 분해'},
                {'from': 'scope', 'to': 'wbs13', 'label': '결과를 분해'},
                {'from': 'scope', 'to': 'wbs14', 'label': '결과를 분해'},
                {'from': 'scope', 'to': 'wbs15', 'label': '결과를 분해'},
                {'from': 'scope', 'to': 'wbs16', 'label': '결과를 분해'},
            ],
            'rows': [['scope'], ['wbs11', 'wbs12', 'wbs13'], ['wbs14', 'wbs15', 'wbs16']],
        },
        {
            'id': 'u2-r01-trace',
            'section': 'u2-example',
            'after': '중요한 것은 ID만 맞히는 것이 아니라 요구가 패키지와 시험에 연결되는 이유를 설명하는 것입니다.',
            'stage': 'S1',
            'title': '한 요구가 구현과 시험에서 같은 뜻을 유지합니다',
            'lead': '본문의 R01 부분 예제를 연결한 그림입니다. 요구가 무엇을 만들지와 무엇으로 확인할지로 갈라졌다가 시험 계획에서 만납니다.',
            'caption': 'WBS는 만들 결과를, 인수조건은 받아들일 기준을 설명합니다. 시험은 두 정보를 함께 사용합니다. T01을 연결한 것은 앞으로 검증할 경로를 정한 것이며 시험 통과나 현업 인수가 이미 끝났다는 뜻은 아닙니다.',
            'question': 'D09에서 R03을 골라 같은 연결을 직접 써 보세요. 어떤 패키지가 결과를 만들며, 어떤 조건을 시험에서 확인해야 하나요?',
            'sources': ['S03', 'S06', 'S18'],
            'kind': 'flow',
            'nodes': [
                {'id': 'voice', 'title': 'S03 운영의 요청', 'lines': ['가맹점별 지급예정액 확인', '요청자: 박다은'], 'role': 'evidence'},
                {'id': 'requirement', 'title': 'D09의 R01', 'lines': ['지정 날짜·가맹점 조회', '원천 발언과 ID를 보존'], 'role': 'work'},
                {'id': 'package', 'title': 'D11의 WBS 1.2', 'lines': ['조회 패키지에서 구현', '완료 증거를 정의'], 'role': 'work'},
                {'id': 'condition', 'title': 'R01의 인수조건', 'lines': ['지급액이 원천 계산과 일치', '같은 조건의 값을 비교'], 'role': 'decision'},
                {'id': 'test', 'title': 'T01 시험 계획', 'lines': ['정산금액을 검사할 방법', '현재는 기대결과를 정의'], 'role': 'work'},
            ],
            'edges': [
                {'from': 'voice', 'to': 'requirement', 'label': '기능과 이유를 정리'},
                {'from': 'requirement', 'to': 'package', 'label': '누가 무엇을 만들까'},
                {'from': 'requirement', 'to': 'condition', 'label': '어떻게 수락할까'},
                {'from': 'package', 'to': 'test', 'label': '검사할 인도물'},
                {'from': 'condition', 'to': 'test', 'label': '기대결과의 기준'},
            ],
            'rows': [['voice', 'requirement'], ['package', 'condition'], ['test']],
        },
    ],
    3: [
        {
            'id': 'u3-effort-duration',
            'section': 'u3-concepts',
            'after': '그래서 S06의 기간과 공수÷인원을 나란히 검토합니다.',
            'stage': 'S1',
            'title': '공수·인원·기간을 다른 입력으로 읽습니다',
            'lead': 'S06의 C 조회개발 조건입니다. 세 값은 같은 숫자를 다른 단위로 쓴 것이 아니라 배치 가능성을 함께 검토할 입력입니다.',
            'caption': '50인일÷4명=12.5일은 일을 균등하게 나눌 수 있다는 단순 환산입니다. 제공된 15영업일 추정과 작업의 병행·검토 조건을 함께 읽어야 합니다. 나눗셈만으로 기간을 확정하거나 기간에 공수를 다시 곱해 원가를 계산하지 않습니다.',
            'question': 'D21·D15에서 E의 공수·가용 인원·기간을 다른 열로 적어 보세요. 단순 환산값과 제공 기간이 같거나 다른 이유를 어떤 조건으로 확인하겠습니까?',
            'sources': ['S06'],
            'kind': 'compare',
            'nodes': [
                {'id': 'activity', 'title': 'C 조회개발', 'lines': ['아래 세 조건을 함께 읽음', '현재는 계획 추정'], 'role': 'work'},
                {'id': 'effort', 'title': '공수 50인일', 'lines': ['사람의 총 투입량', '개인별 투입을 합한 단위'], 'role': 'evidence'},
                {'id': 'people', 'title': '가용 인원 4명', 'lines': ['배정 가능한 개발 인원', '개인 하루 한도 1인일'], 'role': 'evidence'},
                {'id': 'duration', 'title': '기간 15영업일', 'lines': ['활동이 흐르는 작업 시간', '월~금 교육 달력 적용'], 'role': 'evidence'},
                {'id': 'check', 'title': '배치 가능성 검토', 'lines': ['50÷4=12.5는 단순 환산', '15일 추정의 조건도 확인'], 'role': 'decision'},
            ],
            'edges': [
                {'from': 'activity', 'to': 'effort', 'label': '얼마나 일할까'},
                {'from': 'activity', 'to': 'people', 'label': '누가 가능할까'},
                {'from': 'activity', 'to': 'duration', 'label': '얼마 동안 할까'},
                {'from': 'effort', 'to': 'check', 'label': '총량'},
                {'from': 'people', 'to': 'check', 'label': '가용 조건'},
                {'from': 'duration', 'to': 'check', 'label': '기간 조건'},
            ],
            'rows': [['activity'], ['effort', 'people', 'duration'], ['check']],
        },
        {
            'id': 'u3-fork-join',
            'section': 'u3-example',
            'after': '이번 FS·지연0 조건에서 E의 ES는 max(35,40)=40이 됩니다.',
            'stage': 'S1',
            'title': '합류점 E는 더 늦게 끝나는 선행을 기다립니다',
            'lead': 'A 이후의 B~E 구간만 보여 주는 부분 계산입니다. S06 원안의 FS·지연0 조건을 적용하며 숫자는 달력 날짜가 아닌 계산 시점입니다.',
            'caption': 'B 뒤의 C와 D는 병렬이지만 E에는 두 결과가 모두 필요합니다. 따라서 ES는 평균이 아니라 max(35,40)=40입니다. 본문의 후진 계산까지 대조하면 C에는 5영업일의 총여유가 있습니다. 관계나 기간을 바꾸면 합류 시점과 여유도 다시 계산해야 합니다.',
            'question': 'D14에서 C와 D의 기간을 각각 3영업일 늘렸다고 가정해 보세요. 어떤 경우에 E의 시작이 달라지는지 계산한 뒤 선행 열에 근거를 표시하세요.',
            'sources': ['S06'],
            'kind': 'network',
            'nodes': [
                {'id': 'b', 'title': 'B 설계', 'lines': ['기간 10영업일', 'A 이후 시점 20에 종료'], 'role': 'work'},
                {'id': 'c', 'title': 'C 조회개발', 'lines': ['기간 15영업일', 'ES 20 → EF 35', '총여유 5영업일'], 'role': 'work'},
                {'id': 'd', 'title': 'D 대사·예외', 'lines': ['기간 20영업일', 'ES 20 → EF 40'], 'role': 'work'},
                {'id': 'e', 'title': 'E 통합검증', 'lines': ['C와 D의 결과가 모두 필요', 'ES=max(35,40)=40'], 'role': 'decision'},
            ],
            'edges': [
                {'from': 'b', 'to': 'c', 'label': 'FS·지연0'},
                {'from': 'b', 'to': 'd', 'label': 'FS·지연0'},
                {'from': 'c', 'to': 'e', 'label': '시점 35에 준비'},
                {'from': 'd', 'to': 'e', 'label': '시점 40에 준비'},
            ],
            'rows': [['b'], ['c', 'd'], ['e']],
        },
    ],
    4: [
        {
            'id': 'u4-budget-structure',
            'section': 'u4-concepts',
            'after': '사용과 전용에는 제공된 내부 규칙이 적용됩니다.',
            'stage': 'S1',
            'title': '원가기준선과 총자금의 경계를 나눕니다',
            'lead': '금액을 넣기 전 D17의 구조를 읽는 그림입니다. 화살표는 합산 관계이며 현금을 지급하는 순서를 뜻하지 않습니다.',
            'caption': '작업원가와 우발예비비로 원가기준선 후보를 만들고, 기준선 밖의 관리예비비를 더해 총자금 요구를 설명합니다. 예비자금 확보와 실제 사용은 별도 사건입니다. 지금 S1의 숫자는 계획 후보이며 승인된 기준선이나 발생 비용이 아닙니다.',
            'question': 'D17의 예비비 두 종류를 이 구조에 배치하세요. 사용 전 자금 확보 요구와 실제 지출을 어느 열에서 나눌지 설명해 보세요.',
            'sources': ['S06', 'S07', 'S19'],
            'kind': 'budget',
            'nodes': [
                {'id': 'work', 'title': '작업원가', 'lines': ['정의된 활동의 추정 비용', '수량·단가·고정가 근거'], 'role': 'evidence'},
                {'id': 'contingency', 'title': '우발예비비', 'lines': ['식별한 위험의 대응 비용', '원가기준선 안에 포함'], 'role': 'evidence'},
                {'id': 'baseline', 'title': '원가기준선 후보', 'lines': ['작업원가 + 우발예비비', '통합 검토 후 승인 대상'], 'role': 'work'},
                {'id': 'management', 'title': '관리예비비', 'lines': ['원가기준선 밖에 둠', '별도 승인·전용 규칙 적용'], 'role': 'decision'},
                {'id': 'funding', 'title': '총자금 요구', 'lines': ['기준선 후보 + 관리예비비', '전체 자금 필요를 설명'], 'role': 'result'},
            ],
            'edges': [
                {'from': 'work', 'to': 'baseline', 'label': '합산'},
                {'from': 'contingency', 'to': 'baseline', 'label': '합산'},
                {'from': 'baseline', 'to': 'funding', 'label': '합산'},
                {'from': 'management', 'to': 'funding', 'label': '별도 항목으로 합산'},
            ],
            'rows': [['work', 'contingency'], ['baseline', 'management'], ['funding']],
        },
        {
            'id': 'u4-cost-payment',
            'section': 'u4-example',
            'after': '금액이 다른 이유를 문장으로 설명할 수 있어야 합니다.',
            'stage': 'S1',
            'title': '같은 용역의 약정·비용·지급을 따로 읽습니다',
            'lead': 'S19의 외주 11월 부분검수분 20백만원을 대상으로 한 계획 설명입니다. 실제 발주·검수·지급이 발생했다는 기록은 아닙니다.',
            'caption': '11월의 외주 비용 계획 20백만원과 지급 계획 12백만원은 같은 용역의 서로 다른 사건입니다. 차이 8백만원은 다음 지급 조건으로 이어지며 추가 비용이 아닙니다. 발주·검수·청구·지급 금액을 모두 더하면 같은 일을 여러 번 집계합니다.',
            'question': 'D17의 11월 행에서 비용 52백만원과 현금 44백만원의 차이를 이 그림과 연결해 설명하세요. 12월에도 비용과 지급을 같은 값으로 복사해도 될까요?',
            'sources': ['S04', 'S06', 'S08', 'S19'],
            'kind': 'lanes',
            'nodes': [
                {'id': 'order', 'title': '발주 계획', 'lines': ['용역을 구매하는 약정', '발주액은 실제 비용 아님'], 'role': 'work'},
                {'id': 'recognition', 'title': '부분검수·비용 계획', 'lines': ['11월 외주 20백만원', '용역 수행에 따른 비용'], 'role': 'evidence'},
                {'id': 'invoice', 'title': '청구 조건', 'lines': ['검수 후 청구', '지급할 채무와 조건 확인'], 'role': 'work'},
                {'id': 'november', 'title': '11월 지급 계획', 'lines': ['외주 현금 12백만원', '8백만원은 후속 지급 예정'], 'role': 'result'},
                {'id': 'remaining', 'title': '잔액 지급 계획', 'lines': ['남은 8백만원은 1월', '최종 인수 후 지급 조건'], 'role': 'result'},
            ],
            'edges': [
                {'from': 'order', 'to': 'recognition', 'label': '인도·검수 계획'},
                {'from': 'recognition', 'to': 'invoice', 'label': '검수 후 청구'},
                {'from': 'invoice', 'to': 'november', 'label': '부분 지급 조건'},
                {'from': 'november', 'to': 'remaining', 'label': '잔액 지급 조건'},
            ],
            'rows': [['order', 'recognition', 'invoice'], ['november', 'remaining']],
        },
    ],
}


AUDIT = {
    0: {
        'weakness': '금액의 의미와 정산의 순서가 표·문장으로만 제시되어 서로 다른 개념을 한 번에 기억해야 한다.',
        'rationale': '개념절에서는 돈을 질문별로 갈라 읽고 조회절에서는 업무가 흐르는 순서를 보여 준다. 분류 화살표와 작업 흐름 화살표의 의미를 명시해 혼동을 막는다.',
        'checked': 'S01·S04·S17의 자금 한도와 현금 구분, S05의 다섯 업무·시각·팀 경과시간 및 정산 조정 맥락을 대조했다.',
    },
    1: {
        'weakness': '독자가 여러 원천에서 어떤 헌장 항목으로 이동할지와 검토·승인의 책임 경계를 머릿속에서만 연결해야 한다.',
        'rationale': '항목 세 개의 입력 경로와 승인 상정까지의 절차를 별도 그림으로 분리한다. S0 그림에는 AP00 결과·날짜·승인 사실을 넣지 않는다.',
        'checked': 'S02의 헌장 승인권자·PM 권한, S17의 목표 측정 회신과 별도 상세 기준선 승인 조건을 대조했다. 역할별 검토는 교재의 교육용 절차로 표시한다.',
    },
    2: {
        'weakness': '요구·WBS·활동·시험의 차이가 말로 설명되어 같은 표의 이름만 다른 것으로 읽힐 수 있다.',
        'rationale': '상위 WBS는 결과의 포함 관계, R01 그림은 하나의 약속을 구현과 검증으로 추적하는 관계로 제시한다. 그림은 범위·시험 결과의 승인 상태를 만들지 않는다.',
        'checked': 'S06·S18의 1.1~1.6·계획 담당·인도물과 S03/S18의 R01→1.2→T01 연결을 대조했다. 공급자 회사 선정은 확정하지 않는다.',
    },
    3: {
        'weakness': '공수·기간·인원의 차이와 합류점의 최대값 계산이 긴 설명 안에 있어 관계의 모양을 바로 보기 어렵다.',
        'rationale': '개념절에서 세 입력을 한 검토로 모으고 예제절에서 B~E의 실제 분기·합류만 그린다. 전체 네트워크 답안 대신 기존 C 부분 예제에 한정한다.',
        'checked': 'S06의 50인일·4명·15영업일, FS·지연0, B 이후 C/D 및 E 합류와 본문 C의 ES20·EF35·여유5를 대조했다. 3일 증가는 질문의 가정 실험으로만 둔다.',
    },
    4: {
        'weakness': '기준선의 구성 관계와 같은 용역의 비용·현금 시점 차이를 글과 월별 표 사이에서 오가며 해석해야 한다.',
        'rationale': '예비비는 합산 구조, 외주 부분검수분은 계획 사건의 흐름으로 나눠 보여 준다. 총 예산의 완성 숫자와 실제 거래 결과는 추가하지 않는다.',
        'checked': 'S06·S19의 예비비 경계, S04의 발주·비용·지급 구분, S08의 검수 후 청구 조건과 S19의 외주20/12/잔액8 및 최종인수 후 1월 지급 조건을 대조했다.',
    },
}
