"""Static, source-grounded explanatory figures for Level 1 units 5–9.

Data only: the common renderer owns SVG/PDF layout and accessibility.
Each figure belongs to a specific section and inherits its release stage.
Arrows express the relationship named on the edge, not an invented calendar.
"""


FIGURES = {
    5: [
        {
            "id": "u5-quality",
            "section": "u05-01",
            "after": "계획을 적은 날에 실제 시험을 통과했다고 쓰지 않습니다.",
            "stage": "S1",
            "title": "절차 점검과 제품 검사는 다릅니다",
            "lead": "품질계획에서 두 갈래의 확인을 설계합니다. 현업 인수에는 실제 결과를 검사한 증거가 필요합니다.",
            "caption": "요구와 시험의 연결을 점검했다고 제품이 합격한 것은 아닙니다. 이 그림은 앞으로 수행할 확인 절차이며, S1에서는 시험 통과 수나 현업 인수 결과를 채우지 않습니다.",
            "question": "D18의 한 요구를 골라, 절차가 작동하는지 보는 항목과 실제 결과를 검사하는 항목을 각각 적어 보세요. 검사 증거는 누구에게 넘기나요?",
            "sources": ["S02", "S07", "S18"],
            "kind": "compare",
            "nodes": [
                {"id": "q-plan", "title": "품질계획 · D18", "lines": ["무엇을 합격으로 볼까?", "기준·방법·담당·증거"], "role": "work"},
                {"id": "q-process", "title": "절차 점검 · D19", "lines": ["요구–설계–시험 연결 확인", "좋은 결과를 만드는 과정 점검"], "role": "work"},
                {"id": "q-test", "title": "제품 검사 · D20", "lines": ["기대결과와 실제결과 대조", "정유나가 시험 증거 확인"], "role": "evidence"},
                {"id": "q-accept", "title": "현업 인수 · D12", "lines": ["박다은이 수용 여부 판단", "검증과 인수 권한을 구분"], "role": "decision"},
            ],
            "edges": [
                {"from": "q-plan", "to": "q-process", "label": "만드는 과정"},
                {"from": "q-plan", "to": "q-test", "label": "완성한 결과"},
                {"from": "q-test", "to": "q-accept", "label": "검증 증거 인계"},
            ],
            "rows": [["q-plan"], ["q-process", "q-test"], ["q-accept"]],
        },
        {
            "id": "u5-risk",
            "section": "u05-03",
            "after": "한 위험만 발생하는 경우에는 다른 위험이 발생하지 않을 확률도 곱해야 합니다.",
            "stage": "S1",
            "title": "위험 분석을 대응 업무로 연결하기",
            "lead": "같은 위험을 우선순위와 손실 규모라는 두 질문으로 분석한 뒤, 실제 담당자가 수행할 조치로 바꿉니다.",
            "caption": "정성 점수와 기대손실은 단위가 다릅니다. S07의 독립 가정으로 네 경우를 계산하되 평균이 모든 손실을 보장하지는 않습니다. 실행 후 재평가하며, 이미 발생한 사건은 이슈로 기록합니다.",
            "question": "D25의 K02에서 정성 순위의 근거와 D26의 금액 분석을 나누어 쓰세요. 그 판단이 D14·D17의 어느 항목을 다시 보게 하나요?",
            "sources": ["S07", "S19"],
            "kind": "network",
            "nodes": [
                {"id": "r-event", "title": "위험 식별 · D25", "lines": ["원인 → 불확실 사건 → 영향", "확률·영향·책임을 기록"], "role": "evidence"},
                {"id": "r-rank", "title": "정성 분석", "lines": ["확률 × 영향등급", "먼저 점검할 순위 결정"], "role": "decision"},
                {"id": "r-amount", "title": "정량 분석 · D26", "lines": ["독립 가정의 네 경우", "확률 × 손실 금액을 합산", "평균과 최대손실을 구분"], "role": "work"},
                {"id": "r-response", "title": "대응 계획", "lines": ["책임·발생 신호·예방조치", "일정·예산 반영 여부 검토"], "role": "work"},
                {"id": "r-monitor", "title": "실행 후 재평가", "lines": ["실행 증거로 잔여 위험 확인", "최초 평가도 함께 보존"], "role": "work"},
                {"id": "r-issue", "title": "발생한 사건은 이슈", "lines": ["발생 사실·영향·조치", "D03에서 담당·기한 추적"], "role": "result"},
            ],
            "edges": [
                {"from": "r-event", "to": "r-rank", "label": "무엇부터 볼까"},
                {"from": "r-event", "to": "r-amount", "label": "노출은 얼마일까"},
                {"from": "r-rank", "to": "r-response", "label": "우선순위"},
                {"from": "r-amount", "to": "r-response", "label": "예비비 근거"},
                {"from": "r-response", "to": "r-monitor", "label": "실행 증거 수신 후"},
                {"from": "r-monitor", "to": "r-issue", "label": "발생이 확인되면"},
            ],
            "rows": [["r-event"], ["r-rank", "r-amount"], ["r-response"], ["r-monitor", "r-issue"]],
        },
    ],
    6: [
        {
            "id": "u6-procurement",
            "section": "u06-02",
            "after": "평가가 타당해도 권한 있는 서명과 발주는 별도로 진행됩니다.",
            "stage": "S1",
            "title": "선정 권고가 계약이 되기까지",
            "lead": "같은 범위를 평가하는 판단과 회사를 대표해 서명하는 권한은 서로 다른 단계입니다.",
            "caption": "S1에서는 평가·권고·계약 검토 초안을 준비합니다. 그림의 서명은 이후 거칠 절차이며, 지금 계약 체결이나 발주가 완료됐다는 뜻이 아닙니다. 평가자의 판단이 승인권자의 서명을 대신하지 않습니다.",
            "question": "D28에서 점수에 따른 권고 근거와 서명 전 확인할 조건을 나누어 표시하세요. 강태훈·최민석·윤서진은 각각 어떤 일을 하나요?",
            "sources": ["S02", "S08", "S19"],
            "kind": "flow",
            "nodes": [
                {"id": "p-scope", "title": "같은 범위부터 확인", "lines": ["R02·R03와 인도물 대조", "D27 SOW·검수 조건"], "role": "evidence"},
                {"id": "p-evaluate", "title": "사전 기준으로 평가", "lines": ["기술·납기·가격 가중치", "두 제안에 동일하게 적용"], "role": "work"},
                {"id": "p-recommend", "title": "선정 권고 · D28", "lines": ["점수와 조건 검토의 이유", "권고와 체결 상태를 구분"], "role": "decision"},
                {"id": "p-draft", "title": "강태훈 · 계약 작성", "lines": ["범위·검수·보증·지급 조건", "현재는 계약 초안"], "role": "work"},
                {"id": "p-review", "title": "최민석 · 계약 검토", "lines": ["재무·지급 조건 대조", "검토 의견과 수정 기록"], "role": "evidence"},
                {"id": "p-sign", "title": "윤서진 · 서명 절차", "lines": ["권한자의 서명 근거 확인", "S1에서는 서명 전"], "role": "decision"},
            ],
            "edges": [
                {"from": "p-scope", "to": "p-evaluate", "label": "비교 대상 고정"},
                {"from": "p-evaluate", "to": "p-recommend", "label": "산식·조건 해석"},
                {"from": "p-recommend", "to": "p-draft", "label": "권고안 상정"},
                {"from": "p-draft", "to": "p-review", "label": "조건 검토"},
                {"from": "p-review", "to": "p-sign", "label": "보완 후 서명 요청"},
            ],
            "rows": [["p-scope", "p-evaluate"], ["p-recommend", "p-draft"], ["p-review", "p-sign"]],
        },
        {
            "id": "u6-communication",
            "section": "u06-04",
            "after": "D31에서는 현재와 목표 상태의 차이에 맞춰 무엇을 시연하고 누구에게 어떤 회신을 받을지 작성합니다.",
            "stage": "S1",
            "title": "받는 사람이 다르면 정보도 다릅니다",
            "lead": "PM은 같은 사실을 수신자의 업무와 권한에 맞춰 전달하고, 필요한 회신과 참여 행동까지 계획합니다.",
            "caption": "발송은 상대가 이해하거나 지원한다는 증거가 아닙니다. D23은 정보 전달·확인 방법을, D31은 필요한 협의와 참여 행동을 정합니다. 내부 인건비는 가맹점 요약에서 제외합니다.",
            "question": "D23의 가맹점 안내에서 내부 작업회의와 다른 내용을 표시하세요. 회신이 없을 때 누가 무엇을 확인할지 D31과 연결할 수 있나요?",
            "sources": ["S02", "S08"],
            "kind": "lanes",
            "nodes": [
                {"id": "c-pm", "title": "PM · 전달할 사실 정리", "lines": ["사실·업무 영향·확인 요청", "D23 수신자별 작성"], "role": "work"},
                {"id": "c-sponsor", "title": "스폰서에게", "lines": ["결정할 사항과 영향", "주간보고에서 검토"], "role": "decision"},
                {"id": "c-team", "title": "작업팀에게", "lines": ["수행할 일·담당·기한", "작업회의에서 장애물 확인"], "role": "work"},
                {"id": "c-merchant", "title": "가맹점에게", "lines": ["업무 영향·확인 요청", "내부 인건비 공유 제외"], "role": "evidence"},
                {"id": "c-feedback", "title": "수신과 질문 확인", "lines": ["발송·회신·미확인을 구분", "후속 담당과 확인 방법"], "role": "evidence"},
                {"id": "c-engagement", "title": "참여 계획 · D31", "lines": ["현재·목표 상태의 차이", "시연·협의·회신 활동 설계"], "role": "work"},
            ],
            "edges": [
                {"from": "c-pm", "to": "c-sponsor", "label": "의사결정에 필요한 정보"},
                {"from": "c-pm", "to": "c-team", "label": "실행에 필요한 정보"},
                {"from": "c-pm", "to": "c-merchant", "label": "이용에 필요한 정보"},
                {"from": "c-sponsor", "to": "c-feedback", "label": "검토·회신"},
                {"from": "c-team", "to": "c-feedback", "label": "질문·확인"},
                {"from": "c-merchant", "to": "c-feedback", "label": "이해·피드백"},
                {"from": "c-feedback", "to": "c-engagement", "label": "필요한 다음 행동"},
            ],
            "rows": [["c-pm"], ["c-sponsor", "c-team", "c-merchant"], ["c-feedback", "c-engagement"]],
        },
    ],
    7: [
        {
            "id": "u7-execution",
            "section": "u07-03",
            "after": "승인이 시작점을 제공해도 실행 결과는 앞으로 별도 확인해야 합니다.",
            "stage": "S1A",
            "title": "승인된 계획을 실행 업무로 옮기기",
            "lead": "승인은 일할 기준을 줍니다. PM은 그 기준을 공지하고 담당자가 수행할 업무와 확인할 증거를 구체화합니다.",
            "caption": "AP01은 S09에서 확인한 승인 사실입니다. 이후 수행·확인 상자는 앞으로 관리할 절차이며 현재 완료 사실이 아닙니다. 학생의 임시 작업 ID는 실제 실행 원장을 받은 뒤 대응시키고, 지시일과 완료일을 구분합니다.",
            "question": "D03의 환경점검 지시를 골라 담당·기한·완료 증거를 써 보세요. 지금 확정할 수 있는 항목과 실행 자료를 기다려야 하는 항목은 무엇인가요?",
            "sources": ["S02", "S09"],
            "kind": "flow",
            "nodes": [
                {"id": "x-approval", "title": "AP01 · 통합 승인", "lines": ["S09의 승인 조건 대조", "BL01과 적용 버전 연결"], "role": "decision"},
                {"id": "x-notice", "title": "승인본 공지", "lines": ["PM이 문서 소유자에게 전달", "같은 기준으로 일하도록 안내"], "role": "work"},
                {"id": "x-order", "title": "작업지시 · D03", "lines": ["학생 임시 작업 ID 부여", "결정·담당·기한 연결"], "role": "work"},
                {"id": "x-perform", "title": "수행할 업무", "lines": ["승인 범위 안에서 실행", "무엇을 남겨야 완료일까?"], "role": "work"},
                {"id": "x-proof", "title": "기다릴 실행 증거", "lines": ["실제 수행일·확인자·결과", "원천 수신 전엔 확인 대기"], "role": "evidence"},
                {"id": "x-update", "title": "확인 후 상태 갱신", "lines": ["지시와 실제 결과 대조", "후속 업무·보고에 반영"], "role": "result"},
            ],
            "edges": [
                {"from": "x-approval", "to": "x-notice", "label": "적용할 기준"},
                {"from": "x-notice", "to": "x-order", "label": "회의 결정을 구체화"},
                {"from": "x-order", "to": "x-perform", "label": "책임·기한·완료조건"},
                {"from": "x-perform", "to": "x-proof", "label": "수행 후 기록"},
                {"from": "x-proof", "to": "x-update", "label": "근거를 확인한 뒤"},
            ],
            "rows": [["x-approval", "x-notice"], ["x-order", "x-perform"], ["x-proof", "x-update"]],
        },
        {
            "id": "u7-team-knowledge",
            "section": "u07-05",
            "after": "원래 회의록·근거 ID를 연결하면 맥락을 다시 찾을 수 있습니다.",
            "stage": "S2",
            "title": "팀의 합의를 확인 가능한 교훈으로",
            "lead": "사람에 대한 평가를 적기 전에 업무 조건과 양쪽의 필요를 듣습니다. 합의와 그 효과가 확인된 상태도 나눕니다.",
            "caption": "S20에는 질문 취합 방식의 합의와 12월 7일 후속 확인 계획이 있습니다. 아직 효과 측정 결과는 없습니다. D04에는 적용 조건·시도한 방식·검증 대기를 남기고, 확인된 효과가 생기면 보완합니다.",
            "question": "D22의 면담 기록에서 관찰 사실·각자의 필요·합의·후속 확인을 나누세요. D04에 지금 쓸 수 있는 교훈과 아직 단정할 수 없는 효과는 무엇인가요?",
            "sources": ["S02", "S10", "S20"],
            "kind": "network",
            "nodes": [
                {"id": "t-fact", "title": "관찰한 업무 이슈", "lines": ["질문 대응으로 집중시간 손실", "S20의 당사자 발언 확인"], "role": "evidence"},
                {"id": "t-dev", "title": "개발의 필요", "lines": ["오전 집중시간 보호", "업무 중단 조건을 살핌"], "role": "evidence"},
                {"id": "t-qa", "title": "QA의 필요", "lines": ["모호한 명세를 당일 확인", "질문할 통로가 필요"], "role": "evidence"},
                {"id": "t-agree", "title": "업무 방식 합의", "lines": ["매일 16:30 질문 취합", "이현우·정유나가 조정"], "role": "decision"},
                {"id": "t-follow", "title": "효과는 후속 확인", "lines": ["12월 7일 확인 예정", "중단 횟수·질문 미해결 건수"], "role": "work"},
                {"id": "t-lesson", "title": "교훈 기록 · D04", "lines": ["조건·시도한 방식 기록", "효과는 검증 대기로 표시"], "role": "result"},
            ],
            "edges": [
                {"from": "t-fact", "to": "t-dev", "label": "개발 측 설명"},
                {"from": "t-fact", "to": "t-qa", "label": "QA 측 설명"},
                {"from": "t-dev", "to": "t-agree", "label": "필요를 함께 반영"},
                {"from": "t-qa", "to": "t-agree", "label": "질문 통로 유지"},
                {"from": "t-agree", "to": "t-follow", "label": "합의의 효과 확인"},
                {"from": "t-agree", "to": "t-lesson", "label": "현재의 시도 기록"},
                {"from": "t-follow", "to": "t-lesson", "label": "결과 확인 후 보완"},
            ],
            "rows": [["t-fact"], ["t-dev", "t-qa"], ["t-agree", "t-follow"], ["t-lesson"]],
        },
    ],
    8: [
        {
            "id": "u8-earned-value",
            "section": "u08-03",
            "after": "SPI의 부족한 비율을 전체 기간에 곱해 지연 일수라고 쓰지 않습니다.",
            "stage": "S2",
            "title": "세 숫자가 서로 다른 질문에 답합니다",
            "lead": "PV·EV·AC를 같은 기준일과 범위에 놓습니다. EV를 기준으로 양쪽을 비교하면 일정 가치와 원가 성과를 나누어 해석할 수 있습니다.",
            "caption": "S10의 EV 50백만원과 현금 지급 50백만원은 숫자가 같아도 다른 측정값입니다. AC에는 인식된 비용을 쓰며, SV의 금액 차이를 달력 지연일로 바꾸지 않습니다. 계산 뒤 원인과 남은 작업을 확인합니다.",
            "question": "D05에서 AC 대신 현금 지급액을 사용하면 원가 편차가 어떻게 가려지나요? SV와 SPI를 설명한 다음 실제 일정 영향을 확인할 자료도 적어 보세요.",
            "sources": ["S09", "S10"],
            "kind": "compare",
            "nodes": [
                {"id": "e-date", "title": "비교 기준 맞추기", "lines": ["상태일 2026-11-30", "같은 범위·단위: 백만원"], "role": "evidence"},
                {"id": "e-pv", "title": "PV · 계획가치 60", "lines": ["이날까지 완료할 계획인", "작업의 예산 가치"], "role": "evidence"},
                {"id": "e-ev", "title": "EV · 획득가치 50", "lines": ["완료했다고 검증한", "작업의 예산 가치"], "role": "evidence"},
                {"id": "e-ac", "title": "AC · 실제원가 58", "lines": ["수행한 작업에 인식한 비용", "현금 지급과 구분"], "role": "evidence"},
                {"id": "e-schedule", "title": "일정 가치 비교", "lines": ["SV = EV − PV", "SPI = EV ÷ PV", "지연일은 별도 일정 분석"], "role": "work"},
                {"id": "e-cost", "title": "원가 성과 비교", "lines": ["CV = EV − AC", "CPI = EV ÷ AC", "완료 가치와 소비 비용 비교"], "role": "work"},
            ],
            "edges": [
                {"from": "e-date", "to": "e-pv", "label": "계획한 가치"},
                {"from": "e-date", "to": "e-ev", "label": "검증한 가치"},
                {"from": "e-date", "to": "e-ac", "label": "인식한 비용"},
                {"from": "e-pv", "to": "e-schedule", "label": "계획과 대조"},
                {"from": "e-ev", "to": "e-schedule", "label": "완료한 가치"},
                {"from": "e-ev", "to": "e-cost", "label": "완료한 가치"},
                {"from": "e-ac", "to": "e-cost", "label": "실제원가와 대조"},
            ],
            "rows": [["e-date"], ["e-pv", "e-ev", "e-ac"], ["e-schedule", "e-cost"]],
        },
        {
            "id": "u8-change-baseline",
            "section": "u08-05",
            "after": "BL01은 비교와 의사결정 이력을 설명할 수 있도록 남기고 BL02를 새 적용 기준으로 연결합니다.",
            "stage": "S3",
            "title": "변경 승인 뒤 두 버전을 함께 관리하기",
            "lead": "변경요청·검토·결정의 근거를 남긴 뒤 새 기준을 적용합니다. 이전 기준선도 남아 있어야 무엇을 왜 바꿨는지 설명할 수 있습니다.",
            "caption": "S12의 AP02가 승인한 범위만 갱신합니다. BL01을 삭제하거나 과거 실적을 새 계획에 맞춰 고치지 않습니다. 요청과 권고는 승인 전 상태이며, CT01처럼 변경 없는 항목도 승인 회신으로 확인합니다.",
            "question": "D06의 AP02에서 D09·D14·D17로 이어지는 변경 항목을 찾아보세요. 적용할 새 버전과 비교를 위해 보존할 이전 버전은 어디에 표시했나요?",
            "sources": ["S02", "S11", "S12"],
            "kind": "network",
            "nodes": [
                {"id": "b-request", "title": "CR01 · 변경요청", "lines": ["새 요구와 이유를 접수", "요청 자체는 승인 아님"], "role": "evidence"},
                {"id": "b-analysis", "title": "PM · 영향 분석", "lines": ["범위·일정·원가·자원 비교", "대안과 권고를 D06에 기록"], "role": "work"},
                {"id": "b-review", "title": "관계자 영향 검토", "lines": ["최민석·이현우·박다은", "조건과 감수할 영향을 확인"], "role": "evidence"},
                {"id": "b-decision", "title": "윤서진 · AP02 승인", "lines": ["S12의 결정 범위를 대조", "승인 근거·시점 연결"], "role": "decision"},
                {"id": "b-old", "title": "BL01 · 이력 보존", "lines": ["원래 약속과 비교 근거", "기존 버전을 삭제하지 않음"], "role": "evidence"},
                {"id": "b-new", "title": "BL02 · 새 기준 적용", "lines": ["승인된 범위에 맞춰 갱신", "과거 실적은 소급 수정 안 함"], "role": "result"},
                {"id": "b-docs", "title": "연결 문서 함께 갱신", "lines": ["요구·WBS·일정·예산", "시험·작업·통지 기록"], "role": "work"},
            ],
            "edges": [
                {"from": "b-request", "to": "b-analysis", "label": "영향 확인"},
                {"from": "b-analysis", "to": "b-review", "label": "대안·권고 상정"},
                {"from": "b-review", "to": "b-decision", "label": "스폰서 결정"},
                {"from": "b-decision", "to": "b-old", "label": "이전 기준 보존"},
                {"from": "b-decision", "to": "b-new", "label": "승인 후 적용"},
                {"from": "b-new", "to": "b-docs", "label": "같은 버전으로 업무"},
            ],
            "rows": [["b-request", "b-analysis", "b-review"], ["b-decision"], ["b-old", "b-new", "b-docs"]],
        },
    ],
    9: [
        {
            "id": "u9-acceptance-close",
            "section": "u09-01",
            "after": "PM은 각 담당자가 확인한 증거를 모으고 서로 빠진 조건이 없는지 대조해 종료 판단을 가능하게 합니다.",
            "stage": "S4",
            "title": "검증·인수·종료의 책임을 나누기",
            "lead": "끝났다는 주장마다 필요한 증거와 판단자가 다릅니다. 각 확인을 연결해야 프로젝트 종료를 상정할 수 있습니다.",
            "caption": "화살표는 증거의 인계 관계이며 모든 서명의 실제 날짜 순서를 뜻하지 않습니다. QA 검증은 박다은의 현업 인수나 윤서진의 종료 승인을 대신하지 않습니다. 보안 확인과 운영·계약·자원 인계도 별도로 연결합니다.",
            "question": "D12의 요구 한 건에서 QA 증거·AT01을 찾고, 관련 보안 조건을 SC01과 대조해 보세요. D07의 종료 조건으로 이어지려면 어떤 이관과 잔여 책임 확인이 더 필요한가요?",
            "sources": ["S02", "S13", "S15", "S21"],
            "kind": "lanes",
            "nodes": [
                {"id": "a-require", "title": "승인 요구 · D09", "lines": ["약속한 인도물과 인수조건", "변경된 요구도 포함"], "role": "evidence"},
                {"id": "a-verify", "title": "정유나 · QA 검증", "lines": ["시험·보완·재시험 증거", "조건 충족 여부 확인"], "role": "evidence"},
                {"id": "a-accept", "title": "박다은 · AT01 인수", "lines": ["현업이 결과를 받아들임", "D12에 인수 근거 연결"], "role": "decision"},
                {"id": "a-security", "title": "오수빈 · SC01 확인", "lines": ["권한·로그 등 보안 확인", "현업 인수와 범위 구분"], "role": "decision"},
                {"id": "a-transfer", "title": "운영·계약·자원 인계", "lines": ["매뉴얼·복구·지원 창구", "잔액·보증·잔여 책임 확인"], "role": "result"},
                {"id": "a-close", "title": "윤서진 · AP03 종료", "lines": ["인수와 잔여 책임 인계 확인", "종료 승인본 보존"], "role": "decision"},
            ],
            "edges": [
                {"from": "a-require", "to": "a-verify", "label": "시험 판단 기준"},
                {"from": "a-verify", "to": "a-accept", "label": "검증 증거"},
                {"from": "a-verify", "to": "a-security", "label": "보안 시험 증거"},
                {"from": "a-accept", "to": "a-transfer", "label": "현업 수용 확인"},
                {"from": "a-security", "to": "a-transfer", "label": "보안 확인 연결"},
                {"from": "a-transfer", "to": "a-close", "label": "종료 조건 상정"},
            ],
            "rows": [["a-require", "a-verify"], ["a-accept", "a-security"], ["a-transfer", "a-close"]],
        },
        {
            "id": "u9-benefit-handoff",
            "section": "u09-05",
            "after": "아직 제공되지 않은 미래 측정 결과를 성공 또는 실패로 채우지 말고 담당·기간·방법·보고처만 인계합니다.",
            "stage": "S4",
            "title": "프로젝트가 끝나도 이어지는 책임",
            "lead": "종료보고에는 끝낸 업무와 다음 담당자가 이어갈 업무를 함께 적습니다. 사업 효과는 정해진 기간의 운영 자료로 나중에 판단합니다.",
            "caption": "화살표는 책임 인계 관계입니다. 보증은 종료일부터 새로 시작하는 것이 아니라 최종검수 다음 날부터 이어집니다. 첫 주 65분은 사전 관찰치이며, 20영업일의 편익 측정 결과는 아직 제공되지 않았습니다.",
            "question": "D07에서 보증 창구와 편익 측정의 담당·기간·보고처를 구분했나요? 아직 측정하지 않은 효과를 달성 사실로 적은 문장이 없는지도 확인하세요.",
            "sources": ["S13", "S14", "S17", "S19", "S21"],
            "kind": "lanes",
            "nodes": [
                {"id": "h-close", "title": "AP03 · 프로젝트 종료", "lines": ["수행과 잔여 책임 인계 확인", "운영 책임은 계속 남음"], "role": "decision"},
                {"id": "h-operate", "title": "운영·지원 이어가기", "lines": ["OM01·RB01·QA-01 인계", "운영 박다은 · 기술 이현우"], "role": "work"},
                {"id": "h-warranty", "title": "무상 보완 창구 유지", "lines": ["1월 23일~2월 21일", "강태훈 접수 창구", "지급채무 정리와 별개"], "role": "work"},
                {"id": "h-measure", "title": "편익 측정 예정", "lines": ["2월 1일~26일 · 20영업일", "박다은이 운영일지 취합", "미래 결과는 아직 없음"], "role": "work"},
                {"id": "h-method", "title": "측정 항목 구분", "lines": ["팀의 일별 순대사 경과시간", "운영자별 투입시간은 별도", "예외 이력 누락도 기록"], "role": "evidence"},
                {"id": "h-report", "title": "운영 결과로 목표 판단", "lines": ["2월 26일 윤서진에게 보고", "측정 자료로 달성 여부 확인"], "role": "decision"},
            ],
            "edges": [
                {"from": "h-close", "to": "h-operate", "label": "운영 책임 인계"},
                {"from": "h-close", "to": "h-warranty", "label": "계속되는 보증"},
                {"from": "h-close", "to": "h-measure", "label": "편익 추적 인계"},
                {"from": "h-operate", "to": "h-method", "label": "일별 운영 자료"},
                {"from": "h-measure", "to": "h-method", "label": "같은 측정 기준"},
                {"from": "h-method", "to": "h-report", "label": "기간 자료를 모아 판단"},
            ],
            "rows": [["h-close"], ["h-operate", "h-warranty", "h-measure"], ["h-method", "h-report"]],
        },
    ],
}


AUDIT = {
    5: {
        "gap": "품질의 절차 관리·제품 검사·현업 인수와 위험의 정성·정량 분석이 글로 연이어 설명되어, 서로 다른 질문과 산출물의 관계를 한눈에 비교하기 어렵다.",
        "selection": "u05-01의 두 품질 확인을 갈래로, u05-03의 정성·정량 분석을 대응 계획으로 합류하는 흐름으로 표현한다. 전체 계산 정답 대신 판단 과정과 문서 인계를 보인다.",
        "stage_check": "S1 원천만 사용한다. 시험 통과 결과·실제 인수·잔여 확률을 넣지 않고 이후 확인 절차라는 점을 명시한다.",
    },
    6: {
        "gap": "계약 권한을 설명하는 표와 소통·참여 개념이 분리되어 있어 평가 권고가 실제 서명으로 바뀌는 조건, 수신자마다 정보가 달라지는 이유가 눈에 잘 들어오지 않는다.",
        "selection": "u06-02에 범위 확인부터 권한자 서명 절차까지 연결하고, u06-04에 세 수신자의 정보 요구와 회신·참여 계획을 배치한다.",
        "stage_check": "S1의 계약·발주는 미체결 상태로 표현한다. 실제 공급자 선정 결과나 계약·발주 ID를 미리 제시하지 않는다.",
    },
    7: {
        "gap": "승인 후의 지시와 실제 완료, 팀 합의와 검증된 효과가 긴 문단 속에서 이어져 상태의 경계를 놓치기 쉽다.",
        "selection": "u07-03은 승인→공지→지시→증거 확인의 절차로, u07-05는 양측 필요→합의→후속 확인→교훈의 관계로 읽게 한다.",
        "stage_check": "S1A 도식은 AP01만 확정 사실로 두고 임시 작업 ID와 증거 대기를 표시한다. S2 도식의 후속 효과는 아직 확인 전이며 12월 7일 결과를 지어내지 않는다.",
    },
    8: {
        "gap": "PV·EV·AC의 비슷한 금액과 여러 산식을 읽으며 무엇을 비교하는지 잃기 쉽고, 변경 후 이전 기준선이 어디에 남는지도 문장만으로 파악하기 어렵다.",
        "selection": "u08-03은 EV를 가운데 두고 일정·원가 비교를 나누며, u08-05는 승인 뒤 BL01 보존과 BL02 적용을 갈래로 보여 준다.",
        "stage_check": "S2 도식에는 11월 30일 원천 수치와 산식만 사용한다. AP02·BL02의 실제 결정은 S3 절의 도식에만 배치한다.",
    },
    9: {
        "gap": "검증·인수·보안·운영이관·종료의 각 책임자와, 종료 뒤 보증·편익 측정을 이어가는 담당자를 동시에 이해하기 어렵다.",
        "selection": "u09-01은 증거와 판단 권한의 연결을, u09-05는 종료 후 운영·보증·편익의 서로 다른 책임과 기간을 보여 준다.",
        "stage_check": "S4 승인·인계 사실을 사용하되 화살표는 실제 서명 날짜 순서가 아님을 명시한다. 미래 편익 결과는 제시하지 않고 담당·측정·보고 계획만 표시한다.",
    },
}
