"""Learning front door: demonstrate useful PM outputs before explaining the tools."""
from html import escape as e
from landing_content import LESSON_PATH


def site_navigation(prefix='', current=''):
    links = [('learn.html?unit=0','교재','개념 읽기 · 작성·검토'),('erp.html','ERP','회사 원천자료 조회'),('visual.html','시각화 워크북','흐름·일정·숫자 실습'),('guide.html','사용 안내','시작부터 따라 하기'),('resources.html','자료실','양식·PDF 보관')]
    items = ''.join(f'<a href="{prefix}{url}" aria-label="{label}" aria-describedby="site-tip-{i}"'+(' aria-current="page"' if url.split('?')[0] == current else '')+f'><strong>{label}</strong><small id="site-tip-{i}">{description}</small></a>' for i,(url,label,description) in enumerate(links))
    target = 'workspace' if current == 'erp.html' else 'content'
    return f'''<a class="site-skip" href="#{target}">본문으로 바로가기</a><header class="site-header"><nav class="site-nav" aria-label="주 메뉴"><a class="site-brand" href="{prefix}index.html"><span class="site-brand-mark" aria-hidden="true">PM</span><span><strong>모아페이 실습실</strong><small>금융 프로젝트 매니지먼트</small></span></a><button type="button" id="site-menu-toggle" aria-expanded="false" aria-controls="site-links">메뉴</button><div class="site-links" id="site-links">{items}</div></nav></header>'''


def site_footer(prefix=''):
    return f'''<footer class="site-footer"><div><strong>모아페이 · 금융 프로젝트 PM 실습</strong><p>자료를 읽고, 관계를 이해하고, 검토할 결과물을 만듭니다.</p></div><div><a href="{prefix}guide.html">처음 사용하는 학생을 위한 안내</a><br><a href="{prefix}pathway.html">완료 기준과 Level 2·3·4</a> · <a href="{prefix}standards.html">PMI 표준 적용</a></div><div>교육용 가상 회사 · 학습 기록 서버 제출 없음<br>실제 수강생 파일럿과 수행 시간 측정은 별도 진행합니다.</div></footer>'''


def charter_fallback():
    return '''<div class="preview-charter"><div class="preview-document-heading"><span>프로젝트 헌장 · 검토용 예시</span><strong>정산 알림 개선</strong></div><div class="charter-objective"><span>시작할 이유</span><p>수동 확인을 줄이고, 알림 누락을 추적한다.</p></div><div class="charter-columns"><div><h4>목표</h4><p>대상과 측정 기간을 정하고<br>운영책임자가 확인한다.</p></div><div><h4>범위</h4><p>알림·확인·이력 조회를 포함한다.<br>정산 계산식 변경은 제외한다.</p></div></div><div class="charter-authority"><span>PM 초안</span><b>→</b><span>관련 부서 검토</span><b>→</b><span>스폰서 결정</span></div><p class="preview-small">서로 연결된 목표·범위·권한을 보고 착수 조건을 검토합니다.</p></div>'''


def render_landing(modules, tour):
    outcomes = ['업무 파악 메모','프로젝트 헌장','요구 추적표·WBS','네트워크·간트','예산·자금 계획','품질 기준·리스크','계약·책임·소통','통합계획·실행 기록','성과보고·변경요청','인수·이관·종료보고']
    units = ''.join(f'<a href="learn.html?unit={i}"><span>{i:02}</span><div><strong>{e(title)}</strong><small>{outcomes[i]}</small></div><b aria-hidden="true">↗</b></a>' for i,title in enumerate(modules))
    path = ''.join(f'<div><span>{"·".join(map(str,p["units"]))}단원</span><strong>{e(p["label"])}</strong><p>{e(p["result"])}</p></div>' for p in LESSON_PATH)
    return f'''
<section class="result-hero" aria-labelledby="landing-title"><div><p class="course-label">금융 프로젝트 PM 부트캠프 · Level 1</p><h1 id="landing-title">첫 프로젝트의 결과물을<br>직접 만들어보세요.</h1></div><div class="result-hero-intro"><p>헌장으로 시작할 이유를 설명하고,<br>간트로 일정의 근거를 보여 주고,<br>성과보고로 다음 결정을 요청하는 연습.</p><div class="result-actions"><a class="result-button result-primary" href="learn.html?unit=0">0단원부터 시작하기 →</a><a class="result-button result-secondary" href="guide.html">사용 순서 먼저 보기</a></div><p class="result-small">설치·로그인 없이 시작합니다. SQL은 선택 학습입니다.</p></div></section>
<section id="outcome-lab" aria-labelledby="outcome-heading" class="outcome-lab"><div class="outcome-top"><div><span class="outcome-live-mark" aria-hidden="true"></span><h2 id="outcome-heading">미리 보는 실습 결과</h2></div><span>별도 가상 사례 · PREVIEW-01</span></div><div class="outcome-tabs" aria-label="살펴볼 결과 선택"><button type="button" data-outcome="charter" aria-pressed="true"><span>헌장</span><strong>시작할 이유를 한눈에</strong></button><button type="button" data-outcome="schedule" aria-pressed="false"><span>일정</span><strong>끝나는 날짜의 근거를</strong></button><button type="button" data-outcome="change" aria-pressed="false"><span>성과·변경</span><strong>숫자에서 다음 결정으로</strong></button></div>
<div class="outcome-workbench"><aside class="outcome-input"><span class="outcome-side-label">실습 전의 메모</span><h3 id="outcome-before-title">무엇부터 정해야 할까요?</h3><div id="outcome-before"><p>알림 업무를 개선한다.</p><p>일정을 맞춰 개발한다.</p><p>완료하면 관련 부서에 공유한다.</p></div><div class="outcome-missing"><strong>이 메모만으로는</strong><p id="outcome-question">성공의 기준, 만들 범위, 승인할 사람을 같은 뜻으로 이해하기 어렵습니다.</p></div></aside><div class="outcome-output"><div class="outcome-output-heading"><div><span>실습 후에 만들 결과의 예시</span><h3 id="outcome-title">목표·범위·책임이 연결된 헌장</h3></div><span class="outcome-status">검토용</span></div><div id="outcome-surface" data-phase="3">{charter_fallback()}</div><div id="outcome-adjust" class="outcome-adjust" hidden></div></div></div>
<div class="outcome-transport"><button id="outcome-play" type="button" aria-pressed="false" hidden>만드는 과정 재생</button><div class="outcome-steps" aria-label="결과를 만드는 순서"><button type="button" data-outcome-step="0" aria-current="false"><span>1</span>자료 읽기</button><button type="button" data-outcome-step="1" aria-current="false"><span>2</span>기준 정리</button><button type="button" data-outcome-step="2" aria-current="false"><span>3</span>관계 연결</button><button type="button" data-outcome-step="3" aria-current="step"><span>4</span>결과 검토</button></div></div><p id="outcome-caption" role="status">목표·범위·권한이 연결되면 시작 조건을 관련 부서와 함께 검토할 수 있습니다.</p>
<div class="outcome-takeaway"><div><strong>이 결과로 답할 수 있는 질문</strong><p id="outcome-answer">왜 시작하는가, 어디까지 하는가, 누가 결정하는가?</p></div><div><a id="outcome-workbook" href="visual.html?lab=charter">같은 유형의 시각화 실습 열기</a><a id="outcome-lesson" href="learn.html?unit=1&view=practice">작성 방법을 교재에서 읽기</a></div></div><p id="outcome-notice">PREVIEW-01 ‘정산 알림 개선’은 결과의 형태를 보여 주는 별도 가상 사례입니다. 본 실습 MP-01의 완성 답안·실제 승인·수강생 성과가 아닙니다. 조작해도 ERP 원본이나 자료 시점은 바뀌지 않습니다.</p><noscript><p class="outcome-nojs">위 헌장 예시는 그대로 읽을 수 있습니다. 일정·성과 예시와 재생은 JavaScript를 켜면 사용할 수 있습니다.</p></noscript></section>
<section id="comparison" class="result-section result-growth" aria-labelledby="growth-title"><div class="result-section-heading"><h2 id="growth-title">문서가 늘어나는 만큼,<br>설명할 수 있는 일이 늘어납니다.</h2><p>완성도는 양식의 칸 수로 판단하지 않습니다. 내가 만든 그림과 기록으로 다음 질문에 답하고, 근거를 다시 찾을 수 있는지 확인합니다.</p></div><div class="result-growth-rows"><div><span>헌장</span><p>“좋은 시스템을 만들자”는 요청</p><b aria-hidden="true">→</b><strong>목표·범위·승인권한을 구분해 착수 조건을 설명하기</strong></div><div><span>일정</span><p>작업 이름과 희망 날짜</p><b aria-hidden="true">→</b><strong>선후관계·총여유·주공정으로 지연의 영향을 설명하기</strong></div><div><span>성과</span><p>돈을 얼마나 썼는지의 보고</p><b aria-hidden="true">→</b><strong>계획·획득가치·실제원가를 구분해 검토할 대안을 제시하기</strong></div></div><p class="result-small">위 비교는 학습 목표입니다. 실제 변화는 직접 만든 문서의 근거·일관성·검토 흔적으로 확인합니다.</p></section>
<section id="menu-map" class="result-section result-menu-section" aria-labelledby="menu-map-title"><div class="result-section-heading"><h2 id="menu-map-title">메뉴는 필요한 순간에,<br>다시 교재로 돌아오면 됩니다.</h2><p>처음에는 교재와 ERP부터 익히세요. 시각화는 관계를 이해하는 도구이고, 문서 작성·검토는 교재 안에서 이어 갑니다.</p></div><ol class="result-menu-route"><li><span>읽을 때</span><a href="learn.html?unit=0">교재</a><p>이번 업무의 이유와 만들 문서를 확인합니다.</p><small>다음 화면: 근거·예제</small></li><li><span>사실이 필요할 때</span><a href="erp.html">ERP</a><p>문서 ID·기준일·조회 조건으로 실제 근거를 찾습니다.</p><small>돌아올 곳: 교재의 작성 항목</small></li><li><span>관계가 헷갈릴 때</span><a href="visual.html">시각화 워크북</a><p>흐름·간트·숫자를 조작하며 차이의 원인을 확인합니다.</p><small>남길 것: 해석과 검토 질문</small></li><li><span>내 결과를 정리할 때</span><a href="learn.html?unit=0&view=practice&step=draft&phase=practice">교재의 작성·검토</a><p>근거와 판단을 양식에 쓰고, 검토 의견을 반영합니다.</p><small>이동하기 전: 작성본 내려받기</small></li><li><span>양식·인쇄본이 필요할 때</span><a href="resources.html">자료실</a><p>현재 단계의 PDF와 편집할 빈 양식을 받습니다.</p><small>보관할 곳: 내 작업 폴더</small></li></ol><div class="result-guide-link"><p><strong>어디를 눌러야 할지 막히면</strong> 사용 안내에서 한 건의 조회부터 메모 저장까지 따라 해보세요.</p><a class="result-button result-secondary" href="guide.html#guide-first-lab">첫 실습을 순서대로 따라 하기</a></div></section>
<div class="result-tour">{tour}</div>
<section class="result-section result-curriculum" aria-labelledby="curriculum-title"><div><h2 id="curriculum-title">하나의 금융 프로젝트,<br>착수부터 종료까지.</h2><p>모아페이의 내부 PM 한지우가 되어 가맹점 정산 확인·대사·예외처리 개선 프로젝트를 진행합니다.</p><p>10개 단원에서 49개 프로세스를 다룹니다. 앞 단원의 문서를 다음 업무의 입력으로 가져가며 검토·수정·승인을 연결합니다.</p><details><summary>어떤 순서로 깊어지나요?</summary><div class="result-path">{path}</div></details></div><div class="result-unit-list">{units}</div></section>
<section class="result-final"><div><h2>첫날에는 한 장의<br>업무 파악 메모부터.</h2><p>회사와 사람을 이해하고, 숫자의 의미를 구분하고,<br>다음에 확인할 질문을 남기는 것부터 시작합니다.</p></div><div><a class="result-button result-primary" href="learn.html?unit=0">첫 업무 시작하기</a><a href="guide.html#guide-start">시작 전에 준비할 것 확인하기</a><a href="pathway.html">Level 1 완료 기준과 다음 레벨</a></div></section>'''
